/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APISchoolAC23 } from './aPISchoolAC23';

export class APIAutocompleteSchoolResult23 {
    /**
    * List of the schools that match the query
    */
    'schoolMatches'?: Array<APISchoolAC23>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schoolMatches",
            "baseName": "schoolMatches",
            "type": "Array<APISchoolAC23>"
        }    ];

    static getAttributeTypeMap() {
        return APIAutocompleteSchoolResult23.attributeTypeMap;
    }
}

