/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APIDistrictAC } from './aPIDistrictAC';

export class APIAutocompleteDistrictResult {
    /**
    * List of the districts that match the query
    */
    'districtMatches'?: Array<APIDistrictAC>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtMatches",
            "baseName": "districtMatches",
            "type": "Array<APIDistrictAC>"
        }    ];

    static getAttributeTypeMap() {
        return APIAutocompleteDistrictResult.attributeTypeMap;
    }
}

