/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APIPolyline } from './aPIPolyline';

export class APIBoundary12 {
    /**
    * Collection of one or more Google Maps encoded polylines representing the attendance boundary. IMPORTANT: Polyline strings are JSON-encoded with escaped backslashes (double backslashes). You must unescape before passing to Google Maps decoding functions. Multiple polylines represent districts/schools with non-contiguous boundary areas.
    */
    'polylineCollection'?: Array<APIPolyline>;
    /**
    * Boundary as a WKT (Well-Known Text) MULTIPOLYGON string with explicit latitude/longitude vertices. Can be used directly with GIS software, PostGIS, or any system that accepts WKT geometry. Format: MULTIPOLYGON (((-122.27 47.77, ...)))
    */
    'polylines'?: string;
    /**
    * States whether there is a boundary available
    */
    'hasBoundary'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "polylineCollection",
            "baseName": "polylineCollection",
            "type": "Array<APIPolyline>"
        },
        {
            "name": "polylines",
            "baseName": "polylines",
            "type": "string"
        },
        {
            "name": "hasBoundary",
            "baseName": "hasBoundary",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return APIBoundary12.attributeTypeMap;
    }
}

