/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIChronicAbsenteeismRate {
    /**
    * School year using spring-year convention (e.g. 2025 = the 2024-2025 school year)
    */
    'year'?: number;
    /**
    * ChronicAbsenteeism Rate at the School Level (Pro or Enterprise level only)
    */
    'schoolChronicAbsenteeismRate'?: number;
    /**
    * ChronicAbsenteeism Rate at the District Level (Pro or Enterprise level only)
    */
    'districtChronicAbsenteeismRate'?: number;
    /**
    * ChronicAbsenteeism Rate at the State Level (Pro or Enterprise level only)
    */
    'stateChronicAbsenteeismRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "schoolChronicAbsenteeismRate",
            "baseName": "schoolChronicAbsenteeismRate",
            "type": "number"
        },
        {
            "name": "districtChronicAbsenteeismRate",
            "baseName": "districtChronicAbsenteeismRate",
            "type": "number"
        },
        {
            "name": "stateChronicAbsenteeismRate",
            "baseName": "stateChronicAbsenteeismRate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIChronicAbsenteeismRate.attributeTypeMap;
    }
}

