/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APICounty {
    /**
    * County in which the school or district is located
    */
    'countyName'?: string;
    /**
    * SchoolDigger URL for all schools in this county
    */
    'countyURL'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "countyName",
            "baseName": "countyName",
            "type": "string"
        },
        {
            "name": "countyURL",
            "baseName": "countyURL",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APICounty.attributeTypeMap;
    }
}

