/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APIDistrictSummary21 } from './aPIDistrictSummary21';

export class APIDistrictListRank21 {
    /**
    * Year this ranking list represents (2018 = 2017-18)
    */
    'rankYear'?: number;
    /**
    * Year rankings returned for comparison (2018 = 2017-18)
    */
    'rankYearCompare'?: number;
    /**
    * The years for which SchoolDigger district rankings are available for this state
    */
    'rankYearsAvailable'?: Array<number>;
    /**
    * The total count of districts in the entire rank list
    */
    'numberOfDistricts'?: number;
    /**
    * The total count of pages in your query list based on given per_page value
    */
    'numberOfPages'?: number;
    'districtList'?: Array<APIDistrictSummary21>;
    'rankCompareYear'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rankYear",
            "baseName": "rankYear",
            "type": "number"
        },
        {
            "name": "rankYearCompare",
            "baseName": "rankYearCompare",
            "type": "number"
        },
        {
            "name": "rankYearsAvailable",
            "baseName": "rankYearsAvailable",
            "type": "Array<number>"
        },
        {
            "name": "numberOfDistricts",
            "baseName": "numberOfDistricts",
            "type": "number"
        },
        {
            "name": "numberOfPages",
            "baseName": "numberOfPages",
            "type": "number"
        },
        {
            "name": "districtList",
            "baseName": "districtList",
            "type": "Array<APIDistrictSummary21>"
        },
        {
            "name": "rankCompareYear",
            "baseName": "rankCompareYear",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIDistrictListRank21.attributeTypeMap;
    }
}

