/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APIBoundary12 } from './aPIBoundary12';
import { APIChronicAbsenteeismRate } from './aPIChronicAbsenteeismRate';
import { APICounty } from './aPICounty';
import { APIDropoutRate } from './aPIDropoutRate';
import { APIGraduationRate } from './aPIGraduationRate';
import { APILEARankHistory } from './aPILEARankHistory';
import { APILEAYearlyDetail } from './aPILEAYearlyDetail';
import { APILocation } from './aPILocation';
import { APISchoolFinance } from './aPISchoolFinance';
import { APITestScoreWrapper } from './aPITestScoreWrapper';

export class APIDistrictFull21 {
    /**
    * SchoolDigger District ID Number (7 digits)
    */
    'districtID'?: string;
    /**
    * District name
    */
    'districtName'?: string;
    /**
    * District phone number
    */
    'phone'?: string;
    /**
    * SchoolDigger URL for this district
    */
    'url'?: string;
    'address'?: APILocation;
    /**
    * The low grade served by this district (PK = Prekindergarten, K = Kindergarten)
    */
    'lowGrade'?: string;
    /**
    * The high grade served by this district
    */
    'highGrade'?: string;
    'numberTotalSchools'?: number;
    'numberPrimarySchools'?: number;
    'numberMiddleSchools'?: number;
    'numberHighSchools'?: number;
    'numberAlternativeSchools'?: number;
    'boundary'?: APIBoundary12;
    /**
    * Yearly per-student spending data. Array is sorted most recent year first. spendingPerStudent is available at Pro level; detailed federal/state/local and personnel/non-personnel breakdowns require Enterprise level.
    */
    'finance'?: Array<APISchoolFinance>;
    /**
    * 4-year adjusted cohort graduation rates at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
    */
    'graduationRates'?: Array<APIGraduationRate>;
    /**
    * Annual dropout rates at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
    */
    'dropoutRates'?: Array<APIDropoutRate>;
    /**
    * Chronic absenteeism rates (students missing 15+ days) at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first. Data availability varies by state.
    */
    'chronicAbsenteeismRates'?: Array<APIChronicAbsenteeismRate>;
    /**
    * Indicates whether this district\'s boundary includes the specified location from nearLatitude/nearLongitude
    */
    'isWithinBoundary'?: boolean;
    'county'?: APICounty;
    /**
    * SchoolDigger yearly rank history for this district, sorted most recent year first. Districts are ranked statewide regardless of level.
    */
    'rankHistory'?: Array<APILEARankHistory>;
    /**
    * Yearly enrollment and staffing details for this district. Array is sorted most recent year first. Includes detailed FTE staffing breakdowns by role (teachers by level, administrators, counselors, librarians, support staff).
    */
    'districtYearlyDetails'?: Array<APILEAYearlyDetail>;
    /**
    * Standardized test score results with district and state comparisons. Each entry represents one test/subject/grade/year combination. District-level records do not include schoolTestScore. Requires Pro or Enterprise API subscription.
    */
    'testScores'?: Array<APITestScoreWrapper>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtID",
            "baseName": "districtID",
            "type": "string"
        },
        {
            "name": "districtName",
            "baseName": "districtName",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "APILocation"
        },
        {
            "name": "lowGrade",
            "baseName": "lowGrade",
            "type": "string"
        },
        {
            "name": "highGrade",
            "baseName": "highGrade",
            "type": "string"
        },
        {
            "name": "numberTotalSchools",
            "baseName": "numberTotalSchools",
            "type": "number"
        },
        {
            "name": "numberPrimarySchools",
            "baseName": "numberPrimarySchools",
            "type": "number"
        },
        {
            "name": "numberMiddleSchools",
            "baseName": "numberMiddleSchools",
            "type": "number"
        },
        {
            "name": "numberHighSchools",
            "baseName": "numberHighSchools",
            "type": "number"
        },
        {
            "name": "numberAlternativeSchools",
            "baseName": "numberAlternativeSchools",
            "type": "number"
        },
        {
            "name": "boundary",
            "baseName": "boundary",
            "type": "APIBoundary12"
        },
        {
            "name": "finance",
            "baseName": "finance",
            "type": "Array<APISchoolFinance>"
        },
        {
            "name": "graduationRates",
            "baseName": "graduationRates",
            "type": "Array<APIGraduationRate>"
        },
        {
            "name": "dropoutRates",
            "baseName": "dropoutRates",
            "type": "Array<APIDropoutRate>"
        },
        {
            "name": "chronicAbsenteeismRates",
            "baseName": "chronicAbsenteeismRates",
            "type": "Array<APIChronicAbsenteeismRate>"
        },
        {
            "name": "isWithinBoundary",
            "baseName": "isWithinBoundary",
            "type": "boolean"
        },
        {
            "name": "county",
            "baseName": "county",
            "type": "APICounty"
        },
        {
            "name": "rankHistory",
            "baseName": "rankHistory",
            "type": "Array<APILEARankHistory>"
        },
        {
            "name": "districtYearlyDetails",
            "baseName": "districtYearlyDetails",
            "type": "Array<APILEAYearlyDetail>"
        },
        {
            "name": "testScores",
            "baseName": "testScores",
            "type": "Array<APITestScoreWrapper>"
        }    ];

    static getAttributeTypeMap() {
        return APIDistrictFull21.attributeTypeMap;
    }
}

