/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIDropoutRate {
    /**
    * School year using spring-year convention (e.g. 2025 = the 2024-2025 school year)
    */
    'year'?: number;
    /**
    * Dropout Rate at the School Level (Pro or Enterprise level only)
    */
    'schoolDropoutRate'?: number;
    /**
    * Dropout Rate at the District Level (Pro or Enterprise level only)
    */
    'districtDropoutRate'?: number;
    /**
    * Dropout Rate at the State Level (Pro or Enterprise level only)
    */
    'stateDropoutRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "schoolDropoutRate",
            "baseName": "schoolDropoutRate",
            "type": "number"
        },
        {
            "name": "districtDropoutRate",
            "baseName": "districtDropoutRate",
            "type": "number"
        },
        {
            "name": "stateDropoutRate",
            "baseName": "stateDropoutRate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIDropoutRate.attributeTypeMap;
    }
}

