/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* District Summary
*/
export class APIDistrictSum {
    /**
    * The 7 digit SchoolDigger District id number
    */
    'districtID'?: string;
    'districtName'?: string;
    /**
    * The URL to see the district details on SchoolDigger
    */
    'url'?: string;
    /**
    * The URL to see the district in the SchoolDigger ranking list
    */
    'rankURL'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtID",
            "baseName": "districtID",
            "type": "string"
        },
        {
            "name": "districtName",
            "baseName": "districtName",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "rankURL",
            "baseName": "rankURL",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APIDistrictSum.attributeTypeMap;
    }
}

