/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APIDistrictSummary21 } from './aPIDistrictSummary21';

export class APIDistrictList21 {
    'districtList'?: Array<APIDistrictSummary21>;
    /**
    * The total count of districts that match your query
    */
    'numberOfDistricts'?: number;
    /**
    * The total count of pages in your query list based on given per_page value
    */
    'numberOfPages'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtList",
            "baseName": "districtList",
            "type": "Array<APIDistrictSummary21>"
        },
        {
            "name": "numberOfDistricts",
            "baseName": "numberOfDistricts",
            "type": "number"
        },
        {
            "name": "numberOfPages",
            "baseName": "numberOfPages",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIDistrictList21.attributeTypeMap;
    }
}

