/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIDistrictAC {
    /**
    * SchoolDigger District ID Number (7 digits). Use /districts/{districtID} to retrieve the full district record
    */
    'districtid'?: string;
    /**
    * District name
    */
    'districtName'?: string;
    /**
    * District location city
    */
    'city'?: string;
    /**
    * District location state
    */
    'state'?: string;
    /**
    * District location zip code
    */
    'zip'?: string;
    /**
    * The low grade served by this district (PK = Prekindergarten, K = Kindergarten)
    */
    'lowGrade'?: string;
    /**
    * The high grade served by this district
    */
    'highGrade'?: string;
    /**
    * District location latitude
    */
    'latitude'?: number;
    /**
    * District location longitude
    */
    'longitude'?: number;
    /**
    * States whether there is an attendance boundary available for this District
    */
    'hasBoundary'?: boolean;
    /**
    * Statewide rank of this district
    */
    'rank'?: number;
    /**
    * Count of districts ranked at this state/level
    */
    'rankOf'?: number;
    /**
    * The number of stars SchoolDigger awarded in the ranking of the district (0-5, 5 is best)
    */
    'rankStars'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtid",
            "baseName": "districtid",
            "type": "string"
        },
        {
            "name": "districtName",
            "baseName": "districtName",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "zip",
            "baseName": "zip",
            "type": "string"
        },
        {
            "name": "lowGrade",
            "baseName": "lowGrade",
            "type": "string"
        },
        {
            "name": "highGrade",
            "baseName": "highGrade",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "number"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "number"
        },
        {
            "name": "hasBoundary",
            "baseName": "hasBoundary",
            "type": "boolean"
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number"
        },
        {
            "name": "rankOf",
            "baseName": "rankOf",
            "type": "number"
        },
        {
            "name": "rankStars",
            "baseName": "rankStars",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIDistrictAC.attributeTypeMap;
    }
}

