/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APICounty } from './aPICounty';
import { APILEARankHistory } from './aPILEARankHistory';
import { APILEAYearlyDetail } from './aPILEAYearlyDetail';
import { APILocation } from './aPILocation';

export class APIDistrictSummary21 {
    /**
    * SchoolDigger District ID Number (7 digits). Use /districts/{districtID} to retrieve the entire district record
    */
    'districtID'?: string;
    /**
    * District name
    */
    'districtName'?: string;
    /**
    * District phone number
    */
    'phone'?: string;
    /**
    * SchoolDigger URL for this district
    */
    'url'?: string;
    'address'?: APILocation;
    /**
    * Indicates whether this school\'s boundary includes the specified location from nearLatitude/nearLongitude or boundaryAddress (Enterprise API level)
    */
    'locationIsWithinBoundary'?: boolean;
    /**
    * Indicates that an attendance boundary is available for this district. (To retrieve, look up district with /districts/{id})
    */
    'hasBoundary'?: boolean;
    /**
    * Distance in miles from the nearLatitude/nearLongitude coordinates (only populated when proximity search parameters are provided)
    */
    'distance'?: number;
    /**
    * Indicates whether this district\'s boundary includes the specified location from nearLatitude/nearLongitude
    */
    'isWithinBoundary'?: boolean;
    'county'?: APICounty;
    /**
    * The low grade served by this district (PK = Prekindergarten, K = Kindergarten)
    */
    'lowGrade'?: string;
    /**
    * The high grade served by this district
    */
    'highGrade'?: string;
    /**
    * Count of schools in the district
    */
    'numberTotalSchools'?: number;
    /**
    * Count of schools designated as primary schools
    */
    'numberPrimarySchools'?: number;
    /**
    * Count of schools designated as middle schools
    */
    'numberMiddleSchools'?: number;
    /**
    * Count of schools designated as high schools
    */
    'numberHighSchools'?: number;
    /**
    * Count of schools designated as other/alternative schools
    */
    'numberAlternativeSchools'?: number;
    /**
    * SchoolDigger yearly rank history of the district
    */
    'rankHistory'?: Array<APILEARankHistory>;
    /**
    * District yearly metrics
    */
    'districtYearlyDetails'?: Array<APILEAYearlyDetail>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "districtID",
            "baseName": "districtID",
            "type": "string"
        },
        {
            "name": "districtName",
            "baseName": "districtName",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "APILocation"
        },
        {
            "name": "locationIsWithinBoundary",
            "baseName": "locationIsWithinBoundary",
            "type": "boolean"
        },
        {
            "name": "hasBoundary",
            "baseName": "hasBoundary",
            "type": "boolean"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "isWithinBoundary",
            "baseName": "isWithinBoundary",
            "type": "boolean"
        },
        {
            "name": "county",
            "baseName": "county",
            "type": "APICounty"
        },
        {
            "name": "lowGrade",
            "baseName": "lowGrade",
            "type": "string"
        },
        {
            "name": "highGrade",
            "baseName": "highGrade",
            "type": "string"
        },
        {
            "name": "numberTotalSchools",
            "baseName": "numberTotalSchools",
            "type": "number"
        },
        {
            "name": "numberPrimarySchools",
            "baseName": "numberPrimarySchools",
            "type": "number"
        },
        {
            "name": "numberMiddleSchools",
            "baseName": "numberMiddleSchools",
            "type": "number"
        },
        {
            "name": "numberHighSchools",
            "baseName": "numberHighSchools",
            "type": "number"
        },
        {
            "name": "numberAlternativeSchools",
            "baseName": "numberAlternativeSchools",
            "type": "number"
        },
        {
            "name": "rankHistory",
            "baseName": "rankHistory",
            "type": "Array<APILEARankHistory>"
        },
        {
            "name": "districtYearlyDetails",
            "baseName": "districtYearlyDetails",
            "type": "Array<APILEAYearlyDetail>"
        }    ];

    static getAttributeTypeMap() {
        return APIDistrictSummary21.attributeTypeMap;
    }
}

