/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APILatLong } from './aPILatLong';

export class APILocation {
    'latLong'?: APILatLong;
    /**
    * Street address of the school or district (e.g. \'18500 37th Avenue N.E.\')
    */
    'street'?: string;
    /**
    * City where the school or district is located
    */
    'city'?: string;
    /**
    * Two-letter state abbreviation (e.g. \'WA\')
    */
    'state'?: string;
    /**
    * Full state name (WA = Washington)
    */
    'stateFull'?: string;
    /**
    * 5-digit ZIP code
    */
    'zip'?: string;
    /**
    * ZIP+4 suffix (4 digits, may be empty)
    */
    'zip4'?: string;
    /**
    * SchoolDigger URL for schools in this city
    */
    'cityURL'?: string;
    /**
    * SchoolDigger URL for schools in this zip code
    */
    'zipURL'?: string;
    /**
    * HTML formatted address
    */
    'html'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "latLong",
            "baseName": "latLong",
            "type": "APILatLong"
        },
        {
            "name": "street",
            "baseName": "street",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "stateFull",
            "baseName": "stateFull",
            "type": "string"
        },
        {
            "name": "zip",
            "baseName": "zip",
            "type": "string"
        },
        {
            "name": "zip4",
            "baseName": "zip4",
            "type": "string"
        },
        {
            "name": "cityURL",
            "baseName": "cityURL",
            "type": "string"
        },
        {
            "name": "zipURL",
            "baseName": "zipURL",
            "type": "string"
        },
        {
            "name": "html",
            "baseName": "html",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APILocation.attributeTypeMap;
    }
}

