/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APILEAYearlyDetail {
    /**
    * School year (2018 = 2017-18)
    */
    'year'?: number;
    /**
    * Number of students enrolled in the district
    */
    'numberOfStudents'?: number;
    /**
    * The number of students having a written Individualized Education Program (IEP) under the Individuals With Disabilities Education Act (IDEA)
    */
    'numberOfSpecialEdStudents'?: number;
    /**
    * The number of English language learner (ELL) students served in appropriate programs
    */
    'numberOfEnglishLanguageLearnerStudents'?: number;
    /**
    * Number of full-time equivalent teachers employed by the district
    */
    'numberOfTeachers'?: number;
    /**
    * Number of full-time equivalent pre-kindergarten teachers employed by the district
    */
    'numberOfTeachersPK'?: number;
    /**
    * Number of full-time equivalent kindergarten teachers employed by the district
    */
    'numberOfTeachersK'?: number;
    /**
    * Number of full-time equivalent elementary teachers employed by the district
    */
    'numberOfTeachersElementary'?: number;
    /**
    * Number of full-time equivalent secondary teachers employed by the district
    */
    'numberOfTeachersSecondary'?: number;
    /**
    * Number of full-time equivalent instructional aids employed by the district
    */
    'numberOfAids'?: number;
    /**
    * Number of full-time equivalent instructional coordinators/supervisors employed by the district
    */
    'numberOfCoordsSupervisors'?: number;
    /**
    * Number of full-time equivalent elementary guidance counselors employed by the district
    */
    'numberOfGuidanceElem'?: number;
    /**
    * Number of full-time equivalent secondary guidance counselors employed by the district
    */
    'numberOfGuidanceSecondary'?: number;
    /**
    * Total number of full-time equivalent guidance counselors employed by the district
    */
    'numberOfGuidanceTotal'?: number;
    /**
    * Number of full-time equivalent librarians/media specialists employed by the district
    */
    'numberOfLibrarians'?: number;
    /**
    * Number of full-time equivalent librarians/media support staff employed by the district
    */
    'numberOfLibraryStaff'?: number;
    /**
    * Number of full-time equivalent LEA administrators employed by the district (LEA)
    */
    'numberOfLEAAdministrators'?: number;
    /**
    * Number of full-time equivalent LEA administrative support staff employed by the district (LEA)
    */
    'numberOfLEASupportStaff'?: number;
    /**
    * Number of full-time equivalent school administrators employed by the district (LEA)
    */
    'numberOfSchoolAdministrators'?: number;
    /**
    * Number of full-time equivalent school administrative support staff employed by the district (LEA)
    */
    'numberOfSchoolAdminSupportStaff'?: number;
    /**
    * Number of full-time equivalent student support services staff employed by the district (LEA)
    */
    'numberOfStudentSupportStaff'?: number;
    /**
    * Number of full-time equivalent all other support staff employed by the district (LEA)
    */
    'numberOfOtherSupportStaff'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "numberOfStudents",
            "baseName": "numberOfStudents",
            "type": "number"
        },
        {
            "name": "numberOfSpecialEdStudents",
            "baseName": "numberOfSpecialEdStudents",
            "type": "number"
        },
        {
            "name": "numberOfEnglishLanguageLearnerStudents",
            "baseName": "numberOfEnglishLanguageLearnerStudents",
            "type": "number"
        },
        {
            "name": "numberOfTeachers",
            "baseName": "numberOfTeachers",
            "type": "number"
        },
        {
            "name": "numberOfTeachersPK",
            "baseName": "numberOfTeachersPK",
            "type": "number"
        },
        {
            "name": "numberOfTeachersK",
            "baseName": "numberOfTeachersK",
            "type": "number"
        },
        {
            "name": "numberOfTeachersElementary",
            "baseName": "numberOfTeachersElementary",
            "type": "number"
        },
        {
            "name": "numberOfTeachersSecondary",
            "baseName": "numberOfTeachersSecondary",
            "type": "number"
        },
        {
            "name": "numberOfAids",
            "baseName": "numberOfAids",
            "type": "number"
        },
        {
            "name": "numberOfCoordsSupervisors",
            "baseName": "numberOfCoordsSupervisors",
            "type": "number"
        },
        {
            "name": "numberOfGuidanceElem",
            "baseName": "numberOfGuidanceElem",
            "type": "number"
        },
        {
            "name": "numberOfGuidanceSecondary",
            "baseName": "numberOfGuidanceSecondary",
            "type": "number"
        },
        {
            "name": "numberOfGuidanceTotal",
            "baseName": "numberOfGuidanceTotal",
            "type": "number"
        },
        {
            "name": "numberOfLibrarians",
            "baseName": "numberOfLibrarians",
            "type": "number"
        },
        {
            "name": "numberOfLibraryStaff",
            "baseName": "numberOfLibraryStaff",
            "type": "number"
        },
        {
            "name": "numberOfLEAAdministrators",
            "baseName": "numberOfLEAAdministrators",
            "type": "number"
        },
        {
            "name": "numberOfLEASupportStaff",
            "baseName": "numberOfLEASupportStaff",
            "type": "number"
        },
        {
            "name": "numberOfSchoolAdministrators",
            "baseName": "numberOfSchoolAdministrators",
            "type": "number"
        },
        {
            "name": "numberOfSchoolAdminSupportStaff",
            "baseName": "numberOfSchoolAdminSupportStaff",
            "type": "number"
        },
        {
            "name": "numberOfStudentSupportStaff",
            "baseName": "numberOfStudentSupportStaff",
            "type": "number"
        },
        {
            "name": "numberOfOtherSupportStaff",
            "baseName": "numberOfOtherSupportStaff",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APILEAYearlyDetail.attributeTypeMap;
    }
}

