/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APILEARankHistory {
    /**
    * School year (2017 - 2016-17)
    */
    'year'?: number;
    /**
    * Statewide rank of this district
    */
    'rank'?: number;
    /**
    * Count of district ranked in this state
    */
    'rankOf'?: number;
    /**
    * The number of stars SchoolDigger awarded in the ranking of the district (0-5, 5 is best)
    */
    'rankStars'?: number;
    /**
    * Percentile of this district\'s rank (e.g. this district performed better than (x)% of this state\'s districts)
    */
    'rankStatewidePercentage'?: number;
    /**
    * The rank score calculated by SchoolDigger (see https://www.schooldigger.com/aboutranking.aspx)
    */
    'rankScore'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number"
        },
        {
            "name": "rankOf",
            "baseName": "rankOf",
            "type": "number"
        },
        {
            "name": "rankStars",
            "baseName": "rankStars",
            "type": "number"
        },
        {
            "name": "rankStatewidePercentage",
            "baseName": "rankStatewidePercentage",
            "type": "number"
        },
        {
            "name": "rankScore",
            "baseName": "rankScore",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APILEARankHistory.attributeTypeMap;
    }
}

