/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIPolyline {
    /**
    * Google Maps encoded polyline string for rendering the boundary on a map. Compatible with google.maps.geometry.encoding.decodePath() and similar libraries. IMPORTANT: Backslashes are JSON-escaped (appear as \\\\). Unescape to single backslashes before decoding.
    */
    'polylineOverlayEncodedPoints'?: string;
    /**
    * Number of encoded points in polyline
    */
    'numberEncodedPoints'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "polylineOverlayEncodedPoints",
            "baseName": "polylineOverlayEncodedPoints",
            "type": "string"
        },
        {
            "name": "numberEncodedPoints",
            "baseName": "numberEncodedPoints",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIPolyline.attributeTypeMap;
    }
}

