/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIRankHistory {
    /**
    * School year (2017 - 2016-17)
    */
    'year'?: number;
    /**
    * Statewide rank of this School
    */
    'rank'?: number;
    /**
    * Count of schools ranked at this state/level
    */
    'rankOf'?: number;
    /**
    * The number of stars SchoolDigger awarded in the ranking of the school (0-5, 5 is best)
    */
    'rankStars'?: number;
    /**
    * The level for which this school is ranked (Elementary, Middle, High)
    */
    'rankLevel'?: string;
    /**
    * Percentile of this school\'s rank (e.g. this school performed better than (x)% of this state\'s elementary schools)
    */
    'rankStatewidePercentage'?: number;
    /**
    * The Average Standard score calculated by SchoolDigger (see: https://www.schooldigger.com/aboutrankingmethodology.aspx)
    */
    'averageStandardScore'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number"
        },
        {
            "name": "rankOf",
            "baseName": "rankOf",
            "type": "number"
        },
        {
            "name": "rankStars",
            "baseName": "rankStars",
            "type": "number"
        },
        {
            "name": "rankLevel",
            "baseName": "rankLevel",
            "type": "string"
        },
        {
            "name": "rankStatewidePercentage",
            "baseName": "rankStatewidePercentage",
            "type": "number"
        },
        {
            "name": "averageStandardScore",
            "baseName": "averageStandardScore",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIRankHistory.attributeTypeMap;
    }
}

