/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APISchoolFinance {
    /**
    * Fiscal school year using spring-year convention (e.g. 2024 = the 2023-2024 fiscal year).
    */
    'year'?: number;
    /**
    * Total spending per student from all funds (Pro or Enterprise level only)
    */
    'spendingPerStudent'?: number;
    /**
    * Spending per student for Personnel at the Federal Level (Enterprise level only)
    */
    'spendingFederalPersonnel'?: number;
    /**
    * Spending per student for Non-personnel at the Federal Level (Enterprise level only)
    */
    'spendingFederalNonPersonnel'?: number;
    /**
    * Spending per student for Personnel at the State and Local Level (Enterprise level only)
    */
    'spendingStateLocalPersonnel'?: number;
    /**
    * Spending per student for Non-personnel at the State and Local Level (Enterprise level only)
    */
    'spendingStateLocalNonPersonnel'?: number;
    /**
    * Spending per student at the Federal Level (Enterprise level only)
    */
    'spendingPerStudentFederal'?: number;
    /**
    * Spending per student at the State and Local Level (Enterprise level only)
    */
    'spendingPerStudentStateLocal'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "spendingPerStudent",
            "baseName": "spendingPerStudent",
            "type": "number"
        },
        {
            "name": "spendingFederalPersonnel",
            "baseName": "spendingFederalPersonnel",
            "type": "number"
        },
        {
            "name": "spendingFederalNonPersonnel",
            "baseName": "spendingFederalNonPersonnel",
            "type": "number"
        },
        {
            "name": "spendingStateLocalPersonnel",
            "baseName": "spendingStateLocalPersonnel",
            "type": "number"
        },
        {
            "name": "spendingStateLocalNonPersonnel",
            "baseName": "spendingStateLocalNonPersonnel",
            "type": "number"
        },
        {
            "name": "spendingPerStudentFederal",
            "baseName": "spendingPerStudentFederal",
            "type": "number"
        },
        {
            "name": "spendingPerStudentStateLocal",
            "baseName": "spendingPerStudentStateLocal",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolFinance.attributeTypeMap;
    }
}

