/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APISchoolSummary22 } from './aPISchoolSummary22';

export class APISchoolList22 {
    /**
    * The total count of schools that match your query
    */
    'numberOfSchools'?: number;
    /**
    * The total count of pages in your query list based on given per_page value
    */
    'numberOfPages'?: number;
    'schoolList'?: Array<APISchoolSummary22>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfSchools",
            "baseName": "numberOfSchools",
            "type": "number"
        },
        {
            "name": "numberOfPages",
            "baseName": "numberOfPages",
            "type": "number"
        },
        {
            "name": "schoolList",
            "baseName": "schoolList",
            "type": "Array<APISchoolSummary22>"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolList22.attributeTypeMap;
    }
}

