/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APICounty } from './aPICounty';
import { APIDistrictSum } from './aPIDistrictSum';
import { APILocation } from './aPILocation';
import { APIRankHistory } from './aPIRankHistory';
import { APIYearlyDemographics } from './aPIYearlyDemographics';

/**
* APISchool2Summary: A summary of a school record. For the full school record, call /schools/{id}
*/
export class APISchoolSummary22 {
    /**
    * SchoolDigger School ID Number (12 digits)
    */
    'schoolid'?: string;
    /**
    * School name
    */
    'schoolName'?: string;
    /**
    * School phone number
    */
    'phone'?: string;
    /**
    * SchoolDigger URL for this school
    */
    'url'?: string;
    /**
    * SchoolDigger URL for comparing this school to nearby schools
    */
    'urlCompare'?: string;
    'address'?: APILocation;
    /**
    * Distance from nearLatitude/nearLongitude, boundaryLatitude/boundaryLongitude, or boundaryAddress (if supplied)
    */
    'distance'?: number;
    /**
    * NCES Locale of school (https://nces.ed.gov/ccd/rural_locales.asp)
    */
    'locale'?: string;
    /**
    * The low grade served by this school (PK = Prekindergarten, K = Kindergarten)
    */
    'lowGrade'?: string;
    /**
    * The high grade served by this school
    */
    'highGrade'?: string;
    /**
    * The level of school (Elementary, Middle, High, Private, Alternative)
    */
    'schoolLevel'?: string;
    /**
    * Indicates if school is a charter school (Yes/No/n-a)
    */
    'isCharterSchool'?: string;
    /**
    * Indicates if school is a magnet school (Yes/No/n-a)
    */
    'isMagnetSchool'?: string;
    /**
    * Indicates if school is a virtual school (Yes/No/n-a)
    */
    'isVirtualSchool'?: string;
    /**
    * Indicates if school is a Title I school (Yes/No/n-a)
    */
    'isTitleISchool'?: string;
    /**
    * Indicates if a school-wide Title I school (Yes/No/n-a)
    */
    'isTitleISchoolwideSchool'?: string;
    'district'?: APIDistrictSum;
    'county'?: APICounty;
    /**
    * SchoolDigger yearly rank history of the school. To retrieve all years, call /schools/{id}.
    */
    'rankHistory'?: Array<APIRankHistory>;
    /**
    * Returns the movement of rank for this school between current and previous year
    */
    'rankMovement'?: number;
    /**
    * School Yearly metrics. To retrieve all years, call /schools/{id}.
    */
    'schoolYearlyDetails'?: Array<APIYearlyDemographics>;
    /**
    * Indicates if school is a private school (Yes/No)
    */
    'isPrivate'?: boolean;
    /**
    * Days in the school year (private schools only)
    */
    'privateDays'?: number;
    /**
    * Hours in the school day (private schools only)
    */
    'privateHours'?: number;
    /**
    * Indicates if the school has a library (private schools only)
    */
    'privateHasLibrary'?: boolean;
    /**
    * Coed/Boys/Girls (private schools only)
    */
    'privateCoed'?: string;
    /**
    * Affiliation of the school (private schools only)
    */
    'privateOrientation'?: string;
    /**
    * The NCES ID of the school (private schools only)
    */
    'ncesPrivateSchoolID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schoolid",
            "baseName": "schoolid",
            "type": "string"
        },
        {
            "name": "schoolName",
            "baseName": "schoolName",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "urlCompare",
            "baseName": "urlCompare",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "APILocation"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "lowGrade",
            "baseName": "lowGrade",
            "type": "string"
        },
        {
            "name": "highGrade",
            "baseName": "highGrade",
            "type": "string"
        },
        {
            "name": "schoolLevel",
            "baseName": "schoolLevel",
            "type": "string"
        },
        {
            "name": "isCharterSchool",
            "baseName": "isCharterSchool",
            "type": "string"
        },
        {
            "name": "isMagnetSchool",
            "baseName": "isMagnetSchool",
            "type": "string"
        },
        {
            "name": "isVirtualSchool",
            "baseName": "isVirtualSchool",
            "type": "string"
        },
        {
            "name": "isTitleISchool",
            "baseName": "isTitleISchool",
            "type": "string"
        },
        {
            "name": "isTitleISchoolwideSchool",
            "baseName": "isTitleISchoolwideSchool",
            "type": "string"
        },
        {
            "name": "district",
            "baseName": "district",
            "type": "APIDistrictSum"
        },
        {
            "name": "county",
            "baseName": "county",
            "type": "APICounty"
        },
        {
            "name": "rankHistory",
            "baseName": "rankHistory",
            "type": "Array<APIRankHistory>"
        },
        {
            "name": "rankMovement",
            "baseName": "rankMovement",
            "type": "number"
        },
        {
            "name": "schoolYearlyDetails",
            "baseName": "schoolYearlyDetails",
            "type": "Array<APIYearlyDemographics>"
        },
        {
            "name": "isPrivate",
            "baseName": "isPrivate",
            "type": "boolean"
        },
        {
            "name": "privateDays",
            "baseName": "privateDays",
            "type": "number"
        },
        {
            "name": "privateHours",
            "baseName": "privateHours",
            "type": "number"
        },
        {
            "name": "privateHasLibrary",
            "baseName": "privateHasLibrary",
            "type": "boolean"
        },
        {
            "name": "privateCoed",
            "baseName": "privateCoed",
            "type": "string"
        },
        {
            "name": "privateOrientation",
            "baseName": "privateOrientation",
            "type": "string"
        },
        {
            "name": "ncesPrivateSchoolID",
            "baseName": "ncesPrivateSchoolID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolSummary22.attributeTypeMap;
    }
}

