/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APISchoolSummary21 } from './aPISchoolSummary21';

export class APISchoolListRank21 {
    /**
    * Year this ranking list represents (2018 = 2017-18)
    */
    'rankYear'?: number;
    /**
    * Year rankings returned for comparison (2018 = 2017-18)
    */
    'rankYearCompare'?: number;
    /**
    * The years for which SchoolDigger rankings are available for this state and level
    */
    'rankYearsAvailable'?: Array<number>;
    /**
    * The total count of schools in this ranking list
    */
    'numberOfSchools'?: number;
    /**
    * The total count of pages this ranking list based on given per_page value
    */
    'numberOfPages'?: number;
    /**
    * The schools in the ranking list
    */
    'schoolList'?: Array<APISchoolSummary21>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rankYear",
            "baseName": "rankYear",
            "type": "number"
        },
        {
            "name": "rankYearCompare",
            "baseName": "rankYearCompare",
            "type": "number"
        },
        {
            "name": "rankYearsAvailable",
            "baseName": "rankYearsAvailable",
            "type": "Array<number>"
        },
        {
            "name": "numberOfSchools",
            "baseName": "numberOfSchools",
            "type": "number"
        },
        {
            "name": "numberOfPages",
            "baseName": "numberOfPages",
            "type": "number"
        },
        {
            "name": "schoolList",
            "baseName": "schoolList",
            "type": "Array<APISchoolSummary21>"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolListRank21.attributeTypeMap;
    }
}

