/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APIChronicAbsenteeismRate } from './aPIChronicAbsenteeismRate';
import { APICounty } from './aPICounty';
import { APIDistrictSum } from './aPIDistrictSum';
import { APIDropoutRate } from './aPIDropoutRate';
import { APIGraduationRate } from './aPIGraduationRate';
import { APILocation } from './aPILocation';
import { APIRankHistory } from './aPIRankHistory';
import { APISchoolFinance } from './aPISchoolFinance';
import { APISchoolReview } from './aPISchoolReview';
import { APITestScoreWrapper } from './aPITestScoreWrapper';
import { APIYearlyDemographics } from './aPIYearlyDemographics';

export class APISchoolFull22 {
    /**
    * SchoolDigger School ID Number (12 digits)
    */
    'schoolid'?: string;
    /**
    * School name
    */
    'schoolName'?: string;
    /**
    * School phone number
    */
    'phone'?: string;
    /**
    * URL of the school\'s own public website (may be null if not available). This is NOT the SchoolDigger page — see urlSchoolDigger for that.
    */
    'url'?: string;
    /**
    * SchoolDigger URL for this school
    */
    'urlSchoolDigger'?: string;
    /**
    * SchoolDigger URL for comparing this school to nearby schools
    */
    'urlCompareSchoolDigger'?: string;
    'address'?: APILocation;
    /**
    * NCES urban-centric locale classification (e.g. \'City: Large\', \'Suburb: Midsize\', \'Rural: Fringe\'). Categories: City (Large/Midsize/Small), Suburb (Large/Midsize/Small), Town (Fringe/Distant/Remote), Rural (Fringe/Distant/Remote). See https://nces.ed.gov/ccd/rural_locales.asp
    */
    'locale'?: string;
    /**
    * The low grade served by this school (PK = Prekindergarten, K = Kindergarten)
    */
    'lowGrade'?: string;
    /**
    * The high grade served by this school
    */
    'highGrade'?: string;
    /**
    * The level of school (Elementary, Middle, High, Private, Alternative)
    */
    'schoolLevel'?: string;
    /**
    * Indicates if school is a charter school (Yes/No/n-a)
    */
    'isCharterSchool'?: string;
    /**
    * Indicates if school is a magnet school (Yes/No/n-a)
    */
    'isMagnetSchool'?: string;
    /**
    * Indicates if school is a virtual school (Yes/No/n-a)
    */
    'isVirtualSchool'?: string;
    /**
    * Indicates if school is a Title I school (Yes/No/n-a)
    */
    'isTitleISchool'?: string;
    /**
    * Indicates if a school-wide Title I school (Yes/No/n-a)
    */
    'isTitleISchoolwideSchool'?: string;
    /**
    * Indicates if school is a private school (Yes/No)
    */
    'isPrivate'?: boolean;
    /**
    * Days in the school year (private schools only)
    */
    'privateDays'?: number;
    /**
    * Hours in the school day (private schools only)
    */
    'privateHours'?: number;
    /**
    * Indicates if the school has a library (private schools only)
    */
    'privateHasLibrary'?: boolean;
    /**
    * Coed/Boys/Girls (private schools only)
    */
    'privateCoed'?: string;
    /**
    * Affiliation of the school (private schools only)
    */
    'privateOrientation'?: string;
    /**
    * The NCES ID of the school (private schools only)
    */
    'ncesPrivateSchoolID'?: string;
    'district'?: APIDistrictSum;
    'county'?: APICounty;
    /**
    * User-submitted reviews from SchoolDigger.com visitors. Each review includes a star rating (1-5), comment text (HTML encoded), date, and reviewer type (parent, student, teacher, principal, citizen). Reviews are unmoderated user content.
    */
    'reviews'?: Array<APISchoolReview>;
    /**
    * Yearly per-student spending data. Array is sorted most recent year first. spendingPerStudent is available at Pro level; detailed federal/state/local and personnel/non-personnel breakdowns require Enterprise level.
    */
    'finance'?: Array<APISchoolFinance>;
    /**
    * 4-year adjusted cohort graduation rates at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
    */
    'graduationRates'?: Array<APIGraduationRate>;
    /**
    * Annual dropout rates at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
    */
    'dropoutRates'?: Array<APIDropoutRate>;
    /**
    * Chronic absenteeism rates (students missing 15+ days) at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first. Data availability varies by state.
    */
    'chronicAbsenteeismRates'?: Array<APIChronicAbsenteeismRate>;
    /**
    * SchoolDigger yearly rank history for this school, sorted most recent year first. Schools are ranked within their state and level (Elementary, Middle, or High). Includes all available years — the full record returns more years than the summary in search results.
    */
    'rankHistory'?: Array<APIRankHistory>;
    /**
    * Returns the movement of rank for this school between current and previous year
    */
    'rankMovement'?: number;
    /**
    * Standardized test score results with school, district, and state comparisons. Each entry represents one test/subject/grade/year combination. Includes percent meeting standard and optional tier breakdowns (Enterprise level). Tests are state-specific (e.g. SBA, WCAS in WA; CAASPP in CA). Requires Pro or Enterprise API subscription.
    */
    'testScores'?: Array<APITestScoreWrapper>;
    /**
    * Yearly enrollment, demographics, and staffing for this school. Array is sorted most recent year first and includes all available years (back to 1988 for some schools). The full record returns more years than the summary in search results.
    */
    'schoolYearlyDetails'?: Array<APIYearlyDemographics>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schoolid",
            "baseName": "schoolid",
            "type": "string"
        },
        {
            "name": "schoolName",
            "baseName": "schoolName",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "urlSchoolDigger",
            "baseName": "urlSchoolDigger",
            "type": "string"
        },
        {
            "name": "urlCompareSchoolDigger",
            "baseName": "urlCompareSchoolDigger",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "APILocation"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "lowGrade",
            "baseName": "lowGrade",
            "type": "string"
        },
        {
            "name": "highGrade",
            "baseName": "highGrade",
            "type": "string"
        },
        {
            "name": "schoolLevel",
            "baseName": "schoolLevel",
            "type": "string"
        },
        {
            "name": "isCharterSchool",
            "baseName": "isCharterSchool",
            "type": "string"
        },
        {
            "name": "isMagnetSchool",
            "baseName": "isMagnetSchool",
            "type": "string"
        },
        {
            "name": "isVirtualSchool",
            "baseName": "isVirtualSchool",
            "type": "string"
        },
        {
            "name": "isTitleISchool",
            "baseName": "isTitleISchool",
            "type": "string"
        },
        {
            "name": "isTitleISchoolwideSchool",
            "baseName": "isTitleISchoolwideSchool",
            "type": "string"
        },
        {
            "name": "isPrivate",
            "baseName": "isPrivate",
            "type": "boolean"
        },
        {
            "name": "privateDays",
            "baseName": "privateDays",
            "type": "number"
        },
        {
            "name": "privateHours",
            "baseName": "privateHours",
            "type": "number"
        },
        {
            "name": "privateHasLibrary",
            "baseName": "privateHasLibrary",
            "type": "boolean"
        },
        {
            "name": "privateCoed",
            "baseName": "privateCoed",
            "type": "string"
        },
        {
            "name": "privateOrientation",
            "baseName": "privateOrientation",
            "type": "string"
        },
        {
            "name": "ncesPrivateSchoolID",
            "baseName": "ncesPrivateSchoolID",
            "type": "string"
        },
        {
            "name": "district",
            "baseName": "district",
            "type": "APIDistrictSum"
        },
        {
            "name": "county",
            "baseName": "county",
            "type": "APICounty"
        },
        {
            "name": "reviews",
            "baseName": "reviews",
            "type": "Array<APISchoolReview>"
        },
        {
            "name": "finance",
            "baseName": "finance",
            "type": "Array<APISchoolFinance>"
        },
        {
            "name": "graduationRates",
            "baseName": "graduationRates",
            "type": "Array<APIGraduationRate>"
        },
        {
            "name": "dropoutRates",
            "baseName": "dropoutRates",
            "type": "Array<APIDropoutRate>"
        },
        {
            "name": "chronicAbsenteeismRates",
            "baseName": "chronicAbsenteeismRates",
            "type": "Array<APIChronicAbsenteeismRate>"
        },
        {
            "name": "rankHistory",
            "baseName": "rankHistory",
            "type": "Array<APIRankHistory>"
        },
        {
            "name": "rankMovement",
            "baseName": "rankMovement",
            "type": "number"
        },
        {
            "name": "testScores",
            "baseName": "testScores",
            "type": "Array<APITestScoreWrapper>"
        },
        {
            "name": "schoolYearlyDetails",
            "baseName": "schoolYearlyDetails",
            "type": "Array<APIYearlyDemographics>"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolFull22.attributeTypeMap;
    }
}

