/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APISchoolAC23 {
    /**
    * SchoolDigger School ID Number (12 digits). Use /schools/{schoolID} to retrieve the full school record
    */
    'schoolid'?: string;
    /**
    * School name
    */
    'schoolName'?: string;
    /**
    * School location city
    */
    'city'?: string;
    /**
    * School location state
    */
    'state'?: string;
    /**
    * School location zip code (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'zip'?: string;
    /**
    * The level of school (Elementary, Middle, High, Private, Alternative)
    */
    'schoolLevel'?: string;
    /**
    * The low grade served by this school (PK = Prekindergarten, K = Kindergarten)  (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'lowGrade'?: string;
    /**
    * The high grade served by this school  (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'highGrade'?: string;
    /**
    * School location latitude (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'latitude'?: number;
    /**
    * School location longitude (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'longitude'?: number;
    /**
    * Statewide rank of this School  (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'rank'?: number;
    /**
    * Count of schools ranked at this state/level (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'rankOf'?: number;
    /**
    * The number of stars SchoolDigger awarded in the ranking of the school (0-5, 5 is best) (Pro, Enterprise, and Autocomplete Pro levels only)
    */
    'rankStars'?: number;
    /**
    * The NCES ID of the school (private schools only)
    */
    'ncesPrivateSchoolID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schoolid",
            "baseName": "schoolid",
            "type": "string"
        },
        {
            "name": "schoolName",
            "baseName": "schoolName",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "zip",
            "baseName": "zip",
            "type": "string"
        },
        {
            "name": "schoolLevel",
            "baseName": "schoolLevel",
            "type": "string"
        },
        {
            "name": "lowGrade",
            "baseName": "lowGrade",
            "type": "string"
        },
        {
            "name": "highGrade",
            "baseName": "highGrade",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "number"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "number"
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number"
        },
        {
            "name": "rankOf",
            "baseName": "rankOf",
            "type": "number"
        },
        {
            "name": "rankStars",
            "baseName": "rankStars",
            "type": "number"
        },
        {
            "name": "ncesPrivateSchoolID",
            "baseName": "ncesPrivateSchoolID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolAC23.attributeTypeMap;
    }
}

