/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APISchoolReview {
    /**
    * The date the review was submitted, formatted as M/D/YYYY (e.g. \'1/24/2009\'). Note: single-digit months and days are not zero-padded.
    */
    'submitDate'?: string;
    /**
    * Number of stars - 1 (poor) to 5 (excellent)
    */
    'numberOfStars'?: number;
    /**
    * Free-text comment left by the reviewer. Content is HTML encoded (special characters escaped). May be empty string if reviewer only left a star rating.
    */
    'comment'?: string;
    /**
    * Reviewer type (parent, student, teacher, principal, citizen)
    */
    'submittedBy'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "submitDate",
            "baseName": "submitDate",
            "type": "string"
        },
        {
            "name": "numberOfStars",
            "baseName": "numberOfStars",
            "type": "number"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "submittedBy",
            "baseName": "submittedBy",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APISchoolReview.attributeTypeMap;
    }
}

