/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APITestScore {
    /**
    * Count of students eligible to take test
    */
    'studentsEligible'?: number;
    /**
    * Count of students tested
    */
    'studentsTested'?: number;
    /**
    * Mean scale score
    */
    'meanScaledScore'?: number;
    /**
    * Percent of students meeting state standard
    */
    'percentMetStandard'?: number;
    /**
    * Count of students meeting state standard
    */
    'numberMetStandard'?: number;
    /**
    * Count of students performing at tier 1 (Enterprise API level only)
    */
    'numTier1'?: number;
    /**
    * Count of students performing at tier 2 (Enterprise API level only)
    */
    'numTier2'?: number;
    /**
    * Count of students performing at tier 3 (Enterprise API level only)
    */
    'numTier3'?: number;
    /**
    * Count of students performing at tier 4 (Enterprise API level only)
    */
    'numTier4'?: number;
    /**
    * Count of students performing at tier 5 (Enterprise API level only)
    */
    'numTier5'?: number;
    /**
    * Percent of students performing at tier 1 (Enterprise API level only)
    */
    'percentTier1'?: number;
    /**
    * Percent of students performing at tier 2 (Enterprise API level only)
    */
    'percentTier2'?: number;
    /**
    * Percent of students performing at tier 3 (Enterprise API level only)
    */
    'percentTier3'?: number;
    /**
    * Percent of students performing at tier 4 (Enterprise API level only)
    */
    'percentTier4'?: number;
    /**
    * Percent of students performing at tier 5 (Enterprise API level only)
    */
    'percentTier5'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "studentsEligible",
            "baseName": "studentsEligible",
            "type": "number"
        },
        {
            "name": "studentsTested",
            "baseName": "studentsTested",
            "type": "number"
        },
        {
            "name": "meanScaledScore",
            "baseName": "meanScaledScore",
            "type": "number"
        },
        {
            "name": "percentMetStandard",
            "baseName": "percentMetStandard",
            "type": "number"
        },
        {
            "name": "numberMetStandard",
            "baseName": "numberMetStandard",
            "type": "number"
        },
        {
            "name": "numTier1",
            "baseName": "numTier1",
            "type": "number"
        },
        {
            "name": "numTier2",
            "baseName": "numTier2",
            "type": "number"
        },
        {
            "name": "numTier3",
            "baseName": "numTier3",
            "type": "number"
        },
        {
            "name": "numTier4",
            "baseName": "numTier4",
            "type": "number"
        },
        {
            "name": "numTier5",
            "baseName": "numTier5",
            "type": "number"
        },
        {
            "name": "percentTier1",
            "baseName": "percentTier1",
            "type": "number"
        },
        {
            "name": "percentTier2",
            "baseName": "percentTier2",
            "type": "number"
        },
        {
            "name": "percentTier3",
            "baseName": "percentTier3",
            "type": "number"
        },
        {
            "name": "percentTier4",
            "baseName": "percentTier4",
            "type": "number"
        },
        {
            "name": "percentTier5",
            "baseName": "percentTier5",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APITestScore.attributeTypeMap;
    }
}

