/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APITestScore } from './aPITestScore';

export class APITestScoreWrapper {
    /**
    * The name of the state-administered test
    */
    'test'?: string;
    /**
    * Test subject
    */
    'subject'?: string;
    /**
    * Year test was administered (2018 = 2017-18)
    */
    'year'?: number;
    /**
    * Grade level for which this test score applies (e.g. \'3\', \'5\', \'8\', \'10\', \'HS\')
    */
    'grade'?: string;
    'schoolTestScore'?: APITestScore;
    'districtTestScore'?: APITestScore;
    'stateTestScore'?: APITestScore;
    /**
    * Label for the lowest performance tier on this test (e.g. \'Below Basic\', \'Level 1\'). Tier labels are state-specific. Enterprise API level only.
    */
    'tier1'?: string;
    /**
    * Label for the second performance tier (e.g. \'Basic\', \'Level 2\'). Enterprise API level only.
    */
    'tier2'?: string;
    /**
    * Label for the third performance tier (e.g. \'Proficient\', \'Level 3\'). Enterprise API level only.
    */
    'tier3'?: string;
    /**
    * Label for the fourth performance tier (e.g. \'Advanced\', \'Level 4\'). Enterprise API level only.
    */
    'tier4'?: string;
    /**
    * Label for the fifth performance tier, if applicable (e.g. \'No Score\'). Not all states use 5 tiers. Enterprise API level only.
    */
    'tier5'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "test",
            "baseName": "test",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "grade",
            "baseName": "grade",
            "type": "string"
        },
        {
            "name": "schoolTestScore",
            "baseName": "schoolTestScore",
            "type": "APITestScore"
        },
        {
            "name": "districtTestScore",
            "baseName": "districtTestScore",
            "type": "APITestScore"
        },
        {
            "name": "stateTestScore",
            "baseName": "stateTestScore",
            "type": "APITestScore"
        },
        {
            "name": "tier1",
            "baseName": "tier1",
            "type": "string"
        },
        {
            "name": "tier2",
            "baseName": "tier2",
            "type": "string"
        },
        {
            "name": "tier3",
            "baseName": "tier3",
            "type": "string"
        },
        {
            "name": "tier4",
            "baseName": "tier4",
            "type": "string"
        },
        {
            "name": "tier5",
            "baseName": "tier5",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return APITestScoreWrapper.attributeTypeMap;
    }
}

