/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class APIYearlyDemographics {
    /**
    * School year (2018 = 2017-18)
    */
    'year'?: number;
    /**
    * Count of students attending the school
    */
    'numberOfStudents'?: number;
    /**
    * Percent of students receiving a free or discounted lunch in the National School Lunch Program
    */
    'percentFreeDiscLunch'?: number;
    /**
    * Percentage of students who are Black or African American (NCES definition: a person having origins in any of the black racial groups of Africa)
    */
    'percentofAfricanAmericanStudents'?: number;
    /**
    * Percentage of students who are Asian (NCES definition: a person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent)
    */
    'percentofAsianStudents'?: number;
    /**
    * Percentage of students who are Hispanic or Latino (NCES definition: a person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin, regardless of race)
    */
    'percentofHispanicStudents'?: number;
    /**
    * Percentage of students who are American Indian or Alaska Native (NCES definition: a person having origins in any of the original peoples of North and South America who maintains tribal affiliation or community attachment)
    */
    'percentofIndianStudents'?: number;
    /**
    * Percentage of students who are Native Hawaiian or Other Pacific Islander (NCES definition: a person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands)
    */
    'percentofPacificIslanderStudents'?: number;
    /**
    * Percentage of students who are White (NCES definition: a person having origins in any of the original peoples of Europe, the Middle East, or North Africa)
    */
    'percentofWhiteStudents'?: number;
    /**
    * Percentage of students reporting two or more races (not Hispanic/Latino)
    */
    'percentofTwoOrMoreRaceStudents'?: number;
    /**
    * Percentage of students whose race/ethnicity was not specified or reported
    */
    'percentofUnspecifiedRaceStudents'?: number;
    /**
    * Number of full-time equivalent teachers employed at the school
    */
    'teachersFulltime'?: number;
    /**
    * Number of students / number of full-time equivalent teachers
    */
    'pupilTeacherRatio'?: number;
    /**
    * NCES definition: A person having origins in any of the black racial groups of Africa.  (https://nces.ed.gov/statprog/2002/std1_5.asp)
    */
    'numberofAfricanAmericanStudents'?: number;
    /**
    * NCES definition: A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent, including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam.  (https://nces.ed.gov/statprog/2002/std1_5.asp)
    */
    'numberofAsianStudents'?: number;
    /**
    * NCES definition: A person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin, regardless of race. (https://nces.ed.gov/statprog/2002/std1_5.asp)
    */
    'numberofHispanicStudents'?: number;
    /**
    * Count of American Indian or Alaska Native students (NCES definition: a person having origins in any of the original peoples of North and South America who maintains tribal affiliation or community attachment)
    */
    'numberofIndianStudents'?: number;
    /**
    * NCES definition: A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands. (https://nces.ed.gov/statprog/2002/std1_5.asp)
    */
    'numberofPacificIslanderStudents'?: number;
    /**
    * NCES definition: A person having origins in any of the original peoples of Europe, the Middle East, or North Africa. (https://nces.ed.gov/statprog/2002/std1_5.asp)
    */
    'numberofWhiteStudents'?: number;
    /**
    * NCES definition: Includes any combination of two or more races and not Hispanic/Latino ethnicity. (https://nces.ed.gov/statprog/2002/std1_5.asp)
    */
    'numberofTwoOrMoreRaceStudents'?: number;
    /**
    * Count of students whose race/ethnicity was not specified or reported
    */
    'numberofUnspecifiedRaceStudents'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "numberOfStudents",
            "baseName": "numberOfStudents",
            "type": "number"
        },
        {
            "name": "percentFreeDiscLunch",
            "baseName": "percentFreeDiscLunch",
            "type": "number"
        },
        {
            "name": "percentofAfricanAmericanStudents",
            "baseName": "percentofAfricanAmericanStudents",
            "type": "number"
        },
        {
            "name": "percentofAsianStudents",
            "baseName": "percentofAsianStudents",
            "type": "number"
        },
        {
            "name": "percentofHispanicStudents",
            "baseName": "percentofHispanicStudents",
            "type": "number"
        },
        {
            "name": "percentofIndianStudents",
            "baseName": "percentofIndianStudents",
            "type": "number"
        },
        {
            "name": "percentofPacificIslanderStudents",
            "baseName": "percentofPacificIslanderStudents",
            "type": "number"
        },
        {
            "name": "percentofWhiteStudents",
            "baseName": "percentofWhiteStudents",
            "type": "number"
        },
        {
            "name": "percentofTwoOrMoreRaceStudents",
            "baseName": "percentofTwoOrMoreRaceStudents",
            "type": "number"
        },
        {
            "name": "percentofUnspecifiedRaceStudents",
            "baseName": "percentofUnspecifiedRaceStudents",
            "type": "number"
        },
        {
            "name": "teachersFulltime",
            "baseName": "teachersFulltime",
            "type": "number"
        },
        {
            "name": "pupilTeacherRatio",
            "baseName": "pupilTeacherRatio",
            "type": "number"
        },
        {
            "name": "numberofAfricanAmericanStudents",
            "baseName": "numberofAfricanAmericanStudents",
            "type": "number"
        },
        {
            "name": "numberofAsianStudents",
            "baseName": "numberofAsianStudents",
            "type": "number"
        },
        {
            "name": "numberofHispanicStudents",
            "baseName": "numberofHispanicStudents",
            "type": "number"
        },
        {
            "name": "numberofIndianStudents",
            "baseName": "numberofIndianStudents",
            "type": "number"
        },
        {
            "name": "numberofPacificIslanderStudents",
            "baseName": "numberofPacificIslanderStudents",
            "type": "number"
        },
        {
            "name": "numberofWhiteStudents",
            "baseName": "numberofWhiteStudents",
            "type": "number"
        },
        {
            "name": "numberofTwoOrMoreRaceStudents",
            "baseName": "numberofTwoOrMoreRaceStudents",
            "type": "number"
        },
        {
            "name": "numberofUnspecifiedRaceStudents",
            "baseName": "numberofUnspecifiedRaceStudents",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APIYearlyDemographics.attributeTypeMap;
    }
}

