/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIAutocompleteDistrictResult,
  APIAutocompleteSchoolResult23,
} from '../models/index';
import {
    APIAutocompleteDistrictResultFromJSON,
    APIAutocompleteDistrictResultToJSON,
    APIAutocompleteSchoolResult23FromJSON,
    APIAutocompleteSchoolResult23ToJSON,
} from '../models/index';

export interface AutocompleteDistrictsRequest {
    q?: string;
    st?: string;
    boxLatitudeNW?: number;
    boxLongitudeNW?: number;
    boxLatitudeSE?: number;
    boxLongitudeSE?: number;
    returnCount?: number;
}

export interface AutocompleteSchoolsRequest {
    q?: string;
    qSearchCityStateName?: boolean;
    st?: string;
    level?: string;
    districtID?: string;
    boxLatitudeNW?: number;
    boxLongitudeNW?: number;
    boxLatitudeSE?: number;
    boxLongitudeSE?: number;
    returnCount?: number;
}

/**
 * 
 */
export class AutocompleteApi extends runtime.BaseAPI {

    /**
     * Creates request options for autocompleteDistricts without sending the request
     */
    async autocompleteDistrictsRequestOpts(requestParameters: AutocompleteDistrictsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['st'] != null) {
            queryParameters['st'] = requestParameters['st'];
        }

        if (requestParameters['boxLatitudeNW'] != null) {
            queryParameters['boxLatitudeNW'] = requestParameters['boxLatitudeNW'];
        }

        if (requestParameters['boxLongitudeNW'] != null) {
            queryParameters['boxLongitudeNW'] = requestParameters['boxLongitudeNW'];
        }

        if (requestParameters['boxLatitudeSE'] != null) {
            queryParameters['boxLatitudeSE'] = requestParameters['boxLatitudeSE'];
        }

        if (requestParameters['boxLongitudeSE'] != null) {
            queryParameters['boxLongitudeSE'] = requestParameters['boxLongitudeSE'];
        }

        if (requestParameters['returnCount'] != null) {
            queryParameters['returnCount'] = requestParameters['returnCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/autocomplete/districts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Returns a simple and quick list of districts for use in a client-typed autocomplete
     */
    async autocompleteDistrictsRaw(requestParameters: AutocompleteDistrictsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIAutocompleteDistrictResult>> {
        const requestOptions = await this.autocompleteDistrictsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIAutocompleteDistrictResultFromJSON(jsonValue));
    }

    /**
     * 
     * Returns a simple and quick list of districts for use in a client-typed autocomplete
     */
    async autocompleteDistricts(requestParameters: AutocompleteDistrictsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIAutocompleteDistrictResult> {
        const response = await this.autocompleteDistrictsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for autocompleteSchools without sending the request
     */
    async autocompleteSchoolsRequestOpts(requestParameters: AutocompleteSchoolsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['qSearchCityStateName'] != null) {
            queryParameters['qSearchCityStateName'] = requestParameters['qSearchCityStateName'];
        }

        if (requestParameters['st'] != null) {
            queryParameters['st'] = requestParameters['st'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['districtID'] != null) {
            queryParameters['districtID'] = requestParameters['districtID'];
        }

        if (requestParameters['boxLatitudeNW'] != null) {
            queryParameters['boxLatitudeNW'] = requestParameters['boxLatitudeNW'];
        }

        if (requestParameters['boxLongitudeNW'] != null) {
            queryParameters['boxLongitudeNW'] = requestParameters['boxLongitudeNW'];
        }

        if (requestParameters['boxLatitudeSE'] != null) {
            queryParameters['boxLatitudeSE'] = requestParameters['boxLatitudeSE'];
        }

        if (requestParameters['boxLongitudeSE'] != null) {
            queryParameters['boxLongitudeSE'] = requestParameters['boxLongitudeSE'];
        }

        if (requestParameters['returnCount'] != null) {
            queryParameters['returnCount'] = requestParameters['returnCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/autocomplete/schools`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Returns a simple and quick list of schools for use in a client-typed autocomplete
     */
    async autocompleteSchoolsRaw(requestParameters: AutocompleteSchoolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIAutocompleteSchoolResult23>> {
        const requestOptions = await this.autocompleteSchoolsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIAutocompleteSchoolResult23FromJSON(jsonValue));
    }

    /**
     * 
     * Returns a simple and quick list of schools for use in a client-typed autocomplete
     */
    async autocompleteSchools(requestParameters: AutocompleteSchoolsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIAutocompleteSchoolResult23> {
        const response = await this.autocompleteSchoolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
