/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIDistrictFull21,
  APIDistrictList21,
} from '../models/index';
import {
    APIDistrictFull21FromJSON,
    APIDistrictFull21ToJSON,
    APIDistrictList21FromJSON,
    APIDistrictList21ToJSON,
} from '../models/index';

export interface GetDistrictRequest {
    id: string;
}

export interface SearchDistrictsRequest {
    st: string;
    q?: string;
    city?: string;
    zip?: string;
    nearLatitude?: number;
    nearLongitude?: number;
    boundaryAddress?: string;
    distanceMiles?: number;
    isInBoundaryOnly?: boolean;
    boxLatitudeNW?: number;
    boxLongitudeNW?: number;
    boxLatitudeSE?: number;
    boxLongitudeSE?: number;
    page?: number;
    perPage?: number;
    sortBy?: string;
    includeUnrankedDistrictsInRankSort?: boolean;
}

/**
 * 
 */
export class DistrictsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDistrict without sending the request
     */
    async getDistrictRequestOpts(requestParameters: GetDistrictRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDistrict().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/districts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a single district record from the SchoolDigger database
     * Returns a detailed record for one district
     */
    async getDistrictRaw(requestParameters: GetDistrictRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIDistrictFull21>> {
        const requestOptions = await this.getDistrictRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIDistrictFull21FromJSON(jsonValue));
    }

    /**
     * Retrieve a single district record from the SchoolDigger database
     * Returns a detailed record for one district
     */
    async getDistrict(requestParameters: GetDistrictRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIDistrictFull21> {
        const response = await this.getDistrictRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchDistricts without sending the request
     */
    async searchDistrictsRequestOpts(requestParameters: SearchDistrictsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['st'] == null) {
            throw new runtime.RequiredError(
                'st',
                'Required parameter "st" was null or undefined when calling searchDistricts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['st'] != null) {
            queryParameters['st'] = requestParameters['st'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['zip'] != null) {
            queryParameters['zip'] = requestParameters['zip'];
        }

        if (requestParameters['nearLatitude'] != null) {
            queryParameters['nearLatitude'] = requestParameters['nearLatitude'];
        }

        if (requestParameters['nearLongitude'] != null) {
            queryParameters['nearLongitude'] = requestParameters['nearLongitude'];
        }

        if (requestParameters['boundaryAddress'] != null) {
            queryParameters['boundaryAddress'] = requestParameters['boundaryAddress'];
        }

        if (requestParameters['distanceMiles'] != null) {
            queryParameters['distanceMiles'] = requestParameters['distanceMiles'];
        }

        if (requestParameters['isInBoundaryOnly'] != null) {
            queryParameters['isInBoundaryOnly'] = requestParameters['isInBoundaryOnly'];
        }

        if (requestParameters['boxLatitudeNW'] != null) {
            queryParameters['boxLatitudeNW'] = requestParameters['boxLatitudeNW'];
        }

        if (requestParameters['boxLongitudeNW'] != null) {
            queryParameters['boxLongitudeNW'] = requestParameters['boxLongitudeNW'];
        }

        if (requestParameters['boxLatitudeSE'] != null) {
            queryParameters['boxLatitudeSE'] = requestParameters['boxLatitudeSE'];
        }

        if (requestParameters['boxLongitudeSE'] != null) {
            queryParameters['boxLongitudeSE'] = requestParameters['boxLongitudeSE'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['includeUnrankedDistrictsInRankSort'] != null) {
            queryParameters['includeUnrankedDistrictsInRankSort'] = requestParameters['includeUnrankedDistrictsInRankSort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/districts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search the SchoolDigger database for districts. You may use any combination of criteria as query parameters.
     * Returns a list of districts
     */
    async searchDistrictsRaw(requestParameters: SearchDistrictsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIDistrictList21>> {
        const requestOptions = await this.searchDistrictsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIDistrictList21FromJSON(jsonValue));
    }

    /**
     * Search the SchoolDigger database for districts. You may use any combination of criteria as query parameters.
     * Returns a list of districts
     */
    async searchDistricts(requestParameters: SearchDistrictsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIDistrictList21> {
        const response = await this.searchDistrictsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
