/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIDistrictListRank21,
  APISchoolListRank21,
} from '../models/index';
import {
    APIDistrictListRank21FromJSON,
    APIDistrictListRank21ToJSON,
    APISchoolListRank21FromJSON,
    APISchoolListRank21ToJSON,
} from '../models/index';

export interface GetDistrictRankingsRequest {
    st: string;
    year?: number;
    page?: number;
    perPage?: number;
}

export interface GetSchoolRankingsRequest {
    st: string;
    year?: number;
    level?: string;
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class RankingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDistrictRankings without sending the request
     */
    async getDistrictRankingsRequestOpts(requestParameters: GetDistrictRankingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['st'] == null) {
            throw new runtime.RequiredError(
                'st',
                'Required parameter "st" was null or undefined when calling getDistrictRankings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/rankings/districts/{st}`;
        urlPath = urlPath.replace(`{${"st"}}`, encodeURIComponent(String(requestParameters['st'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a SchoolDigger district ranking list
     */
    async getDistrictRankingsRaw(requestParameters: GetDistrictRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIDistrictListRank21>> {
        const requestOptions = await this.getDistrictRankingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIDistrictListRank21FromJSON(jsonValue));
    }

    /**
     * Returns a SchoolDigger district ranking list
     */
    async getDistrictRankings(requestParameters: GetDistrictRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIDistrictListRank21> {
        const response = await this.getDistrictRankingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSchoolRankings without sending the request
     */
    async getSchoolRankingsRequestOpts(requestParameters: GetSchoolRankingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['st'] == null) {
            throw new runtime.RequiredError(
                'st',
                'Required parameter "st" was null or undefined when calling getSchoolRankings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/rankings/schools/{st}`;
        urlPath = urlPath.replace(`{${"st"}}`, encodeURIComponent(String(requestParameters['st'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a SchoolDigger school ranking list
     */
    async getSchoolRankingsRaw(requestParameters: GetSchoolRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APISchoolListRank21>> {
        const requestOptions = await this.getSchoolRankingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APISchoolListRank21FromJSON(jsonValue));
    }

    /**
     * Returns a SchoolDigger school ranking list
     */
    async getSchoolRankings(requestParameters: GetSchoolRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APISchoolListRank21> {
        const response = await this.getSchoolRankingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
