/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APISchoolFull22,
  APISchoolList22,
} from '../models/index';
import {
    APISchoolFull22FromJSON,
    APISchoolFull22ToJSON,
    APISchoolList22FromJSON,
    APISchoolList22ToJSON,
} from '../models/index';

export interface GetSchoolRequest {
    id: string;
}

export interface SearchSchoolsRequest {
    st: string;
    q?: string;
    qSearchSchoolNameOnly?: boolean;
    districtID?: string;
    level?: string;
    city?: string;
    zip?: string;
    isMagnet?: boolean;
    isCharter?: boolean;
    isVirtual?: boolean;
    isTitleI?: boolean;
    isTitleISchoolwide?: boolean;
    nearLatitude?: number;
    nearLongitude?: number;
    nearAddress?: string;
    distanceMiles?: number;
    boxLatitudeNW?: number;
    boxLongitudeNW?: number;
    boxLatitudeSE?: number;
    boxLongitudeSE?: number;
    page?: number;
    perPage?: number;
    sortBy?: string;
    includeUnrankedSchoolsInRankSort?: boolean;
}

/**
 * 
 */
export class SchoolsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getSchool without sending the request
     */
    async getSchoolRequestOpts(requestParameters: GetSchoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSchool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/schools/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a school record from the SchoolDigger database
     * Returns a detailed record for one school
     */
    async getSchoolRaw(requestParameters: GetSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APISchoolFull22>> {
        const requestOptions = await this.getSchoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APISchoolFull22FromJSON(jsonValue));
    }

    /**
     * Retrieve a school record from the SchoolDigger database
     * Returns a detailed record for one school
     */
    async getSchool(requestParameters: GetSchoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APISchoolFull22> {
        const response = await this.getSchoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchSchools without sending the request
     */
    async searchSchoolsRequestOpts(requestParameters: SearchSchoolsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['st'] == null) {
            throw new runtime.RequiredError(
                'st',
                'Required parameter "st" was null or undefined when calling searchSchools().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['st'] != null) {
            queryParameters['st'] = requestParameters['st'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['qSearchSchoolNameOnly'] != null) {
            queryParameters['qSearchSchoolNameOnly'] = requestParameters['qSearchSchoolNameOnly'];
        }

        if (requestParameters['districtID'] != null) {
            queryParameters['districtID'] = requestParameters['districtID'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['zip'] != null) {
            queryParameters['zip'] = requestParameters['zip'];
        }

        if (requestParameters['isMagnet'] != null) {
            queryParameters['isMagnet'] = requestParameters['isMagnet'];
        }

        if (requestParameters['isCharter'] != null) {
            queryParameters['isCharter'] = requestParameters['isCharter'];
        }

        if (requestParameters['isVirtual'] != null) {
            queryParameters['isVirtual'] = requestParameters['isVirtual'];
        }

        if (requestParameters['isTitleI'] != null) {
            queryParameters['isTitleI'] = requestParameters['isTitleI'];
        }

        if (requestParameters['isTitleISchoolwide'] != null) {
            queryParameters['isTitleISchoolwide'] = requestParameters['isTitleISchoolwide'];
        }

        if (requestParameters['nearLatitude'] != null) {
            queryParameters['nearLatitude'] = requestParameters['nearLatitude'];
        }

        if (requestParameters['nearLongitude'] != null) {
            queryParameters['nearLongitude'] = requestParameters['nearLongitude'];
        }

        if (requestParameters['nearAddress'] != null) {
            queryParameters['nearAddress'] = requestParameters['nearAddress'];
        }

        if (requestParameters['distanceMiles'] != null) {
            queryParameters['distanceMiles'] = requestParameters['distanceMiles'];
        }

        if (requestParameters['boxLatitudeNW'] != null) {
            queryParameters['boxLatitudeNW'] = requestParameters['boxLatitudeNW'];
        }

        if (requestParameters['boxLongitudeNW'] != null) {
            queryParameters['boxLongitudeNW'] = requestParameters['boxLongitudeNW'];
        }

        if (requestParameters['boxLatitudeSE'] != null) {
            queryParameters['boxLatitudeSE'] = requestParameters['boxLatitudeSE'];
        }

        if (requestParameters['boxLongitudeSE'] != null) {
            queryParameters['boxLongitudeSE'] = requestParameters['boxLongitudeSE'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['includeUnrankedSchoolsInRankSort'] != null) {
            queryParameters['includeUnrankedSchoolsInRankSort'] = requestParameters['includeUnrankedSchoolsInRankSort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appID"] = await this.configuration.apiKey("appID"); // appID authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["appKey"] = await this.configuration.apiKey("appKey"); // appKey authentication
        }


        let urlPath = `/v2.3/schools`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search the SchoolDigger database for schools. You may use any combination of criteria as query parameters.
     * Returns a list of schools
     */
    async searchSchoolsRaw(requestParameters: SearchSchoolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APISchoolList22>> {
        const requestOptions = await this.searchSchoolsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APISchoolList22FromJSON(jsonValue));
    }

    /**
     * Search the SchoolDigger database for schools. You may use any combination of criteria as query parameters.
     * Returns a list of schools
     */
    async searchSchools(requestParameters: SearchSchoolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APISchoolList22> {
        const response = await this.searchSchoolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
