/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIDistrictAC } from './APIDistrictAC';
import {
    APIDistrictACFromJSON,
    APIDistrictACFromJSONTyped,
    APIDistrictACToJSON,
    APIDistrictACToJSONTyped,
} from './APIDistrictAC';

/**
 * 
 * @export
 * @interface APIAutocompleteDistrictResult
 */
export interface APIAutocompleteDistrictResult {
    /**
     * List of the districts that match the query
     * @type {Array<APIDistrictAC>}
     * @memberof APIAutocompleteDistrictResult
     */
    districtMatches?: Array<APIDistrictAC>;
}

/**
 * Check if a given object implements the APIAutocompleteDistrictResult interface.
 */
export function instanceOfAPIAutocompleteDistrictResult(value: object): value is APIAutocompleteDistrictResult {
    return true;
}

export function APIAutocompleteDistrictResultFromJSON(json: any): APIAutocompleteDistrictResult {
    return APIAutocompleteDistrictResultFromJSONTyped(json, false);
}

export function APIAutocompleteDistrictResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIAutocompleteDistrictResult {
    if (json == null) {
        return json;
    }
    return {
        
        'districtMatches': json['districtMatches'] == null ? undefined : ((json['districtMatches'] as Array<any>).map(APIDistrictACFromJSON)),
    };
}

export function APIAutocompleteDistrictResultToJSON(json: any): APIAutocompleteDistrictResult {
    return APIAutocompleteDistrictResultToJSONTyped(json, false);
}

export function APIAutocompleteDistrictResultToJSONTyped(value?: APIAutocompleteDistrictResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'districtMatches': value['districtMatches'] == null ? undefined : ((value['districtMatches'] as Array<any>).map(APIDistrictACToJSON)),
    };
}

