/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APISchoolAC23 } from './APISchoolAC23';
import {
    APISchoolAC23FromJSON,
    APISchoolAC23FromJSONTyped,
    APISchoolAC23ToJSON,
    APISchoolAC23ToJSONTyped,
} from './APISchoolAC23';

/**
 * 
 * @export
 * @interface APIAutocompleteSchoolResult23
 */
export interface APIAutocompleteSchoolResult23 {
    /**
     * List of the schools that match the query
     * @type {Array<APISchoolAC23>}
     * @memberof APIAutocompleteSchoolResult23
     */
    schoolMatches?: Array<APISchoolAC23>;
}

/**
 * Check if a given object implements the APIAutocompleteSchoolResult23 interface.
 */
export function instanceOfAPIAutocompleteSchoolResult23(value: object): value is APIAutocompleteSchoolResult23 {
    return true;
}

export function APIAutocompleteSchoolResult23FromJSON(json: any): APIAutocompleteSchoolResult23 {
    return APIAutocompleteSchoolResult23FromJSONTyped(json, false);
}

export function APIAutocompleteSchoolResult23FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIAutocompleteSchoolResult23 {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolMatches': json['schoolMatches'] == null ? undefined : ((json['schoolMatches'] as Array<any>).map(APISchoolAC23FromJSON)),
    };
}

export function APIAutocompleteSchoolResult23ToJSON(json: any): APIAutocompleteSchoolResult23 {
    return APIAutocompleteSchoolResult23ToJSONTyped(json, false);
}

export function APIAutocompleteSchoolResult23ToJSONTyped(value?: APIAutocompleteSchoolResult23 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schoolMatches': value['schoolMatches'] == null ? undefined : ((value['schoolMatches'] as Array<any>).map(APISchoolAC23ToJSON)),
    };
}

