/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIPolyline } from './APIPolyline';
import {
    APIPolylineFromJSON,
    APIPolylineFromJSONTyped,
    APIPolylineToJSON,
    APIPolylineToJSONTyped,
} from './APIPolyline';

/**
 * 
 * @export
 * @interface APIBoundary12
 */
export interface APIBoundary12 {
    /**
     * Collection of one or more Google Maps encoded polylines representing the attendance boundary. IMPORTANT: Polyline strings are JSON-encoded with escaped backslashes (double backslashes). You must unescape before passing to Google Maps decoding functions. Multiple polylines represent districts/schools with non-contiguous boundary areas.
     * @type {Array<APIPolyline>}
     * @memberof APIBoundary12
     */
    polylineCollection?: Array<APIPolyline>;
    /**
     * Boundary as a WKT (Well-Known Text) MULTIPOLYGON string with explicit latitude/longitude vertices. Can be used directly with GIS software, PostGIS, or any system that accepts WKT geometry. Format: MULTIPOLYGON (((-122.27 47.77, ...)))
     * @type {string}
     * @memberof APIBoundary12
     */
    polylines?: string;
    /**
     * States whether there is a boundary available
     * @type {boolean}
     * @memberof APIBoundary12
     */
    hasBoundary?: boolean;
}

/**
 * Check if a given object implements the APIBoundary12 interface.
 */
export function instanceOfAPIBoundary12(value: object): value is APIBoundary12 {
    return true;
}

export function APIBoundary12FromJSON(json: any): APIBoundary12 {
    return APIBoundary12FromJSONTyped(json, false);
}

export function APIBoundary12FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIBoundary12 {
    if (json == null) {
        return json;
    }
    return {
        
        'polylineCollection': json['polylineCollection'] == null ? undefined : ((json['polylineCollection'] as Array<any>).map(APIPolylineFromJSON)),
        'polylines': json['polylines'] == null ? undefined : json['polylines'],
        'hasBoundary': json['hasBoundary'] == null ? undefined : json['hasBoundary'],
    };
}

export function APIBoundary12ToJSON(json: any): APIBoundary12 {
    return APIBoundary12ToJSONTyped(json, false);
}

export function APIBoundary12ToJSONTyped(value?: APIBoundary12 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'polylineCollection': value['polylineCollection'] == null ? undefined : ((value['polylineCollection'] as Array<any>).map(APIPolylineToJSON)),
        'polylines': value['polylines'],
        'hasBoundary': value['hasBoundary'],
    };
}

