/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIChronicAbsenteeismRate
 */
export interface APIChronicAbsenteeismRate {
    /**
     * School year using spring-year convention (e.g. 2025 = the 2024-2025 school year)
     * @type {number}
     * @memberof APIChronicAbsenteeismRate
     */
    year?: number;
    /**
     * ChronicAbsenteeism Rate at the School Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIChronicAbsenteeismRate
     */
    schoolChronicAbsenteeismRate?: number;
    /**
     * ChronicAbsenteeism Rate at the District Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIChronicAbsenteeismRate
     */
    districtChronicAbsenteeismRate?: number;
    /**
     * ChronicAbsenteeism Rate at the State Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIChronicAbsenteeismRate
     */
    stateChronicAbsenteeismRate?: number;
}

/**
 * Check if a given object implements the APIChronicAbsenteeismRate interface.
 */
export function instanceOfAPIChronicAbsenteeismRate(value: object): value is APIChronicAbsenteeismRate {
    return true;
}

export function APIChronicAbsenteeismRateFromJSON(json: any): APIChronicAbsenteeismRate {
    return APIChronicAbsenteeismRateFromJSONTyped(json, false);
}

export function APIChronicAbsenteeismRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIChronicAbsenteeismRate {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'schoolChronicAbsenteeismRate': json['schoolChronicAbsenteeismRate'] == null ? undefined : json['schoolChronicAbsenteeismRate'],
        'districtChronicAbsenteeismRate': json['districtChronicAbsenteeismRate'] == null ? undefined : json['districtChronicAbsenteeismRate'],
        'stateChronicAbsenteeismRate': json['stateChronicAbsenteeismRate'] == null ? undefined : json['stateChronicAbsenteeismRate'],
    };
}

export function APIChronicAbsenteeismRateToJSON(json: any): APIChronicAbsenteeismRate {
    return APIChronicAbsenteeismRateToJSONTyped(json, false);
}

export function APIChronicAbsenteeismRateToJSONTyped(value?: APIChronicAbsenteeismRate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'schoolChronicAbsenteeismRate': value['schoolChronicAbsenteeismRate'],
        'districtChronicAbsenteeismRate': value['districtChronicAbsenteeismRate'],
        'stateChronicAbsenteeismRate': value['stateChronicAbsenteeismRate'],
    };
}

