/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APICounty
 */
export interface APICounty {
    /**
     * County in which the school or district is located
     * @type {string}
     * @memberof APICounty
     */
    countyName?: string;
    /**
     * SchoolDigger URL for all schools in this county
     * @type {string}
     * @memberof APICounty
     */
    countyURL?: string;
}

/**
 * Check if a given object implements the APICounty interface.
 */
export function instanceOfAPICounty(value: object): value is APICounty {
    return true;
}

export function APICountyFromJSON(json: any): APICounty {
    return APICountyFromJSONTyped(json, false);
}

export function APICountyFromJSONTyped(json: any, ignoreDiscriminator: boolean): APICounty {
    if (json == null) {
        return json;
    }
    return {
        
        'countyName': json['countyName'] == null ? undefined : json['countyName'],
        'countyURL': json['countyURL'] == null ? undefined : json['countyURL'],
    };
}

export function APICountyToJSON(json: any): APICounty {
    return APICountyToJSONTyped(json, false);
}

export function APICountyToJSONTyped(value?: APICounty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'countyName': value['countyName'],
        'countyURL': value['countyURL'],
    };
}

