/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIDistrictSummary21 } from './APIDistrictSummary21';
import {
    APIDistrictSummary21FromJSON,
    APIDistrictSummary21FromJSONTyped,
    APIDistrictSummary21ToJSON,
    APIDistrictSummary21ToJSONTyped,
} from './APIDistrictSummary21';

/**
 * 
 * @export
 * @interface APIDistrictListRank21
 */
export interface APIDistrictListRank21 {
    /**
     * Year this ranking list represents (2018 = 2017-18)
     * @type {number}
     * @memberof APIDistrictListRank21
     */
    rankYear?: number;
    /**
     * Year rankings returned for comparison (2018 = 2017-18)
     * @type {number}
     * @memberof APIDistrictListRank21
     */
    rankYearCompare?: number;
    /**
     * The years for which SchoolDigger district rankings are available for this state
     * @type {Array<number>}
     * @memberof APIDistrictListRank21
     */
    rankYearsAvailable?: Array<number>;
    /**
     * The total count of districts in the entire rank list
     * @type {number}
     * @memberof APIDistrictListRank21
     */
    numberOfDistricts?: number;
    /**
     * The total count of pages in your query list based on given per_page value
     * @type {number}
     * @memberof APIDistrictListRank21
     */
    numberOfPages?: number;
    /**
     * 
     * @type {Array<APIDistrictSummary21>}
     * @memberof APIDistrictListRank21
     */
    districtList?: Array<APIDistrictSummary21>;
    /**
     * 
     * @type {number}
     * @memberof APIDistrictListRank21
     */
    rankCompareYear?: number;
}

/**
 * Check if a given object implements the APIDistrictListRank21 interface.
 */
export function instanceOfAPIDistrictListRank21(value: object): value is APIDistrictListRank21 {
    return true;
}

export function APIDistrictListRank21FromJSON(json: any): APIDistrictListRank21 {
    return APIDistrictListRank21FromJSONTyped(json, false);
}

export function APIDistrictListRank21FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDistrictListRank21 {
    if (json == null) {
        return json;
    }
    return {
        
        'rankYear': json['rankYear'] == null ? undefined : json['rankYear'],
        'rankYearCompare': json['rankYearCompare'] == null ? undefined : json['rankYearCompare'],
        'rankYearsAvailable': json['rankYearsAvailable'] == null ? undefined : json['rankYearsAvailable'],
        'numberOfDistricts': json['numberOfDistricts'] == null ? undefined : json['numberOfDistricts'],
        'numberOfPages': json['numberOfPages'] == null ? undefined : json['numberOfPages'],
        'districtList': json['districtList'] == null ? undefined : ((json['districtList'] as Array<any>).map(APIDistrictSummary21FromJSON)),
        'rankCompareYear': json['rankCompareYear'] == null ? undefined : json['rankCompareYear'],
    };
}

export function APIDistrictListRank21ToJSON(json: any): APIDistrictListRank21 {
    return APIDistrictListRank21ToJSONTyped(json, false);
}

export function APIDistrictListRank21ToJSONTyped(value?: APIDistrictListRank21 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rankYear': value['rankYear'],
        'rankYearCompare': value['rankYearCompare'],
        'rankYearsAvailable': value['rankYearsAvailable'],
        'numberOfDistricts': value['numberOfDistricts'],
        'numberOfPages': value['numberOfPages'],
        'districtList': value['districtList'] == null ? undefined : ((value['districtList'] as Array<any>).map(APIDistrictSummary21ToJSON)),
        'rankCompareYear': value['rankCompareYear'],
    };
}

