/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIDistrictSummary21 } from './APIDistrictSummary21';
import {
    APIDistrictSummary21FromJSON,
    APIDistrictSummary21FromJSONTyped,
    APIDistrictSummary21ToJSON,
    APIDistrictSummary21ToJSONTyped,
} from './APIDistrictSummary21';

/**
 * 
 * @export
 * @interface APIDistrictList21
 */
export interface APIDistrictList21 {
    /**
     * 
     * @type {Array<APIDistrictSummary21>}
     * @memberof APIDistrictList21
     */
    districtList?: Array<APIDistrictSummary21>;
    /**
     * The total count of districts that match your query
     * @type {number}
     * @memberof APIDistrictList21
     */
    numberOfDistricts?: number;
    /**
     * The total count of pages in your query list based on given per_page value
     * @type {number}
     * @memberof APIDistrictList21
     */
    numberOfPages?: number;
}

/**
 * Check if a given object implements the APIDistrictList21 interface.
 */
export function instanceOfAPIDistrictList21(value: object): value is APIDistrictList21 {
    return true;
}

export function APIDistrictList21FromJSON(json: any): APIDistrictList21 {
    return APIDistrictList21FromJSONTyped(json, false);
}

export function APIDistrictList21FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDistrictList21 {
    if (json == null) {
        return json;
    }
    return {
        
        'districtList': json['districtList'] == null ? undefined : ((json['districtList'] as Array<any>).map(APIDistrictSummary21FromJSON)),
        'numberOfDistricts': json['numberOfDistricts'] == null ? undefined : json['numberOfDistricts'],
        'numberOfPages': json['numberOfPages'] == null ? undefined : json['numberOfPages'],
    };
}

export function APIDistrictList21ToJSON(json: any): APIDistrictList21 {
    return APIDistrictList21ToJSONTyped(json, false);
}

export function APIDistrictList21ToJSONTyped(value?: APIDistrictList21 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'districtList': value['districtList'] == null ? undefined : ((value['districtList'] as Array<any>).map(APIDistrictSummary21ToJSON)),
        'numberOfDistricts': value['numberOfDistricts'],
        'numberOfPages': value['numberOfPages'],
    };
}

