/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIDistrictAC
 */
export interface APIDistrictAC {
    /**
     * SchoolDigger District ID Number (7 digits). Use /districts/{districtID} to retrieve the full district record
     * @type {string}
     * @memberof APIDistrictAC
     */
    districtid?: string;
    /**
     * District name
     * @type {string}
     * @memberof APIDistrictAC
     */
    districtName?: string;
    /**
     * District location city
     * @type {string}
     * @memberof APIDistrictAC
     */
    city?: string;
    /**
     * District location state
     * @type {string}
     * @memberof APIDistrictAC
     */
    state?: string;
    /**
     * District location zip code
     * @type {string}
     * @memberof APIDistrictAC
     */
    zip?: string;
    /**
     * The low grade served by this district (PK = Prekindergarten, K = Kindergarten)
     * @type {string}
     * @memberof APIDistrictAC
     */
    lowGrade?: string;
    /**
     * The high grade served by this district
     * @type {string}
     * @memberof APIDistrictAC
     */
    highGrade?: string;
    /**
     * District location latitude
     * @type {number}
     * @memberof APIDistrictAC
     */
    latitude?: number;
    /**
     * District location longitude
     * @type {number}
     * @memberof APIDistrictAC
     */
    longitude?: number;
    /**
     * States whether there is an attendance boundary available for this District
     * @type {boolean}
     * @memberof APIDistrictAC
     */
    hasBoundary?: boolean;
    /**
     * Statewide rank of this district
     * @type {number}
     * @memberof APIDistrictAC
     */
    rank?: number;
    /**
     * Count of districts ranked at this state/level
     * @type {number}
     * @memberof APIDistrictAC
     */
    rankOf?: number;
    /**
     * The number of stars SchoolDigger awarded in the ranking of the district (0-5, 5 is best)
     * @type {number}
     * @memberof APIDistrictAC
     */
    rankStars?: number;
}

/**
 * Check if a given object implements the APIDistrictAC interface.
 */
export function instanceOfAPIDistrictAC(value: object): value is APIDistrictAC {
    return true;
}

export function APIDistrictACFromJSON(json: any): APIDistrictAC {
    return APIDistrictACFromJSONTyped(json, false);
}

export function APIDistrictACFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDistrictAC {
    if (json == null) {
        return json;
    }
    return {
        
        'districtid': json['districtid'] == null ? undefined : json['districtid'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zip': json['zip'] == null ? undefined : json['zip'],
        'lowGrade': json['lowGrade'] == null ? undefined : json['lowGrade'],
        'highGrade': json['highGrade'] == null ? undefined : json['highGrade'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'hasBoundary': json['hasBoundary'] == null ? undefined : json['hasBoundary'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'rankOf': json['rankOf'] == null ? undefined : json['rankOf'],
        'rankStars': json['rankStars'] == null ? undefined : json['rankStars'],
    };
}

export function APIDistrictACToJSON(json: any): APIDistrictAC {
    return APIDistrictACToJSONTyped(json, false);
}

export function APIDistrictACToJSONTyped(value?: APIDistrictAC | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'districtid': value['districtid'],
        'districtName': value['districtName'],
        'city': value['city'],
        'state': value['state'],
        'zip': value['zip'],
        'lowGrade': value['lowGrade'],
        'highGrade': value['highGrade'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'hasBoundary': value['hasBoundary'],
        'rank': value['rank'],
        'rankOf': value['rankOf'],
        'rankStars': value['rankStars'],
    };
}

