/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * District Summary
 * @export
 * @interface APIDistrictSum
 */
export interface APIDistrictSum {
    /**
     * The 7 digit SchoolDigger District id number
     * @type {string}
     * @memberof APIDistrictSum
     */
    districtID?: string;
    /**
     * 
     * @type {string}
     * @memberof APIDistrictSum
     */
    districtName?: string;
    /**
     * The URL to see the district details on SchoolDigger
     * @type {string}
     * @memberof APIDistrictSum
     */
    url?: string;
    /**
     * The URL to see the district in the SchoolDigger ranking list
     * @type {string}
     * @memberof APIDistrictSum
     */
    rankURL?: string;
}

/**
 * Check if a given object implements the APIDistrictSum interface.
 */
export function instanceOfAPIDistrictSum(value: object): value is APIDistrictSum {
    return true;
}

export function APIDistrictSumFromJSON(json: any): APIDistrictSum {
    return APIDistrictSumFromJSONTyped(json, false);
}

export function APIDistrictSumFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDistrictSum {
    if (json == null) {
        return json;
    }
    return {
        
        'districtID': json['districtID'] == null ? undefined : json['districtID'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'url': json['url'] == null ? undefined : json['url'],
        'rankURL': json['rankURL'] == null ? undefined : json['rankURL'],
    };
}

export function APIDistrictSumToJSON(json: any): APIDistrictSum {
    return APIDistrictSumToJSONTyped(json, false);
}

export function APIDistrictSumToJSONTyped(value?: APIDistrictSum | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'districtID': value['districtID'],
        'districtName': value['districtName'],
        'url': value['url'],
        'rankURL': value['rankURL'],
    };
}

