/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v3.0
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APISchoolFinance } from './APISchoolFinance';
import {
    APISchoolFinanceFromJSON,
    APISchoolFinanceFromJSONTyped,
    APISchoolFinanceToJSON,
    APISchoolFinanceToJSONTyped,
} from './APISchoolFinance';
import type { APILEARankHistory } from './APILEARankHistory';
import {
    APILEARankHistoryFromJSON,
    APILEARankHistoryFromJSONTyped,
    APILEARankHistoryToJSON,
    APILEARankHistoryToJSONTyped,
} from './APILEARankHistory';
import type { APIGraduationRate } from './APIGraduationRate';
import {
    APIGraduationRateFromJSON,
    APIGraduationRateFromJSONTyped,
    APIGraduationRateToJSON,
    APIGraduationRateToJSONTyped,
} from './APIGraduationRate';
import type { APIBoundary12 } from './APIBoundary12';
import {
    APIBoundary12FromJSON,
    APIBoundary12FromJSONTyped,
    APIBoundary12ToJSON,
    APIBoundary12ToJSONTyped,
} from './APIBoundary12';
import type { APIDropoutRate } from './APIDropoutRate';
import {
    APIDropoutRateFromJSON,
    APIDropoutRateFromJSONTyped,
    APIDropoutRateToJSON,
    APIDropoutRateToJSONTyped,
} from './APIDropoutRate';
import type { APITestScoreWrapper30 } from './APITestScoreWrapper30';
import {
    APITestScoreWrapper30FromJSON,
    APITestScoreWrapper30FromJSONTyped,
    APITestScoreWrapper30ToJSON,
    APITestScoreWrapper30ToJSONTyped,
} from './APITestScoreWrapper30';
import type { APICounty } from './APICounty';
import {
    APICountyFromJSON,
    APICountyFromJSONTyped,
    APICountyToJSON,
    APICountyToJSONTyped,
} from './APICounty';
import type { APILEAYearlyDetail } from './APILEAYearlyDetail';
import {
    APILEAYearlyDetailFromJSON,
    APILEAYearlyDetailFromJSONTyped,
    APILEAYearlyDetailToJSON,
    APILEAYearlyDetailToJSONTyped,
} from './APILEAYearlyDetail';
import type { APIChronicAbsenteeismRate } from './APIChronicAbsenteeismRate';
import {
    APIChronicAbsenteeismRateFromJSON,
    APIChronicAbsenteeismRateFromJSONTyped,
    APIChronicAbsenteeismRateToJSON,
    APIChronicAbsenteeismRateToJSONTyped,
} from './APIChronicAbsenteeismRate';
import type { APILocation } from './APILocation';
import {
    APILocationFromJSON,
    APILocationFromJSONTyped,
    APILocationToJSON,
    APILocationToJSONTyped,
} from './APILocation';

/**
 * District detail record for API 3.0. Identical to 2.4 (APIDistrictFull21) except testScores, whose percent metrics
 * are a number or an APIReportedPercent object and whose rows are no longer limited to what the pre-2026 importers
 * produced (docs/suppressed-test-values-spec.md R6).
 * @export
 * @interface APIDistrictFull30
 */
export interface APIDistrictFull30 {
    /**
     * Standardized test score results with district and state comparisons. Each entry represents one test/subject/grade/year combination. District-level records do not include schoolTestScore. Percent metrics are a number when the state reported an exact value, otherwise an object describing a range, a suppressed value, a legacy stand-in or a derived value (see APIReportedPercent). Requires Pro or Enterprise API subscription.
     * @type {Array<APITestScoreWrapper30>}
     * @memberof APIDistrictFull30
     */
    testScores?: Array<APITestScoreWrapper30>;
    /**
     * SchoolDigger District ID Number (7 digits)
     * @type {string}
     * @memberof APIDistrictFull30
     */
    districtID?: string;
    /**
     * District name
     * @type {string}
     * @memberof APIDistrictFull30
     */
    districtName?: string;
    /**
     * District phone number
     * @type {string}
     * @memberof APIDistrictFull30
     */
    phone?: string;
    /**
     * SchoolDigger URL for this district
     * @type {string}
     * @memberof APIDistrictFull30
     */
    url?: string;
    /**
     * 
     * @type {APILocation}
     * @memberof APIDistrictFull30
     */
    address?: APILocation;
    /**
     * The low grade served by this district (PK = Prekindergarten, K = Kindergarten)
     * @type {string}
     * @memberof APIDistrictFull30
     */
    lowGrade?: string;
    /**
     * The high grade served by this district
     * @type {string}
     * @memberof APIDistrictFull30
     */
    highGrade?: string;
    /**
     * 
     * @type {number}
     * @memberof APIDistrictFull30
     */
    numberTotalSchools?: number;
    /**
     * 
     * @type {number}
     * @memberof APIDistrictFull30
     */
    numberPrimarySchools?: number;
    /**
     * 
     * @type {number}
     * @memberof APIDistrictFull30
     */
    numberMiddleSchools?: number;
    /**
     * 
     * @type {number}
     * @memberof APIDistrictFull30
     */
    numberHighSchools?: number;
    /**
     * 
     * @type {number}
     * @memberof APIDistrictFull30
     */
    numberAlternativeSchools?: number;
    /**
     * 
     * @type {APIBoundary12}
     * @memberof APIDistrictFull30
     */
    boundary?: APIBoundary12;
    /**
     * Yearly per-student spending data. Array is sorted most recent year first. spendingPerStudent is available at Pro level; detailed federal/state/local and personnel/non-personnel breakdowns require Enterprise level.
     * @type {Array<APISchoolFinance>}
     * @memberof APIDistrictFull30
     */
    finance?: Array<APISchoolFinance>;
    /**
     * 4-year adjusted cohort graduation rates at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
     * @type {Array<APIGraduationRate>}
     * @memberof APIDistrictFull30
     */
    graduationRates?: Array<APIGraduationRate>;
    /**
     * Annual dropout rates at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
     * @type {Array<APIDropoutRate>}
     * @memberof APIDistrictFull30
     */
    dropoutRates?: Array<APIDropoutRate>;
    /**
     * Chronic absenteeism rates (students missing 15+ days) at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first. Data availability varies by state.
     * @type {Array<APIChronicAbsenteeismRate>}
     * @memberof APIDistrictFull30
     */
    chronicAbsenteeismRates?: Array<APIChronicAbsenteeismRate>;
    /**
     * Indicates whether this district's boundary includes the specified location from nearLatitude/nearLongitude
     * @type {boolean}
     * @memberof APIDistrictFull30
     */
    isWithinBoundary?: boolean;
    /**
     * 
     * @type {APICounty}
     * @memberof APIDistrictFull30
     */
    county?: APICounty;
    /**
     * SchoolDigger yearly rank history for this district, sorted most recent year first. Districts are ranked statewide regardless of level.
     * @type {Array<APILEARankHistory>}
     * @memberof APIDistrictFull30
     */
    rankHistory?: Array<APILEARankHistory>;
    /**
     * Yearly enrollment and staffing details for this district. Array is sorted most recent year first. Includes detailed FTE staffing breakdowns by role (teachers by level, administrators, counselors, librarians, support staff).
     * @type {Array<APILEAYearlyDetail>}
     * @memberof APIDistrictFull30
     */
    districtYearlyDetails?: Array<APILEAYearlyDetail>;
}

/**
 * Check if a given object implements the APIDistrictFull30 interface.
 */
export function instanceOfAPIDistrictFull30(value: object): value is APIDistrictFull30 {
    return true;
}

export function APIDistrictFull30FromJSON(json: any): APIDistrictFull30 {
    return APIDistrictFull30FromJSONTyped(json, false);
}

export function APIDistrictFull30FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDistrictFull30 {
    if (json == null) {
        return json;
    }
    return {
        
        'testScores': json['testScores'] == null ? undefined : ((json['testScores'] as Array<any>).map(APITestScoreWrapper30FromJSON)),
        'districtID': json['districtID'] == null ? undefined : json['districtID'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'url': json['url'] == null ? undefined : json['url'],
        'address': json['address'] == null ? undefined : APILocationFromJSON(json['address']),
        'lowGrade': json['lowGrade'] == null ? undefined : json['lowGrade'],
        'highGrade': json['highGrade'] == null ? undefined : json['highGrade'],
        'numberTotalSchools': json['numberTotalSchools'] == null ? undefined : json['numberTotalSchools'],
        'numberPrimarySchools': json['numberPrimarySchools'] == null ? undefined : json['numberPrimarySchools'],
        'numberMiddleSchools': json['numberMiddleSchools'] == null ? undefined : json['numberMiddleSchools'],
        'numberHighSchools': json['numberHighSchools'] == null ? undefined : json['numberHighSchools'],
        'numberAlternativeSchools': json['numberAlternativeSchools'] == null ? undefined : json['numberAlternativeSchools'],
        'boundary': json['boundary'] == null ? undefined : APIBoundary12FromJSON(json['boundary']),
        'finance': json['finance'] == null ? undefined : ((json['finance'] as Array<any>).map(APISchoolFinanceFromJSON)),
        'graduationRates': json['graduationRates'] == null ? undefined : ((json['graduationRates'] as Array<any>).map(APIGraduationRateFromJSON)),
        'dropoutRates': json['dropoutRates'] == null ? undefined : ((json['dropoutRates'] as Array<any>).map(APIDropoutRateFromJSON)),
        'chronicAbsenteeismRates': json['chronicAbsenteeismRates'] == null ? undefined : ((json['chronicAbsenteeismRates'] as Array<any>).map(APIChronicAbsenteeismRateFromJSON)),
        'isWithinBoundary': json['isWithinBoundary'] == null ? undefined : json['isWithinBoundary'],
        'county': json['county'] == null ? undefined : APICountyFromJSON(json['county']),
        'rankHistory': json['rankHistory'] == null ? undefined : ((json['rankHistory'] as Array<any>).map(APILEARankHistoryFromJSON)),
        'districtYearlyDetails': json['districtYearlyDetails'] == null ? undefined : ((json['districtYearlyDetails'] as Array<any>).map(APILEAYearlyDetailFromJSON)),
    };
}

export function APIDistrictFull30ToJSON(json: any): APIDistrictFull30 {
    return APIDistrictFull30ToJSONTyped(json, false);
}

export function APIDistrictFull30ToJSONTyped(value?: APIDistrictFull30 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'testScores': value['testScores'] == null ? undefined : ((value['testScores'] as Array<any>).map(APITestScoreWrapper30ToJSON)),
        'districtID': value['districtID'],
        'districtName': value['districtName'],
        'phone': value['phone'],
        'url': value['url'],
        'address': APILocationToJSON(value['address']),
        'lowGrade': value['lowGrade'],
        'highGrade': value['highGrade'],
        'numberTotalSchools': value['numberTotalSchools'],
        'numberPrimarySchools': value['numberPrimarySchools'],
        'numberMiddleSchools': value['numberMiddleSchools'],
        'numberHighSchools': value['numberHighSchools'],
        'numberAlternativeSchools': value['numberAlternativeSchools'],
        'boundary': APIBoundary12ToJSON(value['boundary']),
        'finance': value['finance'] == null ? undefined : ((value['finance'] as Array<any>).map(APISchoolFinanceToJSON)),
        'graduationRates': value['graduationRates'] == null ? undefined : ((value['graduationRates'] as Array<any>).map(APIGraduationRateToJSON)),
        'dropoutRates': value['dropoutRates'] == null ? undefined : ((value['dropoutRates'] as Array<any>).map(APIDropoutRateToJSON)),
        'chronicAbsenteeismRates': value['chronicAbsenteeismRates'] == null ? undefined : ((value['chronicAbsenteeismRates'] as Array<any>).map(APIChronicAbsenteeismRateToJSON)),
        'isWithinBoundary': value['isWithinBoundary'],
        'county': APICountyToJSON(value['county']),
        'rankHistory': value['rankHistory'] == null ? undefined : ((value['rankHistory'] as Array<any>).map(APILEARankHistoryToJSON)),
        'districtYearlyDetails': value['districtYearlyDetails'] == null ? undefined : ((value['districtYearlyDetails'] as Array<any>).map(APILEAYearlyDetailToJSON)),
    };
}

