/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APILEARankHistory } from './APILEARankHistory';
import {
    APILEARankHistoryFromJSON,
    APILEARankHistoryFromJSONTyped,
    APILEARankHistoryToJSON,
    APILEARankHistoryToJSONTyped,
} from './APILEARankHistory';
import type { APICounty } from './APICounty';
import {
    APICountyFromJSON,
    APICountyFromJSONTyped,
    APICountyToJSON,
    APICountyToJSONTyped,
} from './APICounty';
import type { APILEAYearlyDetail } from './APILEAYearlyDetail';
import {
    APILEAYearlyDetailFromJSON,
    APILEAYearlyDetailFromJSONTyped,
    APILEAYearlyDetailToJSON,
    APILEAYearlyDetailToJSONTyped,
} from './APILEAYearlyDetail';
import type { APILocation } from './APILocation';
import {
    APILocationFromJSON,
    APILocationFromJSONTyped,
    APILocationToJSON,
    APILocationToJSONTyped,
} from './APILocation';

/**
 * 
 * @export
 * @interface APIDistrictSummary21
 */
export interface APIDistrictSummary21 {
    /**
     * SchoolDigger District ID Number (7 digits). Use /districts/{districtID} to retrieve the entire district record
     * @type {string}
     * @memberof APIDistrictSummary21
     */
    districtID?: string;
    /**
     * District name
     * @type {string}
     * @memberof APIDistrictSummary21
     */
    districtName?: string;
    /**
     * District phone number
     * @type {string}
     * @memberof APIDistrictSummary21
     */
    phone?: string;
    /**
     * SchoolDigger URL for this district
     * @type {string}
     * @memberof APIDistrictSummary21
     */
    url?: string;
    /**
     * 
     * @type {APILocation}
     * @memberof APIDistrictSummary21
     */
    address?: APILocation;
    /**
     * Indicates whether this school's boundary includes the specified location from nearLatitude/nearLongitude or boundaryAddress (Enterprise API level)
     * @type {boolean}
     * @memberof APIDistrictSummary21
     */
    locationIsWithinBoundary?: boolean;
    /**
     * Indicates that an attendance boundary is available for this district. (To retrieve, look up district with /districts/{id})
     * @type {boolean}
     * @memberof APIDistrictSummary21
     */
    hasBoundary?: boolean;
    /**
     * Distance in miles from the nearLatitude/nearLongitude coordinates (only populated when proximity search parameters are provided)
     * @type {number}
     * @memberof APIDistrictSummary21
     */
    distance?: number;
    /**
     * Indicates whether this district's boundary includes the specified location from nearLatitude/nearLongitude
     * @type {boolean}
     * @memberof APIDistrictSummary21
     */
    isWithinBoundary?: boolean;
    /**
     * 
     * @type {APICounty}
     * @memberof APIDistrictSummary21
     */
    county?: APICounty;
    /**
     * The low grade served by this district (PK = Prekindergarten, K = Kindergarten)
     * @type {string}
     * @memberof APIDistrictSummary21
     */
    lowGrade?: string;
    /**
     * The high grade served by this district
     * @type {string}
     * @memberof APIDistrictSummary21
     */
    highGrade?: string;
    /**
     * Count of schools in the district
     * @type {number}
     * @memberof APIDistrictSummary21
     */
    numberTotalSchools?: number;
    /**
     * Count of schools designated as primary schools
     * @type {number}
     * @memberof APIDistrictSummary21
     */
    numberPrimarySchools?: number;
    /**
     * Count of schools designated as middle schools
     * @type {number}
     * @memberof APIDistrictSummary21
     */
    numberMiddleSchools?: number;
    /**
     * Count of schools designated as high schools
     * @type {number}
     * @memberof APIDistrictSummary21
     */
    numberHighSchools?: number;
    /**
     * Count of schools designated as other/alternative schools
     * @type {number}
     * @memberof APIDistrictSummary21
     */
    numberAlternativeSchools?: number;
    /**
     * SchoolDigger yearly rank history of the district
     * @type {Array<APILEARankHistory>}
     * @memberof APIDistrictSummary21
     */
    rankHistory?: Array<APILEARankHistory>;
    /**
     * District yearly metrics
     * @type {Array<APILEAYearlyDetail>}
     * @memberof APIDistrictSummary21
     */
    districtYearlyDetails?: Array<APILEAYearlyDetail>;
}

/**
 * Check if a given object implements the APIDistrictSummary21 interface.
 */
export function instanceOfAPIDistrictSummary21(value: object): value is APIDistrictSummary21 {
    return true;
}

export function APIDistrictSummary21FromJSON(json: any): APIDistrictSummary21 {
    return APIDistrictSummary21FromJSONTyped(json, false);
}

export function APIDistrictSummary21FromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDistrictSummary21 {
    if (json == null) {
        return json;
    }
    return {
        
        'districtID': json['districtID'] == null ? undefined : json['districtID'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'url': json['url'] == null ? undefined : json['url'],
        'address': json['address'] == null ? undefined : APILocationFromJSON(json['address']),
        'locationIsWithinBoundary': json['locationIsWithinBoundary'] == null ? undefined : json['locationIsWithinBoundary'],
        'hasBoundary': json['hasBoundary'] == null ? undefined : json['hasBoundary'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'isWithinBoundary': json['isWithinBoundary'] == null ? undefined : json['isWithinBoundary'],
        'county': json['county'] == null ? undefined : APICountyFromJSON(json['county']),
        'lowGrade': json['lowGrade'] == null ? undefined : json['lowGrade'],
        'highGrade': json['highGrade'] == null ? undefined : json['highGrade'],
        'numberTotalSchools': json['numberTotalSchools'] == null ? undefined : json['numberTotalSchools'],
        'numberPrimarySchools': json['numberPrimarySchools'] == null ? undefined : json['numberPrimarySchools'],
        'numberMiddleSchools': json['numberMiddleSchools'] == null ? undefined : json['numberMiddleSchools'],
        'numberHighSchools': json['numberHighSchools'] == null ? undefined : json['numberHighSchools'],
        'numberAlternativeSchools': json['numberAlternativeSchools'] == null ? undefined : json['numberAlternativeSchools'],
        'rankHistory': json['rankHistory'] == null ? undefined : ((json['rankHistory'] as Array<any>).map(APILEARankHistoryFromJSON)),
        'districtYearlyDetails': json['districtYearlyDetails'] == null ? undefined : ((json['districtYearlyDetails'] as Array<any>).map(APILEAYearlyDetailFromJSON)),
    };
}

export function APIDistrictSummary21ToJSON(json: any): APIDistrictSummary21 {
    return APIDistrictSummary21ToJSONTyped(json, false);
}

export function APIDistrictSummary21ToJSONTyped(value?: APIDistrictSummary21 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'districtID': value['districtID'],
        'districtName': value['districtName'],
        'phone': value['phone'],
        'url': value['url'],
        'address': APILocationToJSON(value['address']),
        'locationIsWithinBoundary': value['locationIsWithinBoundary'],
        'hasBoundary': value['hasBoundary'],
        'distance': value['distance'],
        'isWithinBoundary': value['isWithinBoundary'],
        'county': APICountyToJSON(value['county']),
        'lowGrade': value['lowGrade'],
        'highGrade': value['highGrade'],
        'numberTotalSchools': value['numberTotalSchools'],
        'numberPrimarySchools': value['numberPrimarySchools'],
        'numberMiddleSchools': value['numberMiddleSchools'],
        'numberHighSchools': value['numberHighSchools'],
        'numberAlternativeSchools': value['numberAlternativeSchools'],
        'rankHistory': value['rankHistory'] == null ? undefined : ((value['rankHistory'] as Array<any>).map(APILEARankHistoryToJSON)),
        'districtYearlyDetails': value['districtYearlyDetails'] == null ? undefined : ((value['districtYearlyDetails'] as Array<any>).map(APILEAYearlyDetailToJSON)),
    };
}

