/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIDropoutRate
 */
export interface APIDropoutRate {
    /**
     * School year using spring-year convention (e.g. 2025 = the 2024-2025 school year)
     * @type {number}
     * @memberof APIDropoutRate
     */
    year?: number;
    /**
     * Dropout Rate at the School Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIDropoutRate
     */
    schoolDropoutRate?: number;
    /**
     * Dropout Rate at the District Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIDropoutRate
     */
    districtDropoutRate?: number;
    /**
     * Dropout Rate at the State Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIDropoutRate
     */
    stateDropoutRate?: number;
}

/**
 * Check if a given object implements the APIDropoutRate interface.
 */
export function instanceOfAPIDropoutRate(value: object): value is APIDropoutRate {
    return true;
}

export function APIDropoutRateFromJSON(json: any): APIDropoutRate {
    return APIDropoutRateFromJSONTyped(json, false);
}

export function APIDropoutRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIDropoutRate {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'schoolDropoutRate': json['schoolDropoutRate'] == null ? undefined : json['schoolDropoutRate'],
        'districtDropoutRate': json['districtDropoutRate'] == null ? undefined : json['districtDropoutRate'],
        'stateDropoutRate': json['stateDropoutRate'] == null ? undefined : json['stateDropoutRate'],
    };
}

export function APIDropoutRateToJSON(json: any): APIDropoutRate {
    return APIDropoutRateToJSONTyped(json, false);
}

export function APIDropoutRateToJSONTyped(value?: APIDropoutRate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'schoolDropoutRate': value['schoolDropoutRate'],
        'districtDropoutRate': value['districtDropoutRate'],
        'stateDropoutRate': value['stateDropoutRate'],
    };
}

