/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIGraduationRate
 */
export interface APIGraduationRate {
    /**
     * School year using spring-year convention (e.g. 2025 = the 2024-2025 school year)
     * @type {number}
     * @memberof APIGraduationRate
     */
    year?: number;
    /**
     * 4-Year Graduation Rate at the School Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIGraduationRate
     */
    schoolGraduationRate?: number;
    /**
     * 4-Year Graduation Rate at the District Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIGraduationRate
     */
    districtGraduationRate?: number;
    /**
     * 4-Year Graduation Rate at the State Level (Pro or Enterprise level only)
     * @type {number}
     * @memberof APIGraduationRate
     */
    stateGraduationRate?: number;
}

/**
 * Check if a given object implements the APIGraduationRate interface.
 */
export function instanceOfAPIGraduationRate(value: object): value is APIGraduationRate {
    return true;
}

export function APIGraduationRateFromJSON(json: any): APIGraduationRate {
    return APIGraduationRateFromJSONTyped(json, false);
}

export function APIGraduationRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIGraduationRate {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'schoolGraduationRate': json['schoolGraduationRate'] == null ? undefined : json['schoolGraduationRate'],
        'districtGraduationRate': json['districtGraduationRate'] == null ? undefined : json['districtGraduationRate'],
        'stateGraduationRate': json['stateGraduationRate'] == null ? undefined : json['stateGraduationRate'],
    };
}

export function APIGraduationRateToJSON(json: any): APIGraduationRate {
    return APIGraduationRateToJSONTyped(json, false);
}

export function APIGraduationRateToJSONTyped(value?: APIGraduationRate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'schoolGraduationRate': value['schoolGraduationRate'],
        'districtGraduationRate': value['districtGraduationRate'],
        'stateGraduationRate': value['stateGraduationRate'],
    };
}

