/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APILatLong
 */
export interface APILatLong {
    /**
     * Latitude coordinate of the school or district address (WGS84 decimal degrees)
     * @type {number}
     * @memberof APILatLong
     */
    latitude?: number;
    /**
     * Longitude coordinate of the school or district address (WGS84 decimal degrees, negative for Western Hemisphere)
     * @type {number}
     * @memberof APILatLong
     */
    longitude?: number;
}

/**
 * Check if a given object implements the APILatLong interface.
 */
export function instanceOfAPILatLong(value: object): value is APILatLong {
    return true;
}

export function APILatLongFromJSON(json: any): APILatLong {
    return APILatLongFromJSONTyped(json, false);
}

export function APILatLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): APILatLong {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function APILatLongToJSON(json: any): APILatLong {
    return APILatLongToJSONTyped(json, false);
}

export function APILatLongToJSONTyped(value?: APILatLong | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

