/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APILEAYearlyDetail
 */
export interface APILEAYearlyDetail {
    /**
     * School year (2018 = 2017-18)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    year?: number;
    /**
     * Number of students enrolled in the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfStudents?: number;
    /**
     * The number of students having a written Individualized Education Program (IEP) under the Individuals With Disabilities Education Act (IDEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfSpecialEdStudents?: number;
    /**
     * The number of English language learner (ELL) students served in appropriate programs
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfEnglishLanguageLearnerStudents?: number;
    /**
     * Number of full-time equivalent teachers employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfTeachers?: number;
    /**
     * Number of full-time equivalent pre-kindergarten teachers employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfTeachersPK?: number;
    /**
     * Number of full-time equivalent kindergarten teachers employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfTeachersK?: number;
    /**
     * Number of full-time equivalent elementary teachers employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfTeachersElementary?: number;
    /**
     * Number of full-time equivalent secondary teachers employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfTeachersSecondary?: number;
    /**
     * Number of full-time equivalent instructional aids employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfAids?: number;
    /**
     * Number of full-time equivalent instructional coordinators/supervisors employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfCoordsSupervisors?: number;
    /**
     * Number of full-time equivalent elementary guidance counselors employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfGuidanceElem?: number;
    /**
     * Number of full-time equivalent secondary guidance counselors employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfGuidanceSecondary?: number;
    /**
     * Total number of full-time equivalent guidance counselors employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfGuidanceTotal?: number;
    /**
     * Number of full-time equivalent librarians/media specialists employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfLibrarians?: number;
    /**
     * Number of full-time equivalent librarians/media support staff employed by the district
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfLibraryStaff?: number;
    /**
     * Number of full-time equivalent LEA administrators employed by the district (LEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfLEAAdministrators?: number;
    /**
     * Number of full-time equivalent LEA administrative support staff employed by the district (LEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfLEASupportStaff?: number;
    /**
     * Number of full-time equivalent school administrators employed by the district (LEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfSchoolAdministrators?: number;
    /**
     * Number of full-time equivalent school administrative support staff employed by the district (LEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfSchoolAdminSupportStaff?: number;
    /**
     * Number of full-time equivalent student support services staff employed by the district (LEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfStudentSupportStaff?: number;
    /**
     * Number of full-time equivalent all other support staff employed by the district (LEA)
     * @type {number}
     * @memberof APILEAYearlyDetail
     */
    numberOfOtherSupportStaff?: number;
}

/**
 * Check if a given object implements the APILEAYearlyDetail interface.
 */
export function instanceOfAPILEAYearlyDetail(value: object): value is APILEAYearlyDetail {
    return true;
}

export function APILEAYearlyDetailFromJSON(json: any): APILEAYearlyDetail {
    return APILEAYearlyDetailFromJSONTyped(json, false);
}

export function APILEAYearlyDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): APILEAYearlyDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'numberOfStudents': json['numberOfStudents'] == null ? undefined : json['numberOfStudents'],
        'numberOfSpecialEdStudents': json['numberOfSpecialEdStudents'] == null ? undefined : json['numberOfSpecialEdStudents'],
        'numberOfEnglishLanguageLearnerStudents': json['numberOfEnglishLanguageLearnerStudents'] == null ? undefined : json['numberOfEnglishLanguageLearnerStudents'],
        'numberOfTeachers': json['numberOfTeachers'] == null ? undefined : json['numberOfTeachers'],
        'numberOfTeachersPK': json['numberOfTeachersPK'] == null ? undefined : json['numberOfTeachersPK'],
        'numberOfTeachersK': json['numberOfTeachersK'] == null ? undefined : json['numberOfTeachersK'],
        'numberOfTeachersElementary': json['numberOfTeachersElementary'] == null ? undefined : json['numberOfTeachersElementary'],
        'numberOfTeachersSecondary': json['numberOfTeachersSecondary'] == null ? undefined : json['numberOfTeachersSecondary'],
        'numberOfAids': json['numberOfAids'] == null ? undefined : json['numberOfAids'],
        'numberOfCoordsSupervisors': json['numberOfCoordsSupervisors'] == null ? undefined : json['numberOfCoordsSupervisors'],
        'numberOfGuidanceElem': json['numberOfGuidanceElem'] == null ? undefined : json['numberOfGuidanceElem'],
        'numberOfGuidanceSecondary': json['numberOfGuidanceSecondary'] == null ? undefined : json['numberOfGuidanceSecondary'],
        'numberOfGuidanceTotal': json['numberOfGuidanceTotal'] == null ? undefined : json['numberOfGuidanceTotal'],
        'numberOfLibrarians': json['numberOfLibrarians'] == null ? undefined : json['numberOfLibrarians'],
        'numberOfLibraryStaff': json['numberOfLibraryStaff'] == null ? undefined : json['numberOfLibraryStaff'],
        'numberOfLEAAdministrators': json['numberOfLEAAdministrators'] == null ? undefined : json['numberOfLEAAdministrators'],
        'numberOfLEASupportStaff': json['numberOfLEASupportStaff'] == null ? undefined : json['numberOfLEASupportStaff'],
        'numberOfSchoolAdministrators': json['numberOfSchoolAdministrators'] == null ? undefined : json['numberOfSchoolAdministrators'],
        'numberOfSchoolAdminSupportStaff': json['numberOfSchoolAdminSupportStaff'] == null ? undefined : json['numberOfSchoolAdminSupportStaff'],
        'numberOfStudentSupportStaff': json['numberOfStudentSupportStaff'] == null ? undefined : json['numberOfStudentSupportStaff'],
        'numberOfOtherSupportStaff': json['numberOfOtherSupportStaff'] == null ? undefined : json['numberOfOtherSupportStaff'],
    };
}

export function APILEAYearlyDetailToJSON(json: any): APILEAYearlyDetail {
    return APILEAYearlyDetailToJSONTyped(json, false);
}

export function APILEAYearlyDetailToJSONTyped(value?: APILEAYearlyDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'numberOfStudents': value['numberOfStudents'],
        'numberOfSpecialEdStudents': value['numberOfSpecialEdStudents'],
        'numberOfEnglishLanguageLearnerStudents': value['numberOfEnglishLanguageLearnerStudents'],
        'numberOfTeachers': value['numberOfTeachers'],
        'numberOfTeachersPK': value['numberOfTeachersPK'],
        'numberOfTeachersK': value['numberOfTeachersK'],
        'numberOfTeachersElementary': value['numberOfTeachersElementary'],
        'numberOfTeachersSecondary': value['numberOfTeachersSecondary'],
        'numberOfAids': value['numberOfAids'],
        'numberOfCoordsSupervisors': value['numberOfCoordsSupervisors'],
        'numberOfGuidanceElem': value['numberOfGuidanceElem'],
        'numberOfGuidanceSecondary': value['numberOfGuidanceSecondary'],
        'numberOfGuidanceTotal': value['numberOfGuidanceTotal'],
        'numberOfLibrarians': value['numberOfLibrarians'],
        'numberOfLibraryStaff': value['numberOfLibraryStaff'],
        'numberOfLEAAdministrators': value['numberOfLEAAdministrators'],
        'numberOfLEASupportStaff': value['numberOfLEASupportStaff'],
        'numberOfSchoolAdministrators': value['numberOfSchoolAdministrators'],
        'numberOfSchoolAdminSupportStaff': value['numberOfSchoolAdminSupportStaff'],
        'numberOfStudentSupportStaff': value['numberOfStudentSupportStaff'],
        'numberOfOtherSupportStaff': value['numberOfOtherSupportStaff'],
    };
}

