/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APILEARankHistory
 */
export interface APILEARankHistory {
    /**
     * School year (2017 - 2016-17)
     * @type {number}
     * @memberof APILEARankHistory
     */
    year?: number;
    /**
     * Statewide rank of this district
     * @type {number}
     * @memberof APILEARankHistory
     */
    rank?: number;
    /**
     * Count of district ranked in this state
     * @type {number}
     * @memberof APILEARankHistory
     */
    rankOf?: number;
    /**
     * The number of stars SchoolDigger awarded in the ranking of the district (0-5, 5 is best)
     * @type {number}
     * @memberof APILEARankHistory
     */
    rankStars?: number;
    /**
     * Percentile of this district's rank (e.g. this district performed better than (x)% of this state's districts)
     * @type {number}
     * @memberof APILEARankHistory
     */
    rankStatewidePercentage?: number;
    /**
     * The rank score calculated by SchoolDigger (see https://www.schooldigger.com/aboutranking.aspx)
     * @type {number}
     * @memberof APILEARankHistory
     */
    rankScore?: number;
}

/**
 * Check if a given object implements the APILEARankHistory interface.
 */
export function instanceOfAPILEARankHistory(value: object): value is APILEARankHistory {
    return true;
}

export function APILEARankHistoryFromJSON(json: any): APILEARankHistory {
    return APILEARankHistoryFromJSONTyped(json, false);
}

export function APILEARankHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): APILEARankHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'rankOf': json['rankOf'] == null ? undefined : json['rankOf'],
        'rankStars': json['rankStars'] == null ? undefined : json['rankStars'],
        'rankStatewidePercentage': json['rankStatewidePercentage'] == null ? undefined : json['rankStatewidePercentage'],
        'rankScore': json['rankScore'] == null ? undefined : json['rankScore'],
    };
}

export function APILEARankHistoryToJSON(json: any): APILEARankHistory {
    return APILEARankHistoryToJSONTyped(json, false);
}

export function APILEARankHistoryToJSONTyped(value?: APILEARankHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'rank': value['rank'],
        'rankOf': value['rankOf'],
        'rankStars': value['rankStars'],
        'rankStatewidePercentage': value['rankStatewidePercentage'],
        'rankScore': value['rankScore'],
    };
}

