/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APILatLong } from './APILatLong';
import {
    APILatLongFromJSON,
    APILatLongFromJSONTyped,
    APILatLongToJSON,
    APILatLongToJSONTyped,
} from './APILatLong';

/**
 * 
 * @export
 * @interface APILocation
 */
export interface APILocation {
    /**
     * 
     * @type {APILatLong}
     * @memberof APILocation
     */
    latLong?: APILatLong;
    /**
     * Street address of the school or district (e.g. '18500 37th Avenue N.E.')
     * @type {string}
     * @memberof APILocation
     */
    street?: string;
    /**
     * City where the school or district is located
     * @type {string}
     * @memberof APILocation
     */
    city?: string;
    /**
     * Two-letter state abbreviation (e.g. 'WA')
     * @type {string}
     * @memberof APILocation
     */
    state?: string;
    /**
     * Full state name (WA = Washington)
     * @type {string}
     * @memberof APILocation
     */
    stateFull?: string;
    /**
     * 5-digit ZIP code
     * @type {string}
     * @memberof APILocation
     */
    zip?: string;
    /**
     * ZIP+4 suffix (4 digits, may be empty)
     * @type {string}
     * @memberof APILocation
     */
    zip4?: string;
    /**
     * SchoolDigger URL for schools in this city
     * @type {string}
     * @memberof APILocation
     */
    cityURL?: string;
    /**
     * SchoolDigger URL for schools in this zip code
     * @type {string}
     * @memberof APILocation
     */
    zipURL?: string;
    /**
     * HTML formatted address
     * @type {string}
     * @memberof APILocation
     */
    html?: string;
}

/**
 * Check if a given object implements the APILocation interface.
 */
export function instanceOfAPILocation(value: object): value is APILocation {
    return true;
}

export function APILocationFromJSON(json: any): APILocation {
    return APILocationFromJSONTyped(json, false);
}

export function APILocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): APILocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latLong': json['latLong'] == null ? undefined : APILatLongFromJSON(json['latLong']),
        'street': json['street'] == null ? undefined : json['street'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'stateFull': json['stateFull'] == null ? undefined : json['stateFull'],
        'zip': json['zip'] == null ? undefined : json['zip'],
        'zip4': json['zip4'] == null ? undefined : json['zip4'],
        'cityURL': json['cityURL'] == null ? undefined : json['cityURL'],
        'zipURL': json['zipURL'] == null ? undefined : json['zipURL'],
        'html': json['html'] == null ? undefined : json['html'],
    };
}

export function APILocationToJSON(json: any): APILocation {
    return APILocationToJSONTyped(json, false);
}

export function APILocationToJSONTyped(value?: APILocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latLong': APILatLongToJSON(value['latLong']),
        'street': value['street'],
        'city': value['city'],
        'state': value['state'],
        'stateFull': value['stateFull'],
        'zip': value['zip'],
        'zip4': value['zip4'],
        'cityURL': value['cityURL'],
        'zipURL': value['zipURL'],
        'html': value['html'],
    };
}

