/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIPolyline
 */
export interface APIPolyline {
    /**
     * Google Maps encoded polyline string for rendering the boundary on a map. Compatible with google.maps.geometry.encoding.decodePath() and similar libraries. IMPORTANT: Backslashes are JSON-escaped (appear as \\). Unescape to single backslashes before decoding.
     * @type {string}
     * @memberof APIPolyline
     */
    polylineOverlayEncodedPoints?: string;
    /**
     * Number of encoded points in polyline
     * @type {number}
     * @memberof APIPolyline
     */
    numberEncodedPoints?: number;
}

/**
 * Check if a given object implements the APIPolyline interface.
 */
export function instanceOfAPIPolyline(value: object): value is APIPolyline {
    return true;
}

export function APIPolylineFromJSON(json: any): APIPolyline {
    return APIPolylineFromJSONTyped(json, false);
}

export function APIPolylineFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIPolyline {
    if (json == null) {
        return json;
    }
    return {
        
        'polylineOverlayEncodedPoints': json['polylineOverlayEncodedPoints'] == null ? undefined : json['polylineOverlayEncodedPoints'],
        'numberEncodedPoints': json['numberEncodedPoints'] == null ? undefined : json['numberEncodedPoints'],
    };
}

export function APIPolylineToJSON(json: any): APIPolyline {
    return APIPolylineToJSONTyped(json, false);
}

export function APIPolylineToJSONTyped(value?: APIPolyline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'polylineOverlayEncodedPoints': value['polylineOverlayEncodedPoints'],
        'numberEncodedPoints': value['numberEncodedPoints'],
    };
}

