/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIRankHistory
 */
export interface APIRankHistory {
    /**
     * School year (2017 - 2016-17)
     * @type {number}
     * @memberof APIRankHistory
     */
    year?: number;
    /**
     * Statewide rank of this School
     * @type {number}
     * @memberof APIRankHistory
     */
    rank?: number;
    /**
     * Count of schools ranked at this state/level
     * @type {number}
     * @memberof APIRankHistory
     */
    rankOf?: number;
    /**
     * The number of stars SchoolDigger awarded in the ranking of the school (0-5, 5 is best)
     * @type {number}
     * @memberof APIRankHistory
     */
    rankStars?: number;
    /**
     * The level for which this school is ranked (Elementary, Middle, High)
     * @type {string}
     * @memberof APIRankHistory
     */
    rankLevel?: string;
    /**
     * Percentile of this school's rank (e.g. this school performed better than (x)% of this state's elementary schools)
     * @type {number}
     * @memberof APIRankHistory
     */
    rankStatewidePercentage?: number;
    /**
     * The Average Standard score calculated by SchoolDigger (see: https://www.schooldigger.com/aboutrankingmethodology.aspx)
     * @type {number}
     * @memberof APIRankHistory
     */
    averageStandardScore?: number;
}

/**
 * Check if a given object implements the APIRankHistory interface.
 */
export function instanceOfAPIRankHistory(value: object): value is APIRankHistory {
    return true;
}

export function APIRankHistoryFromJSON(json: any): APIRankHistory {
    return APIRankHistoryFromJSONTyped(json, false);
}

export function APIRankHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIRankHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'rankOf': json['rankOf'] == null ? undefined : json['rankOf'],
        'rankStars': json['rankStars'] == null ? undefined : json['rankStars'],
        'rankLevel': json['rankLevel'] == null ? undefined : json['rankLevel'],
        'rankStatewidePercentage': json['rankStatewidePercentage'] == null ? undefined : json['rankStatewidePercentage'],
        'averageStandardScore': json['averageStandardScore'] == null ? undefined : json['averageStandardScore'],
    };
}

export function APIRankHistoryToJSON(json: any): APIRankHistory {
    return APIRankHistoryToJSONTyped(json, false);
}

export function APIRankHistoryToJSONTyped(value?: APIRankHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'rank': value['rank'],
        'rankOf': value['rankOf'],
        'rankStars': value['rankStars'],
        'rankLevel': value['rankLevel'],
        'rankStatewidePercentage': value['rankStatewidePercentage'],
        'averageStandardScore': value['averageStandardScore'],
    };
}

