/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v3.0
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A percent metric (percentMetStandard, percentTier1..5) that the state did not publish as a single exact number.
 * In API 3.0 a percent metric is EITHER a plain number (the state reported an exact value) OR this object, and is
 * absent when nothing was reported. status is one of: 'range' (the state published only a range: low / high are
 * the state's bounds), 'suppressed' (withheld by the state to protect student privacy; no value), 'legacyImputed'
 * (a pre-2018 SchoolDigger stand-in: value is the 4 / 96 number older API versions return, low / high are the
 * state's bounds), 'derived' (computed by SchoolDigger from the other reported levels: value when exact, otherwise
 * low / high). Rendering rule: exact 82.3 -&gt; '82.3%'; low 0 -&gt; '&lt; 10%'; high 100 -&gt; '&gt;= 95%'; otherwise
 * '10-15%'; suppressed -&gt; a dash. See https://developer.schooldigger.com/data-quality
 * @export
 * @interface APIReportedPercent
 */
export interface APIReportedPercent {
    /**
     * Why there is no exact number: 'range', 'suppressed', 'legacyImputed' or 'derived'
     * @type {string}
     * @memberof APIReportedPercent
     */
    status?: string;
    /**
     * The percent value, when one exists (status 'derived' with an exact result, or the 'legacyImputed' stand-in). Absent otherwise.
     * @type {number}
     * @memberof APIReportedPercent
     */
    value?: number;
    /**
     * Lower bound of the range in percent (0 means 'less than high'). Absent for 'suppressed'.
     * @type {number}
     * @memberof APIReportedPercent
     */
    low?: number;
    /**
     * Upper bound of the range in percent (100 means 'at least low'). Absent for 'suppressed'.
     * @type {number}
     * @memberof APIReportedPercent
     */
    high?: number;
}

/**
 * Check if a given object implements the APIReportedPercent interface.
 */
export function instanceOfAPIReportedPercent(value: object): value is APIReportedPercent {
    return true;
}

export function APIReportedPercentFromJSON(json: any): APIReportedPercent {
    return APIReportedPercentFromJSONTyped(json, false);
}

export function APIReportedPercentFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIReportedPercent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'value': json['value'] == null ? undefined : json['value'],
        'low': json['low'] == null ? undefined : json['low'],
        'high': json['high'] == null ? undefined : json['high'],
    };
}

export function APIReportedPercentToJSON(json: any): APIReportedPercent {
    return APIReportedPercentToJSONTyped(json, false);
}

export function APIReportedPercentToJSONTyped(value?: APIReportedPercent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'value': value['value'],
        'low': value['low'],
        'high': value['high'],
    };
}

