/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APISchoolFinance
 */
export interface APISchoolFinance {
    /**
     * Fiscal school year using spring-year convention (e.g. 2024 = the 2023-2024 fiscal year).
     * @type {number}
     * @memberof APISchoolFinance
     */
    year?: number;
    /**
     * Total spending per student from all funds (Pro or Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingPerStudent?: number;
    /**
     * Spending per student for Personnel at the Federal Level (Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingFederalPersonnel?: number;
    /**
     * Spending per student for Non-personnel at the Federal Level (Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingFederalNonPersonnel?: number;
    /**
     * Spending per student for Personnel at the State and Local Level (Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingStateLocalPersonnel?: number;
    /**
     * Spending per student for Non-personnel at the State and Local Level (Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingStateLocalNonPersonnel?: number;
    /**
     * Spending per student at the Federal Level (Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingPerStudentFederal?: number;
    /**
     * Spending per student at the State and Local Level (Enterprise level only)
     * @type {number}
     * @memberof APISchoolFinance
     */
    spendingPerStudentStateLocal?: number;
}

/**
 * Check if a given object implements the APISchoolFinance interface.
 */
export function instanceOfAPISchoolFinance(value: object): value is APISchoolFinance {
    return true;
}

export function APISchoolFinanceFromJSON(json: any): APISchoolFinance {
    return APISchoolFinanceFromJSONTyped(json, false);
}

export function APISchoolFinanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolFinance {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'spendingPerStudent': json['spendingPerStudent'] == null ? undefined : json['spendingPerStudent'],
        'spendingFederalPersonnel': json['spendingFederalPersonnel'] == null ? undefined : json['spendingFederalPersonnel'],
        'spendingFederalNonPersonnel': json['spendingFederalNonPersonnel'] == null ? undefined : json['spendingFederalNonPersonnel'],
        'spendingStateLocalPersonnel': json['spendingStateLocalPersonnel'] == null ? undefined : json['spendingStateLocalPersonnel'],
        'spendingStateLocalNonPersonnel': json['spendingStateLocalNonPersonnel'] == null ? undefined : json['spendingStateLocalNonPersonnel'],
        'spendingPerStudentFederal': json['spendingPerStudentFederal'] == null ? undefined : json['spendingPerStudentFederal'],
        'spendingPerStudentStateLocal': json['spendingPerStudentStateLocal'] == null ? undefined : json['spendingPerStudentStateLocal'],
    };
}

export function APISchoolFinanceToJSON(json: any): APISchoolFinance {
    return APISchoolFinanceToJSONTyped(json, false);
}

export function APISchoolFinanceToJSONTyped(value?: APISchoolFinance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'spendingPerStudent': value['spendingPerStudent'],
        'spendingFederalPersonnel': value['spendingFederalPersonnel'],
        'spendingFederalNonPersonnel': value['spendingFederalNonPersonnel'],
        'spendingStateLocalPersonnel': value['spendingStateLocalPersonnel'],
        'spendingStateLocalNonPersonnel': value['spendingStateLocalNonPersonnel'],
        'spendingPerStudentFederal': value['spendingPerStudentFederal'],
        'spendingPerStudentStateLocal': value['spendingPerStudentStateLocal'],
    };
}

