/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APISchoolReview
 */
export interface APISchoolReview {
    /**
     * The date the review was submitted, formatted as M/D/YYYY (e.g. '1/24/2009'). Note: single-digit months and days are not zero-padded.
     * @type {string}
     * @memberof APISchoolReview
     */
    submitDate?: string;
    /**
     * Number of stars - 1 (poor) to 5 (excellent)
     * @type {number}
     * @memberof APISchoolReview
     */
    numberOfStars?: number;
    /**
     * Free-text comment left by the reviewer. Content is HTML encoded (special characters escaped). May be empty string if reviewer only left a star rating.
     * @type {string}
     * @memberof APISchoolReview
     */
    comment?: string;
    /**
     * Reviewer type (parent, student, teacher, principal, citizen)
     * @type {string}
     * @memberof APISchoolReview
     */
    submittedBy?: string;
}

/**
 * Check if a given object implements the APISchoolReview interface.
 */
export function instanceOfAPISchoolReview(value: object): value is APISchoolReview {
    return true;
}

export function APISchoolReviewFromJSON(json: any): APISchoolReview {
    return APISchoolReviewFromJSONTyped(json, false);
}

export function APISchoolReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolReview {
    if (json == null) {
        return json;
    }
    return {
        
        'submitDate': json['submitDate'] == null ? undefined : json['submitDate'],
        'numberOfStars': json['numberOfStars'] == null ? undefined : json['numberOfStars'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'submittedBy': json['submittedBy'] == null ? undefined : json['submittedBy'],
    };
}

export function APISchoolReviewToJSON(json: any): APISchoolReview {
    return APISchoolReviewToJSONTyped(json, false);
}

export function APISchoolReviewToJSONTyped(value?: APISchoolReview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submitDate': value['submitDate'],
        'numberOfStars': value['numberOfStars'],
        'comment': value['comment'],
        'submittedBy': value['submittedBy'],
    };
}

