/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APISchoolSummary21 } from './APISchoolSummary21';
import {
    APISchoolSummary21FromJSON,
    APISchoolSummary21FromJSONTyped,
    APISchoolSummary21ToJSON,
    APISchoolSummary21ToJSONTyped,
} from './APISchoolSummary21';

/**
 * 
 * @export
 * @interface APISchoolListRank21
 */
export interface APISchoolListRank21 {
    /**
     * Year this ranking list represents (2018 = 2017-18)
     * @type {number}
     * @memberof APISchoolListRank21
     */
    rankYear?: number;
    /**
     * Year rankings returned for comparison (2018 = 2017-18)
     * @type {number}
     * @memberof APISchoolListRank21
     */
    rankYearCompare?: number;
    /**
     * The years for which SchoolDigger rankings are available for this state and level
     * @type {Array<number>}
     * @memberof APISchoolListRank21
     */
    rankYearsAvailable?: Array<number>;
    /**
     * The total count of schools in this ranking list
     * @type {number}
     * @memberof APISchoolListRank21
     */
    numberOfSchools?: number;
    /**
     * The total count of pages this ranking list based on given per_page value
     * @type {number}
     * @memberof APISchoolListRank21
     */
    numberOfPages?: number;
    /**
     * The schools in the ranking list
     * @type {Array<APISchoolSummary21>}
     * @memberof APISchoolListRank21
     */
    schoolList?: Array<APISchoolSummary21>;
}

/**
 * Check if a given object implements the APISchoolListRank21 interface.
 */
export function instanceOfAPISchoolListRank21(value: object): value is APISchoolListRank21 {
    return true;
}

export function APISchoolListRank21FromJSON(json: any): APISchoolListRank21 {
    return APISchoolListRank21FromJSONTyped(json, false);
}

export function APISchoolListRank21FromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolListRank21 {
    if (json == null) {
        return json;
    }
    return {
        
        'rankYear': json['rankYear'] == null ? undefined : json['rankYear'],
        'rankYearCompare': json['rankYearCompare'] == null ? undefined : json['rankYearCompare'],
        'rankYearsAvailable': json['rankYearsAvailable'] == null ? undefined : json['rankYearsAvailable'],
        'numberOfSchools': json['numberOfSchools'] == null ? undefined : json['numberOfSchools'],
        'numberOfPages': json['numberOfPages'] == null ? undefined : json['numberOfPages'],
        'schoolList': json['schoolList'] == null ? undefined : ((json['schoolList'] as Array<any>).map(APISchoolSummary21FromJSON)),
    };
}

export function APISchoolListRank21ToJSON(json: any): APISchoolListRank21 {
    return APISchoolListRank21ToJSONTyped(json, false);
}

export function APISchoolListRank21ToJSONTyped(value?: APISchoolListRank21 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rankYear': value['rankYear'],
        'rankYearCompare': value['rankYearCompare'],
        'rankYearsAvailable': value['rankYearsAvailable'],
        'numberOfSchools': value['numberOfSchools'],
        'numberOfPages': value['numberOfPages'],
        'schoolList': value['schoolList'] == null ? undefined : ((value['schoolList'] as Array<any>).map(APISchoolSummary21ToJSON)),
    };
}

