/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APITestScoreWrapper } from './APITestScoreWrapper';
import {
    APITestScoreWrapperFromJSON,
    APITestScoreWrapperFromJSONTyped,
    APITestScoreWrapperToJSON,
    APITestScoreWrapperToJSONTyped,
} from './APITestScoreWrapper';
import type { APIRankHistory } from './APIRankHistory';
import {
    APIRankHistoryFromJSON,
    APIRankHistoryFromJSONTyped,
    APIRankHistoryToJSON,
    APIRankHistoryToJSONTyped,
} from './APIRankHistory';
import type { APISchoolFinance } from './APISchoolFinance';
import {
    APISchoolFinanceFromJSON,
    APISchoolFinanceFromJSONTyped,
    APISchoolFinanceToJSON,
    APISchoolFinanceToJSONTyped,
} from './APISchoolFinance';
import type { APISchoolReview } from './APISchoolReview';
import {
    APISchoolReviewFromJSON,
    APISchoolReviewFromJSONTyped,
    APISchoolReviewToJSON,
    APISchoolReviewToJSONTyped,
} from './APISchoolReview';
import type { APIYearlyDemographics } from './APIYearlyDemographics';
import {
    APIYearlyDemographicsFromJSON,
    APIYearlyDemographicsFromJSONTyped,
    APIYearlyDemographicsToJSON,
    APIYearlyDemographicsToJSONTyped,
} from './APIYearlyDemographics';
import type { APIGraduationRate } from './APIGraduationRate';
import {
    APIGraduationRateFromJSON,
    APIGraduationRateFromJSONTyped,
    APIGraduationRateToJSON,
    APIGraduationRateToJSONTyped,
} from './APIGraduationRate';
import type { APIDropoutRate } from './APIDropoutRate';
import {
    APIDropoutRateFromJSON,
    APIDropoutRateFromJSONTyped,
    APIDropoutRateToJSON,
    APIDropoutRateToJSONTyped,
} from './APIDropoutRate';
import type { APICounty } from './APICounty';
import {
    APICountyFromJSON,
    APICountyFromJSONTyped,
    APICountyToJSON,
    APICountyToJSONTyped,
} from './APICounty';
import type { APIDistrictSum } from './APIDistrictSum';
import {
    APIDistrictSumFromJSON,
    APIDistrictSumFromJSONTyped,
    APIDistrictSumToJSON,
    APIDistrictSumToJSONTyped,
} from './APIDistrictSum';
import type { APIChronicAbsenteeismRate } from './APIChronicAbsenteeismRate';
import {
    APIChronicAbsenteeismRateFromJSON,
    APIChronicAbsenteeismRateFromJSONTyped,
    APIChronicAbsenteeismRateToJSON,
    APIChronicAbsenteeismRateToJSONTyped,
} from './APIChronicAbsenteeismRate';
import type { APILocation } from './APILocation';
import {
    APILocationFromJSON,
    APILocationFromJSONTyped,
    APILocationToJSON,
    APILocationToJSONTyped,
} from './APILocation';

/**
 * 
 * @export
 * @interface APISchoolFull22
 */
export interface APISchoolFull22 {
    /**
     * SchoolDigger School ID Number (12 digits)
     * @type {string}
     * @memberof APISchoolFull22
     */
    schoolid?: string;
    /**
     * School name
     * @type {string}
     * @memberof APISchoolFull22
     */
    schoolName?: string;
    /**
     * School phone number
     * @type {string}
     * @memberof APISchoolFull22
     */
    phone?: string;
    /**
     * URL of the school's own public website (may be null if not available). This is NOT the SchoolDigger page — see urlSchoolDigger for that.
     * @type {string}
     * @memberof APISchoolFull22
     */
    url?: string;
    /**
     * SchoolDigger URL for this school
     * @type {string}
     * @memberof APISchoolFull22
     */
    urlSchoolDigger?: string;
    /**
     * SchoolDigger URL for comparing this school to nearby schools
     * @type {string}
     * @memberof APISchoolFull22
     */
    urlCompareSchoolDigger?: string;
    /**
     * 
     * @type {APILocation}
     * @memberof APISchoolFull22
     */
    address?: APILocation;
    /**
     * NCES urban-centric locale classification (e.g. 'City: Large', 'Suburb: Midsize', 'Rural: Fringe'). Categories: City (Large/Midsize/Small), Suburb (Large/Midsize/Small), Town (Fringe/Distant/Remote), Rural (Fringe/Distant/Remote). See https://nces.ed.gov/ccd/rural_locales.asp
     * @type {string}
     * @memberof APISchoolFull22
     */
    locale?: string;
    /**
     * The low grade served by this school (PK = Prekindergarten, K = Kindergarten)
     * @type {string}
     * @memberof APISchoolFull22
     */
    lowGrade?: string;
    /**
     * The high grade served by this school
     * @type {string}
     * @memberof APISchoolFull22
     */
    highGrade?: string;
    /**
     * The level of school (Elementary, Middle, High, Private, Alternative)
     * @type {string}
     * @memberof APISchoolFull22
     */
    schoolLevel?: string;
    /**
     * Indicates if school is a charter school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolFull22
     */
    isCharterSchool?: string;
    /**
     * Indicates if school is a magnet school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolFull22
     */
    isMagnetSchool?: string;
    /**
     * Indicates if school is a virtual school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolFull22
     */
    isVirtualSchool?: string;
    /**
     * Indicates if school is a Title I school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolFull22
     */
    isTitleISchool?: string;
    /**
     * Indicates if a school-wide Title I school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolFull22
     */
    isTitleISchoolwideSchool?: string;
    /**
     * Indicates if school is a private school (Yes/No)
     * @type {boolean}
     * @memberof APISchoolFull22
     */
    isPrivate?: boolean;
    /**
     * Days in the school year (private schools only)
     * @type {number}
     * @memberof APISchoolFull22
     */
    privateDays?: number;
    /**
     * Hours in the school day (private schools only)
     * @type {number}
     * @memberof APISchoolFull22
     */
    privateHours?: number;
    /**
     * Indicates if the school has a library (private schools only)
     * @type {boolean}
     * @memberof APISchoolFull22
     */
    privateHasLibrary?: boolean;
    /**
     * Coed/Boys/Girls (private schools only)
     * @type {string}
     * @memberof APISchoolFull22
     */
    privateCoed?: string;
    /**
     * Affiliation of the school (private schools only)
     * @type {string}
     * @memberof APISchoolFull22
     */
    privateOrientation?: string;
    /**
     * The NCES ID of the school (private schools only)
     * @type {string}
     * @memberof APISchoolFull22
     */
    ncesPrivateSchoolID?: string;
    /**
     * 
     * @type {APIDistrictSum}
     * @memberof APISchoolFull22
     */
    district?: APIDistrictSum;
    /**
     * 
     * @type {APICounty}
     * @memberof APISchoolFull22
     */
    county?: APICounty;
    /**
     * User-submitted reviews from SchoolDigger.com visitors. Each review includes a star rating (1-5), comment text (HTML encoded), date, and reviewer type (parent, student, teacher, principal, citizen). Reviews are unmoderated user content.
     * @type {Array<APISchoolReview>}
     * @memberof APISchoolFull22
     */
    reviews?: Array<APISchoolReview>;
    /**
     * Yearly per-student spending data. Array is sorted most recent year first. spendingPerStudent is available at Pro level; detailed federal/state/local and personnel/non-personnel breakdowns require Enterprise level.
     * @type {Array<APISchoolFinance>}
     * @memberof APISchoolFull22
     */
    finance?: Array<APISchoolFinance>;
    /**
     * 4-year adjusted cohort graduation rates at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
     * @type {Array<APIGraduationRate>}
     * @memberof APISchoolFull22
     */
    graduationRates?: Array<APIGraduationRate>;
    /**
     * Annual dropout rates at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.
     * @type {Array<APIDropoutRate>}
     * @memberof APISchoolFull22
     */
    dropoutRates?: Array<APIDropoutRate>;
    /**
     * Chronic absenteeism rates (students missing 15+ days) at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first. Data availability varies by state.
     * @type {Array<APIChronicAbsenteeismRate>}
     * @memberof APISchoolFull22
     */
    chronicAbsenteeismRates?: Array<APIChronicAbsenteeismRate>;
    /**
     * SchoolDigger yearly rank history for this school, sorted most recent year first. Schools are ranked within their state and level (Elementary, Middle, or High). Includes all available years — the full record returns more years than the summary in search results.
     * @type {Array<APIRankHistory>}
     * @memberof APISchoolFull22
     */
    rankHistory?: Array<APIRankHistory>;
    /**
     * Returns the movement of rank for this school between current and previous year
     * @type {number}
     * @memberof APISchoolFull22
     */
    rankMovement?: number;
    /**
     * Standardized test score results with school, district, and state comparisons. Each entry represents one test/subject/grade/year combination. Includes percent meeting standard and optional tier breakdowns (Enterprise level). Tests are state-specific (e.g. SBA, WCAS in WA; CAASPP in CA). Requires Pro or Enterprise API subscription.
     * @type {Array<APITestScoreWrapper>}
     * @memberof APISchoolFull22
     */
    testScores?: Array<APITestScoreWrapper>;
    /**
     * Yearly enrollment, demographics, and staffing for this school. Array is sorted most recent year first and includes all available years (back to 1988 for some schools). The full record returns more years than the summary in search results.
     * @type {Array<APIYearlyDemographics>}
     * @memberof APISchoolFull22
     */
    schoolYearlyDetails?: Array<APIYearlyDemographics>;
}

/**
 * Check if a given object implements the APISchoolFull22 interface.
 */
export function instanceOfAPISchoolFull22(value: object): value is APISchoolFull22 {
    return true;
}

export function APISchoolFull22FromJSON(json: any): APISchoolFull22 {
    return APISchoolFull22FromJSONTyped(json, false);
}

export function APISchoolFull22FromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolFull22 {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolid': json['schoolid'] == null ? undefined : json['schoolid'],
        'schoolName': json['schoolName'] == null ? undefined : json['schoolName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'url': json['url'] == null ? undefined : json['url'],
        'urlSchoolDigger': json['urlSchoolDigger'] == null ? undefined : json['urlSchoolDigger'],
        'urlCompareSchoolDigger': json['urlCompareSchoolDigger'] == null ? undefined : json['urlCompareSchoolDigger'],
        'address': json['address'] == null ? undefined : APILocationFromJSON(json['address']),
        'locale': json['locale'] == null ? undefined : json['locale'],
        'lowGrade': json['lowGrade'] == null ? undefined : json['lowGrade'],
        'highGrade': json['highGrade'] == null ? undefined : json['highGrade'],
        'schoolLevel': json['schoolLevel'] == null ? undefined : json['schoolLevel'],
        'isCharterSchool': json['isCharterSchool'] == null ? undefined : json['isCharterSchool'],
        'isMagnetSchool': json['isMagnetSchool'] == null ? undefined : json['isMagnetSchool'],
        'isVirtualSchool': json['isVirtualSchool'] == null ? undefined : json['isVirtualSchool'],
        'isTitleISchool': json['isTitleISchool'] == null ? undefined : json['isTitleISchool'],
        'isTitleISchoolwideSchool': json['isTitleISchoolwideSchool'] == null ? undefined : json['isTitleISchoolwideSchool'],
        'isPrivate': json['isPrivate'] == null ? undefined : json['isPrivate'],
        'privateDays': json['privateDays'] == null ? undefined : json['privateDays'],
        'privateHours': json['privateHours'] == null ? undefined : json['privateHours'],
        'privateHasLibrary': json['privateHasLibrary'] == null ? undefined : json['privateHasLibrary'],
        'privateCoed': json['privateCoed'] == null ? undefined : json['privateCoed'],
        'privateOrientation': json['privateOrientation'] == null ? undefined : json['privateOrientation'],
        'ncesPrivateSchoolID': json['ncesPrivateSchoolID'] == null ? undefined : json['ncesPrivateSchoolID'],
        'district': json['district'] == null ? undefined : APIDistrictSumFromJSON(json['district']),
        'county': json['county'] == null ? undefined : APICountyFromJSON(json['county']),
        'reviews': json['reviews'] == null ? undefined : ((json['reviews'] as Array<any>).map(APISchoolReviewFromJSON)),
        'finance': json['finance'] == null ? undefined : ((json['finance'] as Array<any>).map(APISchoolFinanceFromJSON)),
        'graduationRates': json['graduationRates'] == null ? undefined : ((json['graduationRates'] as Array<any>).map(APIGraduationRateFromJSON)),
        'dropoutRates': json['dropoutRates'] == null ? undefined : ((json['dropoutRates'] as Array<any>).map(APIDropoutRateFromJSON)),
        'chronicAbsenteeismRates': json['chronicAbsenteeismRates'] == null ? undefined : ((json['chronicAbsenteeismRates'] as Array<any>).map(APIChronicAbsenteeismRateFromJSON)),
        'rankHistory': json['rankHistory'] == null ? undefined : ((json['rankHistory'] as Array<any>).map(APIRankHistoryFromJSON)),
        'rankMovement': json['rankMovement'] == null ? undefined : json['rankMovement'],
        'testScores': json['testScores'] == null ? undefined : ((json['testScores'] as Array<any>).map(APITestScoreWrapperFromJSON)),
        'schoolYearlyDetails': json['schoolYearlyDetails'] == null ? undefined : ((json['schoolYearlyDetails'] as Array<any>).map(APIYearlyDemographicsFromJSON)),
    };
}

export function APISchoolFull22ToJSON(json: any): APISchoolFull22 {
    return APISchoolFull22ToJSONTyped(json, false);
}

export function APISchoolFull22ToJSONTyped(value?: APISchoolFull22 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schoolid': value['schoolid'],
        'schoolName': value['schoolName'],
        'phone': value['phone'],
        'url': value['url'],
        'urlSchoolDigger': value['urlSchoolDigger'],
        'urlCompareSchoolDigger': value['urlCompareSchoolDigger'],
        'address': APILocationToJSON(value['address']),
        'locale': value['locale'],
        'lowGrade': value['lowGrade'],
        'highGrade': value['highGrade'],
        'schoolLevel': value['schoolLevel'],
        'isCharterSchool': value['isCharterSchool'],
        'isMagnetSchool': value['isMagnetSchool'],
        'isVirtualSchool': value['isVirtualSchool'],
        'isTitleISchool': value['isTitleISchool'],
        'isTitleISchoolwideSchool': value['isTitleISchoolwideSchool'],
        'isPrivate': value['isPrivate'],
        'privateDays': value['privateDays'],
        'privateHours': value['privateHours'],
        'privateHasLibrary': value['privateHasLibrary'],
        'privateCoed': value['privateCoed'],
        'privateOrientation': value['privateOrientation'],
        'ncesPrivateSchoolID': value['ncesPrivateSchoolID'],
        'district': APIDistrictSumToJSON(value['district']),
        'county': APICountyToJSON(value['county']),
        'reviews': value['reviews'] == null ? undefined : ((value['reviews'] as Array<any>).map(APISchoolReviewToJSON)),
        'finance': value['finance'] == null ? undefined : ((value['finance'] as Array<any>).map(APISchoolFinanceToJSON)),
        'graduationRates': value['graduationRates'] == null ? undefined : ((value['graduationRates'] as Array<any>).map(APIGraduationRateToJSON)),
        'dropoutRates': value['dropoutRates'] == null ? undefined : ((value['dropoutRates'] as Array<any>).map(APIDropoutRateToJSON)),
        'chronicAbsenteeismRates': value['chronicAbsenteeismRates'] == null ? undefined : ((value['chronicAbsenteeismRates'] as Array<any>).map(APIChronicAbsenteeismRateToJSON)),
        'rankHistory': value['rankHistory'] == null ? undefined : ((value['rankHistory'] as Array<any>).map(APIRankHistoryToJSON)),
        'rankMovement': value['rankMovement'],
        'testScores': value['testScores'] == null ? undefined : ((value['testScores'] as Array<any>).map(APITestScoreWrapperToJSON)),
        'schoolYearlyDetails': value['schoolYearlyDetails'] == null ? undefined : ((value['schoolYearlyDetails'] as Array<any>).map(APIYearlyDemographicsToJSON)),
    };
}

