/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APISchoolSummary22 } from './APISchoolSummary22';
import {
    APISchoolSummary22FromJSON,
    APISchoolSummary22FromJSONTyped,
    APISchoolSummary22ToJSON,
    APISchoolSummary22ToJSONTyped,
} from './APISchoolSummary22';

/**
 * 
 * @export
 * @interface APISchoolList22
 */
export interface APISchoolList22 {
    /**
     * The total count of schools that match your query
     * @type {number}
     * @memberof APISchoolList22
     */
    numberOfSchools?: number;
    /**
     * The total count of pages in your query list based on given per_page value
     * @type {number}
     * @memberof APISchoolList22
     */
    numberOfPages?: number;
    /**
     * 
     * @type {Array<APISchoolSummary22>}
     * @memberof APISchoolList22
     */
    schoolList?: Array<APISchoolSummary22>;
}

/**
 * Check if a given object implements the APISchoolList22 interface.
 */
export function instanceOfAPISchoolList22(value: object): value is APISchoolList22 {
    return true;
}

export function APISchoolList22FromJSON(json: any): APISchoolList22 {
    return APISchoolList22FromJSONTyped(json, false);
}

export function APISchoolList22FromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolList22 {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfSchools': json['numberOfSchools'] == null ? undefined : json['numberOfSchools'],
        'numberOfPages': json['numberOfPages'] == null ? undefined : json['numberOfPages'],
        'schoolList': json['schoolList'] == null ? undefined : ((json['schoolList'] as Array<any>).map(APISchoolSummary22FromJSON)),
    };
}

export function APISchoolList22ToJSON(json: any): APISchoolList22 {
    return APISchoolList22ToJSONTyped(json, false);
}

export function APISchoolList22ToJSONTyped(value?: APISchoolList22 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfSchools': value['numberOfSchools'],
        'numberOfPages': value['numberOfPages'],
        'schoolList': value['schoolList'] == null ? undefined : ((value['schoolList'] as Array<any>).map(APISchoolSummary22ToJSON)),
    };
}

