/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APISchoolAC23
 */
export interface APISchoolAC23 {
    /**
     * SchoolDigger School ID Number (12 digits). Use /schools/{schoolID} to retrieve the full school record
     * @type {string}
     * @memberof APISchoolAC23
     */
    schoolid?: string;
    /**
     * School name
     * @type {string}
     * @memberof APISchoolAC23
     */
    schoolName?: string;
    /**
     * School location city
     * @type {string}
     * @memberof APISchoolAC23
     */
    city?: string;
    /**
     * School location state
     * @type {string}
     * @memberof APISchoolAC23
     */
    state?: string;
    /**
     * School location zip code (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {string}
     * @memberof APISchoolAC23
     */
    zip?: string;
    /**
     * The level of school (Elementary, Middle, High, Private, Alternative)
     * @type {string}
     * @memberof APISchoolAC23
     */
    schoolLevel?: string;
    /**
     * The low grade served by this school (PK = Prekindergarten, K = Kindergarten)  (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {string}
     * @memberof APISchoolAC23
     */
    lowGrade?: string;
    /**
     * The high grade served by this school  (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {string}
     * @memberof APISchoolAC23
     */
    highGrade?: string;
    /**
     * School location latitude (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {number}
     * @memberof APISchoolAC23
     */
    latitude?: number;
    /**
     * School location longitude (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {number}
     * @memberof APISchoolAC23
     */
    longitude?: number;
    /**
     * Statewide rank of this School  (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {number}
     * @memberof APISchoolAC23
     */
    rank?: number;
    /**
     * Count of schools ranked at this state/level (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {number}
     * @memberof APISchoolAC23
     */
    rankOf?: number;
    /**
     * The number of stars SchoolDigger awarded in the ranking of the school (0-5, 5 is best) (Pro, Enterprise, and Autocomplete Pro levels only)
     * @type {number}
     * @memberof APISchoolAC23
     */
    rankStars?: number;
    /**
     * The NCES ID of the school (private schools only)
     * @type {string}
     * @memberof APISchoolAC23
     */
    ncesPrivateSchoolID?: string;
}

/**
 * Check if a given object implements the APISchoolAC23 interface.
 */
export function instanceOfAPISchoolAC23(value: object): value is APISchoolAC23 {
    return true;
}

export function APISchoolAC23FromJSON(json: any): APISchoolAC23 {
    return APISchoolAC23FromJSONTyped(json, false);
}

export function APISchoolAC23FromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolAC23 {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolid': json['schoolid'] == null ? undefined : json['schoolid'],
        'schoolName': json['schoolName'] == null ? undefined : json['schoolName'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zip': json['zip'] == null ? undefined : json['zip'],
        'schoolLevel': json['schoolLevel'] == null ? undefined : json['schoolLevel'],
        'lowGrade': json['lowGrade'] == null ? undefined : json['lowGrade'],
        'highGrade': json['highGrade'] == null ? undefined : json['highGrade'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'rankOf': json['rankOf'] == null ? undefined : json['rankOf'],
        'rankStars': json['rankStars'] == null ? undefined : json['rankStars'],
        'ncesPrivateSchoolID': json['ncesPrivateSchoolID'] == null ? undefined : json['ncesPrivateSchoolID'],
    };
}

export function APISchoolAC23ToJSON(json: any): APISchoolAC23 {
    return APISchoolAC23ToJSONTyped(json, false);
}

export function APISchoolAC23ToJSONTyped(value?: APISchoolAC23 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schoolid': value['schoolid'],
        'schoolName': value['schoolName'],
        'city': value['city'],
        'state': value['state'],
        'zip': value['zip'],
        'schoolLevel': value['schoolLevel'],
        'lowGrade': value['lowGrade'],
        'highGrade': value['highGrade'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'rank': value['rank'],
        'rankOf': value['rankOf'],
        'rankStars': value['rankStars'],
        'ncesPrivateSchoolID': value['ncesPrivateSchoolID'],
    };
}

