/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIRankHistory } from './APIRankHistory';
import {
    APIRankHistoryFromJSON,
    APIRankHistoryFromJSONTyped,
    APIRankHistoryToJSON,
    APIRankHistoryToJSONTyped,
} from './APIRankHistory';
import type { APIYearlyDemographics } from './APIYearlyDemographics';
import {
    APIYearlyDemographicsFromJSON,
    APIYearlyDemographicsFromJSONTyped,
    APIYearlyDemographicsToJSON,
    APIYearlyDemographicsToJSONTyped,
} from './APIYearlyDemographics';
import type { APICounty } from './APICounty';
import {
    APICountyFromJSON,
    APICountyFromJSONTyped,
    APICountyToJSON,
    APICountyToJSONTyped,
} from './APICounty';
import type { APIDistrictSum } from './APIDistrictSum';
import {
    APIDistrictSumFromJSON,
    APIDistrictSumFromJSONTyped,
    APIDistrictSumToJSON,
    APIDistrictSumToJSONTyped,
} from './APIDistrictSum';
import type { APILocation } from './APILocation';
import {
    APILocationFromJSON,
    APILocationFromJSONTyped,
    APILocationToJSON,
    APILocationToJSONTyped,
} from './APILocation';

/**
 * APISchool2Summary: A summary of a school record. For the full school record, call /schools/{id}
 * @export
 * @interface APISchoolSummary21
 */
export interface APISchoolSummary21 {
    /**
     * SchoolDigger School ID Number (12 digits)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    schoolid?: string;
    /**
     * School name
     * @type {string}
     * @memberof APISchoolSummary21
     */
    schoolName?: string;
    /**
     * School phone number
     * @type {string}
     * @memberof APISchoolSummary21
     */
    phone?: string;
    /**
     * SchoolDigger URL for this school
     * @type {string}
     * @memberof APISchoolSummary21
     */
    url?: string;
    /**
     * SchoolDigger URL for comparing this school to nearby schools
     * @type {string}
     * @memberof APISchoolSummary21
     */
    urlCompare?: string;
    /**
     * 
     * @type {APILocation}
     * @memberof APISchoolSummary21
     */
    address?: APILocation;
    /**
     * Distance from nearLatitude/nearLongitude, boundaryLatitude/boundaryLongitude, or boundaryAddress (if supplied)
     * @type {number}
     * @memberof APISchoolSummary21
     */
    distance?: number;
    /**
     * NCES urban-centric locale classification (e.g. 'City: Large', 'Suburb: Midsize', 'Rural: Fringe'). Categories: City (Large/Midsize/Small), Suburb (Large/Midsize/Small), Town (Fringe/Distant/Remote), Rural (Fringe/Distant/Remote). See https://nces.ed.gov/ccd/rural_locales.asp
     * @type {string}
     * @memberof APISchoolSummary21
     */
    locale?: string;
    /**
     * The low grade served by this school (PK = Prekindergarten, K = Kindergarten)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    lowGrade?: string;
    /**
     * The high grade served by this school
     * @type {string}
     * @memberof APISchoolSummary21
     */
    highGrade?: string;
    /**
     * The level of school (Elementary, Middle, High, Private, Alternative)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    schoolLevel?: string;
    /**
     * Indicates if school is a charter school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    isCharterSchool?: string;
    /**
     * Indicates if school is a magnet school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    isMagnetSchool?: string;
    /**
     * Indicates if school is a virtual school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    isVirtualSchool?: string;
    /**
     * Indicates if school is a Title I school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    isTitleISchool?: string;
    /**
     * Indicates if a school-wide Title I school (Yes/No/n-a)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    isTitleISchoolwideSchool?: string;
    /**
     * 
     * @type {APIDistrictSum}
     * @memberof APISchoolSummary21
     */
    district?: APIDistrictSum;
    /**
     * 
     * @type {APICounty}
     * @memberof APISchoolSummary21
     */
    county?: APICounty;
    /**
     * SchoolDigger yearly rank history of the school. To retrieve all years, call /schools/{id}.
     * @type {Array<APIRankHistory>}
     * @memberof APISchoolSummary21
     */
    rankHistory?: Array<APIRankHistory>;
    /**
     * Returns the movement of rank for this school between current and previous year
     * @type {number}
     * @memberof APISchoolSummary21
     */
    rankMovement?: number;
    /**
     * School Yearly metrics. To retrieve all years, call /schools/{id}.
     * @type {Array<APIYearlyDemographics>}
     * @memberof APISchoolSummary21
     */
    schoolYearlyDetails?: Array<APIYearlyDemographics>;
    /**
     * Indicates if school is a private school (Yes/No)
     * @type {boolean}
     * @memberof APISchoolSummary21
     */
    isPrivate?: boolean;
    /**
     * Days in the school year (private schools only)
     * @type {number}
     * @memberof APISchoolSummary21
     */
    privateDays?: number;
    /**
     * Hours in the school day (private schools only)
     * @type {number}
     * @memberof APISchoolSummary21
     */
    privateHours?: number;
    /**
     * Indicates if the school has a library (private schools only)
     * @type {boolean}
     * @memberof APISchoolSummary21
     */
    privateHasLibrary?: boolean;
    /**
     * Coed/Boys/Girls (private schools only)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    privateCoed?: string;
    /**
     * Affiliation of the school (private schools only)
     * @type {string}
     * @memberof APISchoolSummary21
     */
    privateOrientation?: string;
}

/**
 * Check if a given object implements the APISchoolSummary21 interface.
 */
export function instanceOfAPISchoolSummary21(value: object): value is APISchoolSummary21 {
    return true;
}

export function APISchoolSummary21FromJSON(json: any): APISchoolSummary21 {
    return APISchoolSummary21FromJSONTyped(json, false);
}

export function APISchoolSummary21FromJSONTyped(json: any, ignoreDiscriminator: boolean): APISchoolSummary21 {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolid': json['schoolid'] == null ? undefined : json['schoolid'],
        'schoolName': json['schoolName'] == null ? undefined : json['schoolName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'url': json['url'] == null ? undefined : json['url'],
        'urlCompare': json['urlCompare'] == null ? undefined : json['urlCompare'],
        'address': json['address'] == null ? undefined : APILocationFromJSON(json['address']),
        'distance': json['distance'] == null ? undefined : json['distance'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'lowGrade': json['lowGrade'] == null ? undefined : json['lowGrade'],
        'highGrade': json['highGrade'] == null ? undefined : json['highGrade'],
        'schoolLevel': json['schoolLevel'] == null ? undefined : json['schoolLevel'],
        'isCharterSchool': json['isCharterSchool'] == null ? undefined : json['isCharterSchool'],
        'isMagnetSchool': json['isMagnetSchool'] == null ? undefined : json['isMagnetSchool'],
        'isVirtualSchool': json['isVirtualSchool'] == null ? undefined : json['isVirtualSchool'],
        'isTitleISchool': json['isTitleISchool'] == null ? undefined : json['isTitleISchool'],
        'isTitleISchoolwideSchool': json['isTitleISchoolwideSchool'] == null ? undefined : json['isTitleISchoolwideSchool'],
        'district': json['district'] == null ? undefined : APIDistrictSumFromJSON(json['district']),
        'county': json['county'] == null ? undefined : APICountyFromJSON(json['county']),
        'rankHistory': json['rankHistory'] == null ? undefined : ((json['rankHistory'] as Array<any>).map(APIRankHistoryFromJSON)),
        'rankMovement': json['rankMovement'] == null ? undefined : json['rankMovement'],
        'schoolYearlyDetails': json['schoolYearlyDetails'] == null ? undefined : ((json['schoolYearlyDetails'] as Array<any>).map(APIYearlyDemographicsFromJSON)),
        'isPrivate': json['isPrivate'] == null ? undefined : json['isPrivate'],
        'privateDays': json['privateDays'] == null ? undefined : json['privateDays'],
        'privateHours': json['privateHours'] == null ? undefined : json['privateHours'],
        'privateHasLibrary': json['privateHasLibrary'] == null ? undefined : json['privateHasLibrary'],
        'privateCoed': json['privateCoed'] == null ? undefined : json['privateCoed'],
        'privateOrientation': json['privateOrientation'] == null ? undefined : json['privateOrientation'],
    };
}

export function APISchoolSummary21ToJSON(json: any): APISchoolSummary21 {
    return APISchoolSummary21ToJSONTyped(json, false);
}

export function APISchoolSummary21ToJSONTyped(value?: APISchoolSummary21 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schoolid': value['schoolid'],
        'schoolName': value['schoolName'],
        'phone': value['phone'],
        'url': value['url'],
        'urlCompare': value['urlCompare'],
        'address': APILocationToJSON(value['address']),
        'distance': value['distance'],
        'locale': value['locale'],
        'lowGrade': value['lowGrade'],
        'highGrade': value['highGrade'],
        'schoolLevel': value['schoolLevel'],
        'isCharterSchool': value['isCharterSchool'],
        'isMagnetSchool': value['isMagnetSchool'],
        'isVirtualSchool': value['isVirtualSchool'],
        'isTitleISchool': value['isTitleISchool'],
        'isTitleISchoolwideSchool': value['isTitleISchoolwideSchool'],
        'district': APIDistrictSumToJSON(value['district']),
        'county': APICountyToJSON(value['county']),
        'rankHistory': value['rankHistory'] == null ? undefined : ((value['rankHistory'] as Array<any>).map(APIRankHistoryToJSON)),
        'rankMovement': value['rankMovement'],
        'schoolYearlyDetails': value['schoolYearlyDetails'] == null ? undefined : ((value['schoolYearlyDetails'] as Array<any>).map(APIYearlyDemographicsToJSON)),
        'isPrivate': value['isPrivate'],
        'privateDays': value['privateDays'],
        'privateHours': value['privateHours'],
        'privateHasLibrary': value['privateHasLibrary'],
        'privateCoed': value['privateCoed'],
        'privateOrientation': value['privateOrientation'],
    };
}

