/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v3.0
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { APIReportedPercent } from './APIReportedPercent';
import {
    instanceOfAPIReportedPercent,
    APIReportedPercentFromJSON,
    APIReportedPercentFromJSONTyped,
    APIReportedPercentToJSON,
} from './APIReportedPercent';

/**
 * @type APITestScore30PercentTier3
 * Percent of students performing at tier 3 (Enterprise API level only): a number when exact, otherwise an APIReportedPercent object. Absent when not reported.
 * @export
 */
export type APITestScore30PercentTier3 = APIReportedPercent | number;

export function APITestScore30PercentTier3FromJSON(json: any): APITestScore30PercentTier3 {
    return APITestScore30PercentTier3FromJSONTyped(json, false);
}

export function APITestScore30PercentTier3FromJSONTyped(json: any, ignoreDiscriminator: boolean): APITestScore30PercentTier3 {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAPIReportedPercent(json)) {
        return APIReportedPercentFromJSONTyped(json, true);
    }
    if (typeof json === 'number') {
        return json;
    }
    return {} as any;
}

export function APITestScore30PercentTier3ToJSON(json: any): any {
    return APITestScore30PercentTier3ToJSONTyped(json, false);
}

export function APITestScore30PercentTier3ToJSONTyped(value?: APITestScore30PercentTier3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAPIReportedPercent(value)) {
        return APIReportedPercentToJSON(value as APIReportedPercent);
    }
    if (typeof value === 'number') {
        return value;
    }
    return {};
}

