/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v3.0
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APITestScore30PercentTier4 } from './APITestScore30PercentTier4';
import {
    APITestScore30PercentTier4FromJSON,
    APITestScore30PercentTier4FromJSONTyped,
    APITestScore30PercentTier4ToJSON,
    APITestScore30PercentTier4ToJSONTyped,
} from './APITestScore30PercentTier4';
import type { APITestScore30PercentTier5 } from './APITestScore30PercentTier5';
import {
    APITestScore30PercentTier5FromJSON,
    APITestScore30PercentTier5FromJSONTyped,
    APITestScore30PercentTier5ToJSON,
    APITestScore30PercentTier5ToJSONTyped,
} from './APITestScore30PercentTier5';
import type { APITestScore30PercentMetStandard } from './APITestScore30PercentMetStandard';
import {
    APITestScore30PercentMetStandardFromJSON,
    APITestScore30PercentMetStandardFromJSONTyped,
    APITestScore30PercentMetStandardToJSON,
    APITestScore30PercentMetStandardToJSONTyped,
} from './APITestScore30PercentMetStandard';
import type { APITestScore30PercentTier2 } from './APITestScore30PercentTier2';
import {
    APITestScore30PercentTier2FromJSON,
    APITestScore30PercentTier2FromJSONTyped,
    APITestScore30PercentTier2ToJSON,
    APITestScore30PercentTier2ToJSONTyped,
} from './APITestScore30PercentTier2';
import type { APITestScore30PercentTier3 } from './APITestScore30PercentTier3';
import {
    APITestScore30PercentTier3FromJSON,
    APITestScore30PercentTier3FromJSONTyped,
    APITestScore30PercentTier3ToJSON,
    APITestScore30PercentTier3ToJSONTyped,
} from './APITestScore30PercentTier3';
import type { APITestScore30PercentTier1 } from './APITestScore30PercentTier1';
import {
    APITestScore30PercentTier1FromJSON,
    APITestScore30PercentTier1FromJSONTyped,
    APITestScore30PercentTier1ToJSON,
    APITestScore30PercentTier1ToJSONTyped,
} from './APITestScore30PercentTier1';

/**
 * One test result (school, district or state level) as returned by API 3.0. Same members as the 2.4 object except
 * that the six percent metrics are either a plain number or an APIReportedPercent object (see that class), and a
 * score object is returned whenever the state reported anything - including a result that consists only of
 * suppressed or ranged values. Hand-written (not inherited from clsSD2testScore) because the number-or-object
 * union cannot come from the reflection copy the 2.4 models use.
 * @export
 * @interface APITestScore30
 */
export interface APITestScore30 {
    /**
     * Count of students eligible to take test
     * @type {number}
     * @memberof APITestScore30
     */
    studentsEligible?: number;
    /**
     * Count of students tested
     * @type {number}
     * @memberof APITestScore30
     */
    studentsTested?: number;
    /**
     * Mean scale score
     * @type {number}
     * @memberof APITestScore30
     */
    meanScaledScore?: number;
    /**
     * 
     * @type {APITestScore30PercentMetStandard}
     * @memberof APITestScore30
     */
    percentMetStandard?: APITestScore30PercentMetStandard;
    /**
     * Count of students meeting state standard
     * @type {number}
     * @memberof APITestScore30
     */
    numberMetStandard?: number;
    /**
     * Count of students performing at tier 1 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore30
     */
    numTier1?: number;
    /**
     * Count of students performing at tier 2 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore30
     */
    numTier2?: number;
    /**
     * Count of students performing at tier 3 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore30
     */
    numTier3?: number;
    /**
     * Count of students performing at tier 4 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore30
     */
    numTier4?: number;
    /**
     * Count of students performing at tier 5 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore30
     */
    numTier5?: number;
    /**
     * 
     * @type {APITestScore30PercentTier1}
     * @memberof APITestScore30
     */
    percentTier1?: APITestScore30PercentTier1;
    /**
     * 
     * @type {APITestScore30PercentTier2}
     * @memberof APITestScore30
     */
    percentTier2?: APITestScore30PercentTier2;
    /**
     * 
     * @type {APITestScore30PercentTier3}
     * @memberof APITestScore30
     */
    percentTier3?: APITestScore30PercentTier3;
    /**
     * 
     * @type {APITestScore30PercentTier4}
     * @memberof APITestScore30
     */
    percentTier4?: APITestScore30PercentTier4;
    /**
     * 
     * @type {APITestScore30PercentTier5}
     * @memberof APITestScore30
     */
    percentTier5?: APITestScore30PercentTier5;
}

/**
 * Check if a given object implements the APITestScore30 interface.
 */
export function instanceOfAPITestScore30(value: object): value is APITestScore30 {
    return true;
}

export function APITestScore30FromJSON(json: any): APITestScore30 {
    return APITestScore30FromJSONTyped(json, false);
}

export function APITestScore30FromJSONTyped(json: any, ignoreDiscriminator: boolean): APITestScore30 {
    if (json == null) {
        return json;
    }
    return {
        
        'studentsEligible': json['studentsEligible'] == null ? undefined : json['studentsEligible'],
        'studentsTested': json['studentsTested'] == null ? undefined : json['studentsTested'],
        'meanScaledScore': json['meanScaledScore'] == null ? undefined : json['meanScaledScore'],
        'percentMetStandard': json['percentMetStandard'] == null ? undefined : APITestScore30PercentMetStandardFromJSON(json['percentMetStandard']),
        'numberMetStandard': json['numberMetStandard'] == null ? undefined : json['numberMetStandard'],
        'numTier1': json['numTier1'] == null ? undefined : json['numTier1'],
        'numTier2': json['numTier2'] == null ? undefined : json['numTier2'],
        'numTier3': json['numTier3'] == null ? undefined : json['numTier3'],
        'numTier4': json['numTier4'] == null ? undefined : json['numTier4'],
        'numTier5': json['numTier5'] == null ? undefined : json['numTier5'],
        'percentTier1': json['percentTier1'] == null ? undefined : APITestScore30PercentTier1FromJSON(json['percentTier1']),
        'percentTier2': json['percentTier2'] == null ? undefined : APITestScore30PercentTier2FromJSON(json['percentTier2']),
        'percentTier3': json['percentTier3'] == null ? undefined : APITestScore30PercentTier3FromJSON(json['percentTier3']),
        'percentTier4': json['percentTier4'] == null ? undefined : APITestScore30PercentTier4FromJSON(json['percentTier4']),
        'percentTier5': json['percentTier5'] == null ? undefined : APITestScore30PercentTier5FromJSON(json['percentTier5']),
    };
}

export function APITestScore30ToJSON(json: any): APITestScore30 {
    return APITestScore30ToJSONTyped(json, false);
}

export function APITestScore30ToJSONTyped(value?: APITestScore30 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentsEligible': value['studentsEligible'],
        'studentsTested': value['studentsTested'],
        'meanScaledScore': value['meanScaledScore'],
        'percentMetStandard': APITestScore30PercentMetStandardToJSON(value['percentMetStandard']),
        'numberMetStandard': value['numberMetStandard'],
        'numTier1': value['numTier1'],
        'numTier2': value['numTier2'],
        'numTier3': value['numTier3'],
        'numTier4': value['numTier4'],
        'numTier5': value['numTier5'],
        'percentTier1': APITestScore30PercentTier1ToJSON(value['percentTier1']),
        'percentTier2': APITestScore30PercentTier2ToJSON(value['percentTier2']),
        'percentTier3': APITestScore30PercentTier3ToJSON(value['percentTier3']),
        'percentTier4': APITestScore30PercentTier4ToJSON(value['percentTier4']),
        'percentTier5': APITestScore30PercentTier5ToJSON(value['percentTier5']),
    };
}

