/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v3.0
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APITestScore30 } from './APITestScore30';
import {
    APITestScore30FromJSON,
    APITestScore30FromJSONTyped,
    APITestScore30ToJSON,
    APITestScore30ToJSONTyped,
} from './APITestScore30';

/**
 * One test / subject / grade / year entry as returned by API 3.0, with school, district and state APITestScore30
 * objects. Unlike API 2.4 (APITestScoreWrapper) it does not hide rows the pre-2026 importer would not have
 * produced (spec R0 Invariant 2): a score object is present whenever the state reported anything for that level,
 * and the entry is present whenever at least one score object is.
 * @export
 * @interface APITestScoreWrapper30
 */
export interface APITestScoreWrapper30 {
    /**
     * The name of the state-administered test
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    test?: string;
    /**
     * Test subject
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    subject?: string;
    /**
     * Year test was administered (2018 = 2017-18)
     * @type {number}
     * @memberof APITestScoreWrapper30
     */
    year?: number;
    /**
     * Grade level for which this test score applies (e.g. '3', '5', '8', '10', 'HS')
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    grade?: string;
    /**
     * 
     * @type {APITestScore30}
     * @memberof APITestScoreWrapper30
     */
    schoolTestScore?: APITestScore30;
    /**
     * 
     * @type {APITestScore30}
     * @memberof APITestScoreWrapper30
     */
    districtTestScore?: APITestScore30;
    /**
     * 
     * @type {APITestScore30}
     * @memberof APITestScoreWrapper30
     */
    stateTestScore?: APITestScore30;
    /**
     * Label for the lowest performance tier on this test (e.g. 'Below Basic', 'Level 1'). Tier labels are state-specific. Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    tier1?: string;
    /**
     * Label for the second performance tier (e.g. 'Basic', 'Level 2'). Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    tier2?: string;
    /**
     * Label for the third performance tier (e.g. 'Proficient', 'Level 3'). Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    tier3?: string;
    /**
     * Label for the fourth performance tier (e.g. 'Advanced', 'Level 4'). Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    tier4?: string;
    /**
     * Label for the fifth performance tier, if applicable (e.g. 'No Score'). Not all states use 5 tiers. Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper30
     */
    tier5?: string;
}

/**
 * Check if a given object implements the APITestScoreWrapper30 interface.
 */
export function instanceOfAPITestScoreWrapper30(value: object): value is APITestScoreWrapper30 {
    return true;
}

export function APITestScoreWrapper30FromJSON(json: any): APITestScoreWrapper30 {
    return APITestScoreWrapper30FromJSONTyped(json, false);
}

export function APITestScoreWrapper30FromJSONTyped(json: any, ignoreDiscriminator: boolean): APITestScoreWrapper30 {
    if (json == null) {
        return json;
    }
    return {
        
        'test': json['test'] == null ? undefined : json['test'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'year': json['year'] == null ? undefined : json['year'],
        'grade': json['grade'] == null ? undefined : json['grade'],
        'schoolTestScore': json['schoolTestScore'] == null ? undefined : APITestScore30FromJSON(json['schoolTestScore']),
        'districtTestScore': json['districtTestScore'] == null ? undefined : APITestScore30FromJSON(json['districtTestScore']),
        'stateTestScore': json['stateTestScore'] == null ? undefined : APITestScore30FromJSON(json['stateTestScore']),
        'tier1': json['tier1'] == null ? undefined : json['tier1'],
        'tier2': json['tier2'] == null ? undefined : json['tier2'],
        'tier3': json['tier3'] == null ? undefined : json['tier3'],
        'tier4': json['tier4'] == null ? undefined : json['tier4'],
        'tier5': json['tier5'] == null ? undefined : json['tier5'],
    };
}

export function APITestScoreWrapper30ToJSON(json: any): APITestScoreWrapper30 {
    return APITestScoreWrapper30ToJSONTyped(json, false);
}

export function APITestScoreWrapper30ToJSONTyped(value?: APITestScoreWrapper30 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'test': value['test'],
        'subject': value['subject'],
        'year': value['year'],
        'grade': value['grade'],
        'schoolTestScore': APITestScore30ToJSON(value['schoolTestScore']),
        'districtTestScore': APITestScore30ToJSON(value['districtTestScore']),
        'stateTestScore': APITestScore30ToJSON(value['stateTestScore']),
        'tier1': value['tier1'],
        'tier2': value['tier2'],
        'tier3': value['tier3'],
        'tier4': value['tier4'],
        'tier5': value['tier5'],
    };
}

