/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APITestScore } from './APITestScore';
import {
    APITestScoreFromJSON,
    APITestScoreFromJSONTyped,
    APITestScoreToJSON,
    APITestScoreToJSONTyped,
} from './APITestScore';

/**
 * 
 * @export
 * @interface APITestScoreWrapper
 */
export interface APITestScoreWrapper {
    /**
     * The name of the state-administered test
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    test?: string;
    /**
     * Test subject
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    subject?: string;
    /**
     * Year test was administered (2018 = 2017-18)
     * @type {number}
     * @memberof APITestScoreWrapper
     */
    year?: number;
    /**
     * Grade level for which this test score applies (e.g. '3', '5', '8', '10', 'HS')
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    grade?: string;
    /**
     * 
     * @type {APITestScore}
     * @memberof APITestScoreWrapper
     */
    schoolTestScore?: APITestScore;
    /**
     * 
     * @type {APITestScore}
     * @memberof APITestScoreWrapper
     */
    districtTestScore?: APITestScore;
    /**
     * 
     * @type {APITestScore}
     * @memberof APITestScoreWrapper
     */
    stateTestScore?: APITestScore;
    /**
     * Label for the lowest performance tier on this test (e.g. 'Below Basic', 'Level 1'). Tier labels are state-specific. Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    tier1?: string;
    /**
     * Label for the second performance tier (e.g. 'Basic', 'Level 2'). Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    tier2?: string;
    /**
     * Label for the third performance tier (e.g. 'Proficient', 'Level 3'). Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    tier3?: string;
    /**
     * Label for the fourth performance tier (e.g. 'Advanced', 'Level 4'). Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    tier4?: string;
    /**
     * Label for the fifth performance tier, if applicable (e.g. 'No Score'). Not all states use 5 tiers. Enterprise API level only.
     * @type {string}
     * @memberof APITestScoreWrapper
     */
    tier5?: string;
}

/**
 * Check if a given object implements the APITestScoreWrapper interface.
 */
export function instanceOfAPITestScoreWrapper(value: object): value is APITestScoreWrapper {
    return true;
}

export function APITestScoreWrapperFromJSON(json: any): APITestScoreWrapper {
    return APITestScoreWrapperFromJSONTyped(json, false);
}

export function APITestScoreWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): APITestScoreWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'test': json['test'] == null ? undefined : json['test'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'year': json['year'] == null ? undefined : json['year'],
        'grade': json['grade'] == null ? undefined : json['grade'],
        'schoolTestScore': json['schoolTestScore'] == null ? undefined : APITestScoreFromJSON(json['schoolTestScore']),
        'districtTestScore': json['districtTestScore'] == null ? undefined : APITestScoreFromJSON(json['districtTestScore']),
        'stateTestScore': json['stateTestScore'] == null ? undefined : APITestScoreFromJSON(json['stateTestScore']),
        'tier1': json['tier1'] == null ? undefined : json['tier1'],
        'tier2': json['tier2'] == null ? undefined : json['tier2'],
        'tier3': json['tier3'] == null ? undefined : json['tier3'],
        'tier4': json['tier4'] == null ? undefined : json['tier4'],
        'tier5': json['tier5'] == null ? undefined : json['tier5'],
    };
}

export function APITestScoreWrapperToJSON(json: any): APITestScoreWrapper {
    return APITestScoreWrapperToJSONTyped(json, false);
}

export function APITestScoreWrapperToJSONTyped(value?: APITestScoreWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'test': value['test'],
        'subject': value['subject'],
        'year': value['year'],
        'grade': value['grade'],
        'schoolTestScore': APITestScoreToJSON(value['schoolTestScore']),
        'districtTestScore': APITestScoreToJSON(value['districtTestScore']),
        'stateTestScore': APITestScoreToJSON(value['stateTestScore']),
        'tier1': value['tier1'],
        'tier2': value['tier2'],
        'tier3': value['tier3'],
        'tier4': value['tier4'],
        'tier5': value['tier5'],
    };
}

