/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APITestScore
 */
export interface APITestScore {
    /**
     * Count of students eligible to take test
     * @type {number}
     * @memberof APITestScore
     */
    studentsEligible?: number;
    /**
     * Count of students tested
     * @type {number}
     * @memberof APITestScore
     */
    studentsTested?: number;
    /**
     * Mean scale score
     * @type {number}
     * @memberof APITestScore
     */
    meanScaledScore?: number;
    /**
     * Percent of students meeting state standard
     * @type {number}
     * @memberof APITestScore
     */
    percentMetStandard?: number;
    /**
     * Count of students meeting state standard
     * @type {number}
     * @memberof APITestScore
     */
    numberMetStandard?: number;
    /**
     * Count of students performing at tier 1 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    numTier1?: number;
    /**
     * Count of students performing at tier 2 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    numTier2?: number;
    /**
     * Count of students performing at tier 3 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    numTier3?: number;
    /**
     * Count of students performing at tier 4 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    numTier4?: number;
    /**
     * Count of students performing at tier 5 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    numTier5?: number;
    /**
     * Percent of students performing at tier 1 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    percentTier1?: number;
    /**
     * Percent of students performing at tier 2 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    percentTier2?: number;
    /**
     * Percent of students performing at tier 3 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    percentTier3?: number;
    /**
     * Percent of students performing at tier 4 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    percentTier4?: number;
    /**
     * Percent of students performing at tier 5 (Enterprise API level only)
     * @type {number}
     * @memberof APITestScore
     */
    percentTier5?: number;
}

/**
 * Check if a given object implements the APITestScore interface.
 */
export function instanceOfAPITestScore(value: object): value is APITestScore {
    return true;
}

export function APITestScoreFromJSON(json: any): APITestScore {
    return APITestScoreFromJSONTyped(json, false);
}

export function APITestScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): APITestScore {
    if (json == null) {
        return json;
    }
    return {
        
        'studentsEligible': json['studentsEligible'] == null ? undefined : json['studentsEligible'],
        'studentsTested': json['studentsTested'] == null ? undefined : json['studentsTested'],
        'meanScaledScore': json['meanScaledScore'] == null ? undefined : json['meanScaledScore'],
        'percentMetStandard': json['percentMetStandard'] == null ? undefined : json['percentMetStandard'],
        'numberMetStandard': json['numberMetStandard'] == null ? undefined : json['numberMetStandard'],
        'numTier1': json['numTier1'] == null ? undefined : json['numTier1'],
        'numTier2': json['numTier2'] == null ? undefined : json['numTier2'],
        'numTier3': json['numTier3'] == null ? undefined : json['numTier3'],
        'numTier4': json['numTier4'] == null ? undefined : json['numTier4'],
        'numTier5': json['numTier5'] == null ? undefined : json['numTier5'],
        'percentTier1': json['percentTier1'] == null ? undefined : json['percentTier1'],
        'percentTier2': json['percentTier2'] == null ? undefined : json['percentTier2'],
        'percentTier3': json['percentTier3'] == null ? undefined : json['percentTier3'],
        'percentTier4': json['percentTier4'] == null ? undefined : json['percentTier4'],
        'percentTier5': json['percentTier5'] == null ? undefined : json['percentTier5'],
    };
}

export function APITestScoreToJSON(json: any): APITestScore {
    return APITestScoreToJSONTyped(json, false);
}

export function APITestScoreToJSONTyped(value?: APITestScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentsEligible': value['studentsEligible'],
        'studentsTested': value['studentsTested'],
        'meanScaledScore': value['meanScaledScore'],
        'percentMetStandard': value['percentMetStandard'],
        'numberMetStandard': value['numberMetStandard'],
        'numTier1': value['numTier1'],
        'numTier2': value['numTier2'],
        'numTier3': value['numTier3'],
        'numTier4': value['numTier4'],
        'numTier5': value['numTier5'],
        'percentTier1': value['percentTier1'],
        'percentTier2': value['percentTier2'],
        'percentTier3': value['percentTier3'],
        'percentTier4': value['percentTier4'],
        'percentTier5': value['percentTier5'],
    };
}

