/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v3.0
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { APIReportedPercent } from './APIReportedPercent';
import {
    instanceOfAPIReportedPercent,
    APIReportedPercentFromJSON,
    APIReportedPercentFromJSONTyped,
    APIReportedPercentToJSON,
} from './APIReportedPercent';

/**
 * @type APITestScore30PercentMetStandard
 * Percent of students meeting state standard: a number when the state reported an exact value, otherwise an APIReportedPercent object (range, suppressed, legacyImputed or derived). Absent when not reported.
 * @export
 */
export type APITestScore30PercentMetStandard = APIReportedPercent | number;

export function APITestScore30PercentMetStandardFromJSON(json: any): APITestScore30PercentMetStandard {
    return APITestScore30PercentMetStandardFromJSONTyped(json, false);
}

export function APITestScore30PercentMetStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): APITestScore30PercentMetStandard {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAPIReportedPercent(json)) {
        return APIReportedPercentFromJSONTyped(json, true);
    }
    if (typeof json === 'number') {
        return json;
    }
    return {} as any;
}

export function APITestScore30PercentMetStandardToJSON(json: any): any {
    return APITestScore30PercentMetStandardToJSONTyped(json, false);
}

export function APITestScore30PercentMetStandardToJSONTyped(value?: APITestScore30PercentMetStandard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAPIReportedPercent(value)) {
        return APIReportedPercentToJSON(value as APIReportedPercent);
    }
    if (typeof value === 'number') {
        return value;
    }
    return {};
}

