/* tslint:disable */
/* eslint-disable */
/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIYearlyDemographics
 */
export interface APIYearlyDemographics {
    /**
     * School year (2018 = 2017-18)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    year?: number;
    /**
     * Count of students attending the school
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberOfStudents?: number;
    /**
     * Percent of students receiving a free or discounted lunch in the National School Lunch Program
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentFreeDiscLunch?: number;
    /**
     * Percentage of students who are Black or African American (NCES definition: a person having origins in any of the black racial groups of Africa)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofAfricanAmericanStudents?: number;
    /**
     * Percentage of students who are Asian (NCES definition: a person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofAsianStudents?: number;
    /**
     * Percentage of students who are Hispanic or Latino (NCES definition: a person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin, regardless of race)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofHispanicStudents?: number;
    /**
     * Percentage of students who are American Indian or Alaska Native (NCES definition: a person having origins in any of the original peoples of North and South America who maintains tribal affiliation or community attachment)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofIndianStudents?: number;
    /**
     * Percentage of students who are Native Hawaiian or Other Pacific Islander (NCES definition: a person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofPacificIslanderStudents?: number;
    /**
     * Percentage of students who are White (NCES definition: a person having origins in any of the original peoples of Europe, the Middle East, or North Africa)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofWhiteStudents?: number;
    /**
     * Percentage of students reporting two or more races (not Hispanic/Latino)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofTwoOrMoreRaceStudents?: number;
    /**
     * Percentage of students whose race/ethnicity was not specified or reported
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    percentofUnspecifiedRaceStudents?: number;
    /**
     * Number of full-time equivalent teachers employed at the school
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    teachersFulltime?: number;
    /**
     * Number of students / number of full-time equivalent teachers
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    pupilTeacherRatio?: number;
    /**
     * NCES definition: A person having origins in any of the black racial groups of Africa.  (https://nces.ed.gov/statprog/2002/std1_5.asp)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofAfricanAmericanStudents?: number;
    /**
     * NCES definition: A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent, including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam.  (https://nces.ed.gov/statprog/2002/std1_5.asp)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofAsianStudents?: number;
    /**
     * NCES definition: A person of Cuban, Mexican, Puerto Rican, South or Central American, or other Spanish culture or origin, regardless of race. (https://nces.ed.gov/statprog/2002/std1_5.asp)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofHispanicStudents?: number;
    /**
     * Count of American Indian or Alaska Native students (NCES definition: a person having origins in any of the original peoples of North and South America who maintains tribal affiliation or community attachment)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofIndianStudents?: number;
    /**
     * NCES definition: A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands. (https://nces.ed.gov/statprog/2002/std1_5.asp)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofPacificIslanderStudents?: number;
    /**
     * NCES definition: A person having origins in any of the original peoples of Europe, the Middle East, or North Africa. (https://nces.ed.gov/statprog/2002/std1_5.asp)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofWhiteStudents?: number;
    /**
     * NCES definition: Includes any combination of two or more races and not Hispanic/Latino ethnicity. (https://nces.ed.gov/statprog/2002/std1_5.asp)
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofTwoOrMoreRaceStudents?: number;
    /**
     * Count of students whose race/ethnicity was not specified or reported
     * @type {number}
     * @memberof APIYearlyDemographics
     */
    numberofUnspecifiedRaceStudents?: number;
}

/**
 * Check if a given object implements the APIYearlyDemographics interface.
 */
export function instanceOfAPIYearlyDemographics(value: object): value is APIYearlyDemographics {
    return true;
}

export function APIYearlyDemographicsFromJSON(json: any): APIYearlyDemographics {
    return APIYearlyDemographicsFromJSONTyped(json, false);
}

export function APIYearlyDemographicsFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIYearlyDemographics {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'numberOfStudents': json['numberOfStudents'] == null ? undefined : json['numberOfStudents'],
        'percentFreeDiscLunch': json['percentFreeDiscLunch'] == null ? undefined : json['percentFreeDiscLunch'],
        'percentofAfricanAmericanStudents': json['percentofAfricanAmericanStudents'] == null ? undefined : json['percentofAfricanAmericanStudents'],
        'percentofAsianStudents': json['percentofAsianStudents'] == null ? undefined : json['percentofAsianStudents'],
        'percentofHispanicStudents': json['percentofHispanicStudents'] == null ? undefined : json['percentofHispanicStudents'],
        'percentofIndianStudents': json['percentofIndianStudents'] == null ? undefined : json['percentofIndianStudents'],
        'percentofPacificIslanderStudents': json['percentofPacificIslanderStudents'] == null ? undefined : json['percentofPacificIslanderStudents'],
        'percentofWhiteStudents': json['percentofWhiteStudents'] == null ? undefined : json['percentofWhiteStudents'],
        'percentofTwoOrMoreRaceStudents': json['percentofTwoOrMoreRaceStudents'] == null ? undefined : json['percentofTwoOrMoreRaceStudents'],
        'percentofUnspecifiedRaceStudents': json['percentofUnspecifiedRaceStudents'] == null ? undefined : json['percentofUnspecifiedRaceStudents'],
        'teachersFulltime': json['teachersFulltime'] == null ? undefined : json['teachersFulltime'],
        'pupilTeacherRatio': json['pupilTeacherRatio'] == null ? undefined : json['pupilTeacherRatio'],
        'numberofAfricanAmericanStudents': json['numberofAfricanAmericanStudents'] == null ? undefined : json['numberofAfricanAmericanStudents'],
        'numberofAsianStudents': json['numberofAsianStudents'] == null ? undefined : json['numberofAsianStudents'],
        'numberofHispanicStudents': json['numberofHispanicStudents'] == null ? undefined : json['numberofHispanicStudents'],
        'numberofIndianStudents': json['numberofIndianStudents'] == null ? undefined : json['numberofIndianStudents'],
        'numberofPacificIslanderStudents': json['numberofPacificIslanderStudents'] == null ? undefined : json['numberofPacificIslanderStudents'],
        'numberofWhiteStudents': json['numberofWhiteStudents'] == null ? undefined : json['numberofWhiteStudents'],
        'numberofTwoOrMoreRaceStudents': json['numberofTwoOrMoreRaceStudents'] == null ? undefined : json['numberofTwoOrMoreRaceStudents'],
        'numberofUnspecifiedRaceStudents': json['numberofUnspecifiedRaceStudents'] == null ? undefined : json['numberofUnspecifiedRaceStudents'],
    };
}

export function APIYearlyDemographicsToJSON(json: any): APIYearlyDemographics {
    return APIYearlyDemographicsToJSONTyped(json, false);
}

export function APIYearlyDemographicsToJSONTyped(value?: APIYearlyDemographics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'numberOfStudents': value['numberOfStudents'],
        'percentFreeDiscLunch': value['percentFreeDiscLunch'],
        'percentofAfricanAmericanStudents': value['percentofAfricanAmericanStudents'],
        'percentofAsianStudents': value['percentofAsianStudents'],
        'percentofHispanicStudents': value['percentofHispanicStudents'],
        'percentofIndianStudents': value['percentofIndianStudents'],
        'percentofPacificIslanderStudents': value['percentofPacificIslanderStudents'],
        'percentofWhiteStudents': value['percentofWhiteStudents'],
        'percentofTwoOrMoreRaceStudents': value['percentofTwoOrMoreRaceStudents'],
        'percentofUnspecifiedRaceStudents': value['percentofUnspecifiedRaceStudents'],
        'teachersFulltime': value['teachersFulltime'],
        'pupilTeacherRatio': value['pupilTeacherRatio'],
        'numberofAfricanAmericanStudents': value['numberofAfricanAmericanStudents'],
        'numberofAsianStudents': value['numberofAsianStudents'],
        'numberofHispanicStudents': value['numberofHispanicStudents'],
        'numberofIndianStudents': value['numberofIndianStudents'],
        'numberofPacificIslanderStudents': value['numberofPacificIslanderStudents'],
        'numberofWhiteStudents': value['numberofWhiteStudents'],
        'numberofTwoOrMoreRaceStudents': value['numberofTwoOrMoreRaceStudents'],
        'numberofUnspecifiedRaceStudents': value['numberofUnspecifiedRaceStudents'],
    };
}

