/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { APIAutocompleteDistrictResult } from '../model/aPIAutocompleteDistrictResult';
import { APIAutocompleteSchoolResult23 } from '../model/aPIAutocompleteSchoolResult23';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.schooldigger.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AutocompleteApiApiKeys {
    appID,
    appKey,
}

export class AutocompleteApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'appID': new ApiKeyAuth('query', 'appID'),
        'appKey': new ApiKeyAuth('query', 'appKey'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AutocompleteApiApiKeys, value: string) {
        (this.authentications as any)[AutocompleteApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * 
     * @summary Returns a simple and quick list of districts for use in a client-typed autocomplete
     * @param q Search term for autocomplete (e.g. \&#39;Lincol\&#39;) (required)
     * @param st Two character state (e.g. \&#39;CA\&#39;) (optional -- leave blank to search entire U.S.)
     * @param boxLatitudeNW Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
     * @param boxLongitudeNW Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
     * @param boxLatitudeSE Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
     * @param boxLongitudeSE Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
     * @param returnCount Number of districts to return. Valid values: 1-20. (default: 10)
     */
    public async autocompleteDistricts (q?: string, st?: string, boxLatitudeNW?: number, boxLongitudeNW?: number, boxLatitudeSE?: number, boxLongitudeSE?: number, returnCount?: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: APIAutocompleteDistrictResult;  }> {
        const localVarPath = this.basePath + '/v2.3/autocomplete/districts';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        if (q !== undefined) {
            localVarQueryParameters['q'] = ObjectSerializer.serialize(q, "string");
        }

        if (st !== undefined) {
            localVarQueryParameters['st'] = ObjectSerializer.serialize(st, "string");
        }

        if (boxLatitudeNW !== undefined) {
            localVarQueryParameters['boxLatitudeNW'] = ObjectSerializer.serialize(boxLatitudeNW, "number");
        }

        if (boxLongitudeNW !== undefined) {
            localVarQueryParameters['boxLongitudeNW'] = ObjectSerializer.serialize(boxLongitudeNW, "number");
        }

        if (boxLatitudeSE !== undefined) {
            localVarQueryParameters['boxLatitudeSE'] = ObjectSerializer.serialize(boxLatitudeSE, "number");
        }

        if (boxLongitudeSE !== undefined) {
            localVarQueryParameters['boxLongitudeSE'] = ObjectSerializer.serialize(boxLongitudeSE, "number");
        }

        if (returnCount !== undefined) {
            localVarQueryParameters['returnCount'] = ObjectSerializer.serialize(returnCount, "number");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.appID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.appKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: APIAutocompleteDistrictResult;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "APIAutocompleteDistrictResult");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Returns a simple and quick list of schools for use in a client-typed autocomplete
     * @param q Search term for autocomplete (e.g. \&#39;Lincol\&#39;) (required)
     * @param qSearchCityStateName Extend the search term to include city and state (e.g. \&#39;Lincoln el paso\&#39; matches Lincoln Middle School in El Paso) (optional)
     * @param st Two character state (e.g. \&#39;CA\&#39;) (optional -- leave blank to search entire U.S.)
     * @param level Search for schools at this level only. Valid values: \&#39;Elementary\&#39;, \&#39;Middle\&#39;, \&#39;High\&#39;, \&#39;Alt\&#39;, \&#39;Private\&#39; (optional - leave blank to search for all schools)
     * @param districtID Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
     * @param boxLatitudeNW Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
     * @param boxLongitudeNW Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
     * @param boxLatitudeSE Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
     * @param boxLongitudeSE Search within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
     * @param returnCount Number of schools to return. Valid values: 1-20. (default: 10)
     */
    public async autocompleteSchools (q?: string, qSearchCityStateName?: boolean, st?: string, level?: string, districtID?: string, boxLatitudeNW?: number, boxLongitudeNW?: number, boxLatitudeSE?: number, boxLongitudeSE?: number, returnCount?: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: APIAutocompleteSchoolResult23;  }> {
        const localVarPath = this.basePath + '/v2.3/autocomplete/schools';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        if (q !== undefined) {
            localVarQueryParameters['q'] = ObjectSerializer.serialize(q, "string");
        }

        if (qSearchCityStateName !== undefined) {
            localVarQueryParameters['qSearchCityStateName'] = ObjectSerializer.serialize(qSearchCityStateName, "boolean");
        }

        if (st !== undefined) {
            localVarQueryParameters['st'] = ObjectSerializer.serialize(st, "string");
        }

        if (level !== undefined) {
            localVarQueryParameters['level'] = ObjectSerializer.serialize(level, "string");
        }

        if (districtID !== undefined) {
            localVarQueryParameters['districtID'] = ObjectSerializer.serialize(districtID, "string");
        }

        if (boxLatitudeNW !== undefined) {
            localVarQueryParameters['boxLatitudeNW'] = ObjectSerializer.serialize(boxLatitudeNW, "number");
        }

        if (boxLongitudeNW !== undefined) {
            localVarQueryParameters['boxLongitudeNW'] = ObjectSerializer.serialize(boxLongitudeNW, "number");
        }

        if (boxLatitudeSE !== undefined) {
            localVarQueryParameters['boxLatitudeSE'] = ObjectSerializer.serialize(boxLatitudeSE, "number");
        }

        if (boxLongitudeSE !== undefined) {
            localVarQueryParameters['boxLongitudeSE'] = ObjectSerializer.serialize(boxLongitudeSE, "number");
        }

        if (returnCount !== undefined) {
            localVarQueryParameters['returnCount'] = ObjectSerializer.serialize(returnCount, "number");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.appID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.appKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: APIAutocompleteSchoolResult23;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "APIAutocompleteSchoolResult23");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
