/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { APIDistrictFull21 } from '../model/aPIDistrictFull21';
import { APIDistrictList21 } from '../model/aPIDistrictList21';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.schooldigger.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum DistrictsApiApiKeys {
    appID,
    appKey,
}

export class DistrictsApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'appID': new ApiKeyAuth('query', 'appID'),
        'appKey': new ApiKeyAuth('query', 'appKey'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: DistrictsApiApiKeys, value: string) {
        (this.authentications as any)[DistrictsApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Retrieve a single district record from the SchoolDigger database
     * @summary Returns a detailed record for one district
     * @param id The 7 digit District ID (e.g. 0642150)
     */
    public async getDistrict (id: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: APIDistrictFull21;  }> {
        const localVarPath = this.basePath + '/v2.3/districts/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getDistrict.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.appID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.appKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: APIDistrictFull21;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "APIDistrictFull21");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Search the SchoolDigger database for districts. You may use any combination of criteria as query parameters.
     * @summary Returns a list of districts
     * @param st Two character state (e.g. \&#39;CA\&#39;) - required
     * @param q Search term - note: will match district name or city (optional)
     * @param city Search for districts in this city (optional)
     * @param zip Search for districts in this 5-digit zip code (optional)
     * @param nearLatitude Search for districts within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only. Enterprise API level will flag districts that include lat/long in its attendance boundary.)
     * @param nearLongitude Search for districts within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only. Enterprise API level will flag districts that include lat/long in its attendance boundary.)
     * @param boundaryAddress Full U.S. address: flag returned districts that include this address in its attendance boundary. Example: \&#39;123 Main St. AnyTown CA 90001\&#39; (optional) (Enterprise API level only)
     * @param distanceMiles Search for districts within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 50 miles) (optional) (Pro, Enterprise API levels only)
     * @param isInBoundaryOnly Return only the districts that include given location (nearLatitude/nearLongitude) or (boundaryAddress) in its attendance boundary (Enterprise API level only)
     * @param boxLatitudeNW Search for districts within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional)
     * @param boxLongitudeNW Search for districts within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional)
     * @param boxLatitudeSE Search for districts within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional)
     * @param boxLongitudeSE Search for districts within a \&#39;box\&#39; defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional)
     * @param page Page number to retrieve (optional, default: 1)
     * @param perPage Number of districts to retrieve on a page (50 max) (optional, default: 10)
     * @param sortBy Sort list. Values are: districtname, distance, rank. For descending order, precede with \&#39;-\&#39; i.e. -districtname (optional, default: districtname)
     * @param includeUnrankedDistrictsInRankSort If sortBy is \&#39;rank\&#39;, this boolean determines if districts with no rank are included in the result (optional, default: false)
     */
    public async searchDistricts (st: string, q?: string, city?: string, zip?: string, nearLatitude?: number, nearLongitude?: number, boundaryAddress?: string, distanceMiles?: number, isInBoundaryOnly?: boolean, boxLatitudeNW?: number, boxLongitudeNW?: number, boxLatitudeSE?: number, boxLongitudeSE?: number, page?: number, perPage?: number, sortBy?: string, includeUnrankedDistrictsInRankSort?: boolean, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: APIDistrictList21;  }> {
        const localVarPath = this.basePath + '/v2.3/districts';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'st' is not null or undefined
        if (st === null || st === undefined) {
            throw new Error('Required parameter st was null or undefined when calling searchDistricts.');
        }

        if (st !== undefined) {
            localVarQueryParameters['st'] = ObjectSerializer.serialize(st, "string");
        }

        if (q !== undefined) {
            localVarQueryParameters['q'] = ObjectSerializer.serialize(q, "string");
        }

        if (city !== undefined) {
            localVarQueryParameters['city'] = ObjectSerializer.serialize(city, "string");
        }

        if (zip !== undefined) {
            localVarQueryParameters['zip'] = ObjectSerializer.serialize(zip, "string");
        }

        if (nearLatitude !== undefined) {
            localVarQueryParameters['nearLatitude'] = ObjectSerializer.serialize(nearLatitude, "number");
        }

        if (nearLongitude !== undefined) {
            localVarQueryParameters['nearLongitude'] = ObjectSerializer.serialize(nearLongitude, "number");
        }

        if (boundaryAddress !== undefined) {
            localVarQueryParameters['boundaryAddress'] = ObjectSerializer.serialize(boundaryAddress, "string");
        }

        if (distanceMiles !== undefined) {
            localVarQueryParameters['distanceMiles'] = ObjectSerializer.serialize(distanceMiles, "number");
        }

        if (isInBoundaryOnly !== undefined) {
            localVarQueryParameters['isInBoundaryOnly'] = ObjectSerializer.serialize(isInBoundaryOnly, "boolean");
        }

        if (boxLatitudeNW !== undefined) {
            localVarQueryParameters['boxLatitudeNW'] = ObjectSerializer.serialize(boxLatitudeNW, "number");
        }

        if (boxLongitudeNW !== undefined) {
            localVarQueryParameters['boxLongitudeNW'] = ObjectSerializer.serialize(boxLongitudeNW, "number");
        }

        if (boxLatitudeSE !== undefined) {
            localVarQueryParameters['boxLatitudeSE'] = ObjectSerializer.serialize(boxLatitudeSE, "number");
        }

        if (boxLongitudeSE !== undefined) {
            localVarQueryParameters['boxLongitudeSE'] = ObjectSerializer.serialize(boxLongitudeSE, "number");
        }

        if (page !== undefined) {
            localVarQueryParameters['page'] = ObjectSerializer.serialize(page, "number");
        }

        if (perPage !== undefined) {
            localVarQueryParameters['perPage'] = ObjectSerializer.serialize(perPage, "number");
        }

        if (sortBy !== undefined) {
            localVarQueryParameters['sortBy'] = ObjectSerializer.serialize(sortBy, "string");
        }

        if (includeUnrankedDistrictsInRankSort !== undefined) {
            localVarQueryParameters['includeUnrankedDistrictsInRankSort'] = ObjectSerializer.serialize(includeUnrankedDistrictsInRankSort, "boolean");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.appID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.appKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: APIDistrictList21;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "APIDistrictList21");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
