/**
 * SchoolDigger API
 * K-12 school and district data for 120,000+ U.S. schools
 *
 * The version of the OpenAPI document: v2.3
 * Contact: api@schooldigger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { APISchoolFull22 } from '../model/aPISchoolFull22';
import { APISchoolList22 } from '../model/aPISchoolList22';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.schooldigger.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum SchoolsApiApiKeys {
    appID,
    appKey,
}

export class SchoolsApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'appID': new ApiKeyAuth('query', 'appID'),
        'appKey': new ApiKeyAuth('query', 'appKey'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: SchoolsApiApiKeys, value: string) {
        (this.authentications as any)[SchoolsApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Retrieve a school record from the SchoolDigger database
     * @summary Returns a detailed record for one school
     * @param id The 12 digit School ID (e.g. 064215006903)
     */
    public async getSchool (id: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: APISchoolFull22;  }> {
        const localVarPath = this.basePath + '/v2.3/schools/{id}'
            .replace('{' + 'id' + '}', encodeURIComponent(String(id)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSchool.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.appID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.appKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: APISchoolFull22;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "APISchoolFull22");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Search the SchoolDigger database for schools. You may use any combination of criteria as query parameters.
     * @summary Returns a list of schools
     * @param st Two character state (e.g. \&#39;CA\&#39;) - required
     * @param q Search term - note: will match school name or city (optional)
     * @param qSearchSchoolNameOnly For parameter \&#39;q\&#39;, only search school names instead of school and city (optional)
     * @param districtID Search for schools within this district (7 digit district id) (optional)
     * @param level Search for schools at this level. Valid values: \&#39;Elementary\&#39;, \&#39;Middle\&#39;, \&#39;High\&#39;, \&#39;Alt\&#39;, \&#39;Public\&#39;, \&#39;Private\&#39; (optional). \&#39;Public\&#39; returns all Elementary, Middle, High and Alternative schools
     * @param city Search for schools in this city (optional)
     * @param zip Search for schools in this 5-digit zip code (optional)
     * @param isMagnet True &#x3D; return only magnet schools, False &#x3D; return only non-magnet schools (optional) (Pro, Enterprise API levels only)
     * @param isCharter True &#x3D; return only charter schools, False &#x3D; return only non-charter schools (optional) (Pro, Enterprise API levels only)
     * @param isVirtual True &#x3D; return only virtual schools, False &#x3D; return only non-virtual schools (optional) (Pro, Enterprise API levels only)
     * @param isTitleI True &#x3D; return only Title I schools, False &#x3D; return only non-Title I schools (optional) (Pro, Enterprise API levels only)
     * @param isTitleISchoolwide True &#x3D; return only Title I school-wide schools, False &#x3D; return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)
     * @param nearLatitude Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)
     * @param nearLongitude Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)
     * @param nearAddress Search for schools within (distanceMiles) of this address. Example: \&#39;123 Main St. AnyTown CA 90001\&#39; (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times
     * @param distanceMiles Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)
     * @param boxLatitudeNW Search for schools within a \&#39;box\&#39; defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
     * @param boxLongitudeNW Search for schools within a \&#39;box\&#39; defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
     * @param boxLatitudeSE Search for schools within a \&#39;box\&#39; defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
     * @param boxLongitudeSE Search for schools within a \&#39;box\&#39; defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
     * @param page Page number to retrieve (optional, default: 1)
     * @param perPage Number of schools to retrieve on a page (50 max) (optional, default: 10)
     * @param sortBy Sort list. Values are: schoolname, distance, rank. For descending order, precede with \&#39;-\&#39; i.e. -schoolname (optional, default: schoolname)
     * @param includeUnrankedSchoolsInRankSort If sortBy is \&#39;rank\&#39;, this boolean determines if schools with no rank are included in the result (optional, default: false)
     */
    public async searchSchools (st: string, q?: string, qSearchSchoolNameOnly?: boolean, districtID?: string, level?: string, city?: string, zip?: string, isMagnet?: boolean, isCharter?: boolean, isVirtual?: boolean, isTitleI?: boolean, isTitleISchoolwide?: boolean, nearLatitude?: number, nearLongitude?: number, nearAddress?: string, distanceMiles?: number, boxLatitudeNW?: number, boxLongitudeNW?: number, boxLatitudeSE?: number, boxLongitudeSE?: number, page?: number, perPage?: number, sortBy?: string, includeUnrankedSchoolsInRankSort?: boolean, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: APISchoolList22;  }> {
        const localVarPath = this.basePath + '/v2.3/schools';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'st' is not null or undefined
        if (st === null || st === undefined) {
            throw new Error('Required parameter st was null or undefined when calling searchSchools.');
        }

        if (st !== undefined) {
            localVarQueryParameters['st'] = ObjectSerializer.serialize(st, "string");
        }

        if (q !== undefined) {
            localVarQueryParameters['q'] = ObjectSerializer.serialize(q, "string");
        }

        if (qSearchSchoolNameOnly !== undefined) {
            localVarQueryParameters['qSearchSchoolNameOnly'] = ObjectSerializer.serialize(qSearchSchoolNameOnly, "boolean");
        }

        if (districtID !== undefined) {
            localVarQueryParameters['districtID'] = ObjectSerializer.serialize(districtID, "string");
        }

        if (level !== undefined) {
            localVarQueryParameters['level'] = ObjectSerializer.serialize(level, "string");
        }

        if (city !== undefined) {
            localVarQueryParameters['city'] = ObjectSerializer.serialize(city, "string");
        }

        if (zip !== undefined) {
            localVarQueryParameters['zip'] = ObjectSerializer.serialize(zip, "string");
        }

        if (isMagnet !== undefined) {
            localVarQueryParameters['isMagnet'] = ObjectSerializer.serialize(isMagnet, "boolean");
        }

        if (isCharter !== undefined) {
            localVarQueryParameters['isCharter'] = ObjectSerializer.serialize(isCharter, "boolean");
        }

        if (isVirtual !== undefined) {
            localVarQueryParameters['isVirtual'] = ObjectSerializer.serialize(isVirtual, "boolean");
        }

        if (isTitleI !== undefined) {
            localVarQueryParameters['isTitleI'] = ObjectSerializer.serialize(isTitleI, "boolean");
        }

        if (isTitleISchoolwide !== undefined) {
            localVarQueryParameters['isTitleISchoolwide'] = ObjectSerializer.serialize(isTitleISchoolwide, "boolean");
        }

        if (nearLatitude !== undefined) {
            localVarQueryParameters['nearLatitude'] = ObjectSerializer.serialize(nearLatitude, "number");
        }

        if (nearLongitude !== undefined) {
            localVarQueryParameters['nearLongitude'] = ObjectSerializer.serialize(nearLongitude, "number");
        }

        if (nearAddress !== undefined) {
            localVarQueryParameters['nearAddress'] = ObjectSerializer.serialize(nearAddress, "string");
        }

        if (distanceMiles !== undefined) {
            localVarQueryParameters['distanceMiles'] = ObjectSerializer.serialize(distanceMiles, "number");
        }

        if (boxLatitudeNW !== undefined) {
            localVarQueryParameters['boxLatitudeNW'] = ObjectSerializer.serialize(boxLatitudeNW, "number");
        }

        if (boxLongitudeNW !== undefined) {
            localVarQueryParameters['boxLongitudeNW'] = ObjectSerializer.serialize(boxLongitudeNW, "number");
        }

        if (boxLatitudeSE !== undefined) {
            localVarQueryParameters['boxLatitudeSE'] = ObjectSerializer.serialize(boxLatitudeSE, "number");
        }

        if (boxLongitudeSE !== undefined) {
            localVarQueryParameters['boxLongitudeSE'] = ObjectSerializer.serialize(boxLongitudeSE, "number");
        }

        if (page !== undefined) {
            localVarQueryParameters['page'] = ObjectSerializer.serialize(page, "number");
        }

        if (perPage !== undefined) {
            localVarQueryParameters['perPage'] = ObjectSerializer.serialize(perPage, "number");
        }

        if (sortBy !== undefined) {
            localVarQueryParameters['sortBy'] = ObjectSerializer.serialize(sortBy, "string");
        }

        if (includeUnrankedSchoolsInRankSort !== undefined) {
            localVarQueryParameters['includeUnrankedSchoolsInRankSort'] = ObjectSerializer.serialize(includeUnrankedSchoolsInRankSort, "boolean");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.appID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.appKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.appKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: APISchoolList22;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "APISchoolList22");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
